"""Authored source/capability/assumption review; values are not calibration data."""
import json,sys,hashlib
from pathlib import Path
from dataclasses import asdict
R=Path(__file__).resolve().parent;sys.path.insert(0,str(R.parent.parent))
from methane.config import Config
from methane.provenance import LOADED_SOURCE
D='2026-09-12'
S=[]
def source(id,title,url,kind,date,scope,access='Primary page inspected'):
 S.append(dict(id=id,title=title,url=url,evidence_type=kind,publication=date,accessed=D,access=access,scope=scope))
source('S01','Ecoppia T4 datasheet','https://www.ecoppia.com/warehouse/temp/ecoppia/T4_Datasheet.pdf','Manufacturer specification','Undated; file label 020321','Single-axis tracker geometry; up to 400 m² nightly, 3 m²/min; own PV dock; vendor maintenance. Product claims, not an independent reliability or cost estimate.','PDF pp. 2–4 inspected')
source('S02','SolarCleano F1','https://www.solarcleano.com/products/remote-solarcleano-f1','Manufacturer specification','Undated current page','Portable remote-controlled wet/dry cleaning with one operator, setup and access limitations. Its stated daily MW coverage is not an autonomous service rate.')
source('S03','ExRobotics products and services','https://www.exrobotics.com/our-products','Manufacturer/service description','Undated current page','Inspection payloads, commissioned routes, charging, connectivity and service provision. Endurance and unattended-period claims lack an exposed fleet denominator.')
source('S04','AutoInspect: Towards Long-Term Autonomous Industrial Inspection','https://arxiv.org/html/2404.12785v2','Primary deployment research','22 April 2024, v2','Two deployments report mission success and minor/serious/fatal interventions. Calendar deployment time differs from active operation and intervention-free duration.','Full HTML, deployment tables inspected')
source('S05','ANYmal X','https://www.anybotics.com/robotics/anymal-x/','Manufacturer specification','Undated current page','Advertised Zone 1 IIB and inspection capabilities. This does not establish IIC hydrogen-area eligibility for the proposed payload and configuration.')
source('S06','Taurob Operator','https://www.taurob.com/operator/','Manufacturer prototype','Undated current page','Explicitly a prototype. Constrained manipulation is a design prospect, not evidence of autonomous hydrogen-system replacement.')
source('S07','A Robot Factors Approach to Designing Modular Hardware','https://www.eecs.harvard.edu/~jkwerfel/iros22melenbrink.pdf','Primary laboratory research','IROS 2022','Prepared mechanical/electrical and water-filter interfaces; redesign enables constrained manipulation. Laboratory tasks are not qualified hydrogen repairs.','Full author PDF inspected')
source('S08','DJI Dock 3 specifications','https://enterprise.dji.com/dock-3/specs','Manufacturer specification','Undated current page','Dock max input 800 W and 12 m/s landing/operation wind specification. Backup power excludes aircraft charging and some thermal loads; maximum draw is not standby demand.')
source('S09','EASA Specific Category — Civil Drones','https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/specific-category-civil-drones','Regulator guidance','Current page accessed on review date','BVLOS operation is an example within the specific category; site and mission authorization remain separate from dock automation. EU scope.')
source('S10','UK CAA categories of UAS operations','https://regulatorylibrary.caa.co.uk/2019-947/Content/AMC-GM/GM1%20Article%203%20Categories%20of.htm','Regulator guidance','Current page accessed on review date','UK operation has its own applicable authorization framework; European product availability is not permission for a London mission.')
source('S11','Reinforcement Learning for RUG','https://www.geckorobotics.com/resources/blog/reinforcement-learning-for-rug','Manufacturer technical account','2 June 2025','Specialist contact/ultrasonic inspection. Requires accessible material and a corresponding integrity model; no generic repair capability.')
source('S12','Renu Robotics autonomous vegetation management','https://renurobotics.com/about-us/','Manufacturer/service account','Undated current page','Renubot, recharge infrastructure and Mission Control remote monitoring form a service system. Does not remove all human maintenance.')
source('S13','Swagelok calibration and switching modules','https://products.swagelok.com/en/all-products/analytical-instrumentation/analytical-subsystems-press/calibrating-switching-modules/c/502?clp=true','Manufacturer subsystem specification','Undated current page','Conditioned sample/reference routing with pneumatic actuation. Not a complete analyzer or a hydrogen-flow calibration procedure.')
source('S14','Endress+Hauser Liquiline Control CDC90','https://www.endress.com/en/field-instruments-overview/liquid-analysis-product-overview/pH-sensor-automatic-cleaning-calibration-cdc90','Manufacturer specification','Undated current page','Automatic pH/ORP cleaning/calibration with compatible assemblies and utilities, non-Ex applications. Not a hydrogen flow meter remedy.')
source('S15','Emerson corrosion and erosion monitoring','https://www.emerson.com/en/measurement-instrumentation/catalog/corrosion-and-erosion-monitoring','Manufacturer technology catalogue','Undated current page','Technology-specific ultrasonic, acoustic and intrusive observations. A sensor family does not confer general fault observability or remaining-life truth.')
source('S16','Rotork IQ3 Pro intelligent actuators','https://www.rotork.com/en/products/electric-intelligent-actuators/iq3-pro','Manufacturer specification','Undated current page','Purpose-built actuation and feedback. Cause-specific reset/interlock semantics require an engineered equipment interface; this product is not evidence for the simulated electrolyser reset.')
source('S17','Maximo completes 100 MW of robotic solar installation','https://www.nasdaq.com/press-release/maximo-completes-100-mw-robotic-solar-installation-2026-03-25','Company press release hosted by Nasdaq','25 March 2026','Company-reported installation deployment. Construction task scope and site crews remain; not independent O&M autonomy evidence.')
source('S18','Next-generation Terafab completes field testing','https://www.terabase.energy/resources/terabase-energys-next-generation-terafab-completes-field-testing-ready-for-deployment','Manufacturer announcement','19 March 2026','Version-specific field-test/deployment announcement; planned availability is not a completed fleet deployment.')
source('S19','5B Maverick','https://5b.co/en/5b-maverick','Manufacturer specification','Undated current page','Pre-wired deployable PV blocks use people and a telehandler. A site design alternative, not autonomous daily maintenance.')
source('S20','DOE technical targets for PEM electrolysis','https://www.energy.gov/cmei/fuels/technical-targets-proton-exchange-membrane-electrolysis','Government status/target table','2022 status and 2026 targets displayed','System 55 kWh/kg is a status guidepost; target 51 kWh/kg is aspirational. Continuous-life values do not determine intermittent-duty fault rates.')
source('S21','Hydrogen Shot Water Electrolysis Technology Assessment','https://www.energy.gov/sites/default/files/2024-12/hydrogen-shot-water-electrolysis-technology-assessment.pdf','Government technical assessment','December 2024','Stack and balance-of-plant scope, dynamic durability and development needs. No equipment-specific repair hazard or duration for this fixture.','Relevant PDF sections inspected')
source('S22','Enapter EL 4.1 handbook','https://handbook.enapter.com/electrolyser/el41/','OEM operating documentation','Current online handbook','AEM equipment illustrates cause-specific faults, reset conditions, service escalation, utilities, telemetry and venting. Structural analogy only; do not transfer AEM numerical values to an unspecified 450 kW plant.')
source('S23','Bronkhorst MV-191-H2 datasheet','https://products.bronkhorst.com/media/lbmdbkcf/3276-mv-191-h2-en-datasheet.pdf','Manufacturer metrology specification','Modification printed 01-12-2025','Range-dependent reading/full-scale accuracy and temperature effects differ from 2% independent Gaussian noise. Flow/pressure scope is not a proposed plant meter selection.','PDF specification inspected')
source('S24','DNV hydrogen and renewable flow calibration','https://www.dnv.com/energy/services/laboratories-test-facilities/technology-centre-groningen-the-netherlands/hydrogen-and-renewable-flow-calibration/','Calibration facility description','Undated current page','Hydrogen-specific reference facilities and operating ranges. Blend calibration uncertainties cannot be transferred to pure-H2 or arbitrary on-site calibration.')
source('S25','Ignition and flow stopping considerations for hydrogen networks','https://hysafe.info/uploads/papers/2023/114.pdf','Primary HSE-authored technical paper','2023','Hydrogen gas-group IIC distinction; paper network/pressure scope differs from this plant. Used only to flag equipment certification compatibility.','Relevant PDF passage inspected')
source('S26','Soiling losses — impact on photovoltaic power plants','https://iea-pvps.org/wp-content/uploads/2023/01/IEA-PVPS-T13-21-2022-EXEC-SUMM-Soiling-Losses-PV-Plants.pdf','IEA PVPS technical report executive summary','2022 report; January 2023 file','Site-dependent soiling and measurement uncertainty. Global loss estimates are not London, Seville or Copenhagen daily deposition rates.','Three-page executive summary inspected')
source('S27','EU harmonised protocols for testing low temperature water electrolysers','https://publications.jrc.ec.europa.eu/repository/bitstream/JRC122565/jrc122565_ltwe_harmonisation_online_identifier_4.pdf','JRC technical testing protocol','2021','Reference conditions and measurement requirements; dynamic loading, cold starts and standby transitions require specified tests. Not field failure-rate data.','PDF contents and relevant testing sections inspected')
source('S28','Determination of reaction kinetics in three phase CO₂ methanation','https://publikationen.bibliothek.kit.edu/1000188810/171087110','Peer-reviewed primary research, author repository','Online December 2025; journal issue March 2026','Reaction enthalpy and heat-management rationale supported; the liquid/catalyst experiment does not calibrate the fixture thermal capacity, heat loss or operating band.','Author-hosted publisher PDF inspected; DOI 10.1039/D5RE00337G')

F=[]
def family(id,name,status,allowed,unsupported,prerequisites,support,model,sources):
 F.append(dict(id=id,name=name,feasibility=status,permitted_scope=allowed,unavailable_scope=unsupported,prerequisites=prerequisites,support=support,current_model=model,sources=sources,reviewed=D))
family('F01','Dedicated solar-row cleaner','Conditional commercial','Dry removal of compatible loose deposits on prepared rows.','One generic robot serving arbitrary array geometry; removal of permanent damage.','Named cleaner/module/tracker combination; parking, bridges, clearances, approved operating weather.','Per-row docks, communications, brushes, inspection, retrieval and vendor maintenance.','Section optical treatment exists; generic 1,000 m²/h and bus-fed charger are not T4 parameters.',['S01','S26'])
family('F02','Portable wet/dry cleaner','Commercial, human operated','Person-deployed and supervised compatible cleaning.','Unattended deployment or operation inferred from remote control.','Access, lifting/transport, module limits, water method, operator availability.','Travel, setup, water/refill, battery charging, consumables, return journey.','Portable wet service/logistics implemented as illustrative bundle.',['S02'])
family('F03','Mobile ground inspector','Conditional commercial','Commissioned visual/thermal/acoustic/gas observations with appropriate payload.','Repair, unqualified hydrogen-area access, or universal fault localization.','Route, lighting, terrain, stairs, reachable view/port and gas-group/payload certificate.','Dock, mapping, connectivity, remote assistance, retrieval, batteries and vendor service.','Mobile prepared-contact reader exists; not a realistic visual/thermal inspection model.',['S03','S04','S05','S25'])
family('F04','Docked aerial inspector','Conditional commercial','Permitted repeatable visual/thermal survey.','General manipulation, concealed-fault diagnosis or permission implied by autonomy.','Flight authorization, site airspace, landing margin, weather and inspection conditions.','Dock mains/backup, internet, aircraft maintenance, remote pilot responsibilities and retrieval.','Catalogue concept; no complete flight/payload mechanism reviewed.',['S08','S09','S10'])
family('F05','Contact inspection crawler','Specialist commercial','Compatible contact/ultrasonic material measurements.','Repair or automatic launch on every process surface.','Reachable material, coupling/contact, geometry and a thickness/degradation hypothesis.','Preparation, qualified interpretation, deployment/retrieval, sensor maintenance.','No corresponding wall-integrity process in current plant.',['S11'])
family('F06','Vegetation-management robot','Conditional commercial','Mapped vegetation cutting on suitable ground.','Universal terrain operation or value without vegetation/access mechanics.','Terrain/obstacles, exclusion rules, growth and shading/access effects.','Charging pod, Mission Control, blade service, weather and recovery.','Future site-operations mechanism.',['S12'])
family('F07','Sampling and analyzer station','Commercial engineered subsystem','Switch and condition compatible process/reference samples.','Complete chemical diagnosis or certification from a selector alone.','Analyzer, gas compatibility, flow/pressure conditioning, transport/purge delays.','Reference gases, filters, utilities, calibration, purge/sample accounting.','No complete analyzer/sample-chain model.',['S13'])
family('F08','Automatic sensor service station','Commercial for named sensors','Clean/calibrate a compatible pH/ORP sensor using the specified station.','Generic autonomous hydrogen-flow calibration.','Matching sensor, references, retractable assembly and permitted environment.','Reagents, reference replacement, waste, pneumatics and technician service.','Generic calibration remedy lacks identified H2 metrology procedure.',['S14','S24'])
family('F09','Rugged fixed sensor package','Conditional commercial','Named electrical/process/material measurements with bounded error.','Perfect inventory, exact loose/adhered fractions or generic remaining-life truth.','Measurement model, range, placement, references and channel independence.','Calibration, drift checks, protection, power/comms and replacement.','Fixed contact/reference acquisition exists; other ideal plant observations remain.',['S15','S23','S27'])
family('F10','Remote actuator / redundant service path','Conditional engineered capability','Command and verify a specified permitted action after cause clearance.','Reset repairing physical damage; bypass of unresolved trips.','OEM semantics, permissives, position/process feedback, power and communication.','Actuator maintenance, stored-energy provision where required, testing and fallback.','Latched trip reset exists; only an illustrative engineered interface.',['S16','S22'])
family('F11','Mobile maintenance manipulator','Prototype / speculative for this plant','Separate prepared-site research tasks.','Credible default autonomous electrolyser repair or consumable exchange.','Reach, tool, torque, connectors, isolation and acceptance specification.','Tooling, fixtures, remote supervision, parts and recovery.','Future capability; do not substitute rover inspection for manipulation.',['S06'])
family('F12','Robot-compatible replaceable module','Design principle demonstrated in laboratory','Explicitly speculative purpose-designed module scenario.','Qualified hydrogen module replacement inferred from a water-filter lab demo.','Guides/connectors, depressurization/isolation, lifting, seals and proof tests.','Spare compatibility, handling, waste, tools and trained fallback.','Current human module replacement is generic; robotic replacement not established.',['S07','S22'])
family('F13','Solar construction robot','Company-reported commercial deployments','Construction-phase installation assistance on compatible designs.','Ongoing maintenance autonomy or whole-site commissioning from panel placement alone.','Foundation/tracker readiness, logistics, quality acceptance and crew workflow.','Mobilization, transport, rented equipment, operators and commissioning.','Separate build-phase scenario; not daily service comparison.',['S17','S18'])
family('F14','Pre-integrated deployable solar array','Commercial, crew assisted','Alternative array/deployment design.','An autonomous maintenance robot.','Ground preparation, access, footprint, wind design and compatible cleaning.','Transport, crew, telehandler, electrical commissioning and O&M access.','Separate plant-design alternative.',['S19'])

A=[]
def assumption(id,priority,claim,binding,current,role,evidence,gap,consequence,action,check='Numerical checks do not establish empirical validity'):
 A.append(dict(id=id,priority=priority,claim=claim,binding=binding,current=current,units='As specified in current',role=role,sources=evidence,range_or_gap=gap,consequence=consequence,required_change_or_evidence=action,independent_check=check,review=dict(date=D,reviewer='Codex source/code review; not a hardware qualification',source_hash=LOADED_SOURCE['content_hash'],outcome='Conditional use / evidence gap',permitted_use='Explicit illustrative or threshold study only until listed evidence is supplied',invalidate_on='Change to bound mechanism, hardware/interface, evidence scope or operating envelope')))
assumption('A01',0,'A generic module replacement restores capacity damage','methane/faults.py: service; FaultPolicy.capacity_cause','equipment-damage → nominal capacity after successful module-replacement','Feasibility/restoration',['S22','S07'],'No component-specific cause or compatible replacement procedure identified.','Remedy may not exist; a faster repair simulation cannot answer its value.','Specify pump/power-stage/stack cause separately, named remedy, prerequisites and acceptance; unresolved causes require human escalation.')
assumption('A02',0,'A trip may be cleared by a remote reset','FieldOperations.reset_enabled; services/plant.py; faults.py','Latched resettable-trip; reset duration 0.25 h','Action availability',['S22','S16'],'Cause-clearance and actual OEM interface unbound.','A nominal reset could mask a persistent unsafe/process condition.','Model cause clearance, reset eligibility, command feedback and successful process tracking separately.')
assumption('A03',0,'Flow bias is removable by a generic calibration task','FaultPolicy / services/core.py calibration capability','Successful calibration clears injected bias','Metrology/remedy',['S14','S24','S23'],'No named H2 meter, reference path or on-site procedure. pH/ORP station is incompatible evidence.','Invalid repair option distorts downtime and robot value.','Choose a specific meter and permitted verification/replacement/calibration workflow; otherwise leave fault unresolved.')
assumption('A04',0,'Inventory provides independent high-quality H2 balance','methane/sensing.py: observe','Noise SD = hourly H2 production × 0.02; exact when production = 0','Observability',['S23','S27'],'No pressure/temperature/volume metrology or measured error covariance.','Current diagnosis may lose identifiability with range errors or drift.','Replace with declared measurement chain; propagate difference-of-reading and outflow uncertainty.','Eight observation stress sequences show isolation lost under unmodelled drift.')
assumption('A05',0,'Downstream outflow and other states are known exactly','methane/sensing.py: observe','Exact H2 outflow, battery energy, CO2 and reactor temperature','Observability',['S23','S27'],'Ideal sensors; no independent errors or common cause.','Mass-balance fault localization receives unrealistic information.','Identify separate channels and errors; keep retrospective truth separate.')
assumption('A06',0,'Soil types are distinguishable without an inspection task','services/surface.py: Surface.public','Exact section loose/adhered/damaged fractions exposed','Observability',['S26'],'No optical/soiling station inference model.','Condition cleaning has perfect information; treatment choice overstates autonomy.','Use irradiance/reference-cell or inspection evidence with ambiguity; ideal monitor remains teaching-only.')
assumption('A07',0,'Mobile and fixed readers provide independent fault evidence','services/inspection.py: classify/sample/evidence','Two readers can share one trip contact; zero/span references','Information independence',['S22'],'References check acquisition, not the physical contact or equipment.','Agreeing readers cannot exclude a shared stuck contact.','Represent sensor-to-hypothesis graph and common causes; require independent process evidence.','Shared-contact equivalence and seven voltage boundary cases checked.')
assumption('A08',0,'The cleaner works on the chosen array layout','ServiceSystem.cleaning_model, row_accessible; solar design','Generic row access; area 5 m²/kW; 1,000 m²/h','Feasibility/fleet size',['S01','S02'],'No installed cleaner/array pairing. T4 up to 400 m²/night on near-flat trackers is not this fixture.','Single asset can become a distributed fleet with altered cost and downtime.','Bind task to geometry and measured cycle; separate dedicated-row and portable products.')
assumption('A09',0,'Inspection robot may approach the hydrogen equipment','ServiceSystem.inspection_interface; service route graph','Accessible port; no gas-zone or payload certification model','Access',['S05','S25'],'Advertised IIB does not establish IIC H2 eligibility. Site zone unspecified.','An assumed inspection action can be unavailable.','Keep path outside restricted area or require matching certificate/site classification; do not infer approval.')
assumption('A10',0,'Human replacement reliably clears all capacity-loss causes','FieldOperations.human_fallback/human_work_hours/repair_success_probability','Human fallback; 2 h work; success 0.95','Fallback capability',['S22'],'No cause-specific parts, isolation, test and expert qualification.','Human baseline is also optimistic, affecting relative and absolute rankings.','Specify complete procedure, unreachable/irreparable cases and escalation; do not use a generic repair probability.')
assumption('A11',1,'Field availability can be inferred from saved European weather','ServiceSystem.environment_source/assumed_wind_mps/assumed_rain_mmph; runs/weather','Default fixed 3 m/s and 0 mm/h; cached snapshots lack wind/rain','Joint exposure',['S01','S08','S26'],'No site service-window evidence or precipitation-driven soil removal.','Weather can simultaneously create need and prevent work.','Add provenance-preserving wind/precipitation data and joint access scenarios; missing data must remain unavailable.')
assumption('A12',1,'European soiling accumulates at the fixture rate','FieldOperations.soiling_per_day','0.005 fraction/day; no rain wash-off','Service demand',['S26'],'Explicit gap: 0.5 percentage point/day is not a site rate or confidence bound.','Cleaning benefit can be manufactured by unsupported deposition.','Site/season monitoring; rain/dew/adhered effects; threshold studies until then.')
assumption('A13',1,'Treatments remove a fixed fraction and wear predictably','FieldOperations.cleaning_removal_fraction; ServiceSystem.brush_life_m2','Loose removal .9; brush life 50,000 m²; wet adhered .7','Restoration/wear',['S01','S02','S26'],'No module/deposit/brush field calibration; permanent damage is separately retained.','Repeated work may be ineffective or damage coatings.','Pair-specific efficacy/wear evidence; never use dust-removal claim for bonded deposits.')
assumption('A14',1,'Robot mission failure is an independent fixed probability','FieldOperations.mission_failure_probability; ServiceSystem.outcome_randomness','0.05 per mission; matched target/action stream option','Reliability',['S04','S03'],'No duration/exposure/cause-specific hazard fit or denominator.','Longer or repeated missions change failure exposure artificially.','Log distance/time/weather/interventions; separate repeatable failure causes and common support outages.')
assumption('A15',1,'Robot/dock energy resembles the installed product','FieldOperations cleaner/rover battery, mission_power_kw, dock_kw; ServiceSystem.dock_standby_kw','2 kWh packs; .2 kW mission; 1 kW dock; default zero standby, review .05 kW','Energy/support',['S01','S03','S08'],'No measured duty/load curve. T4 own PV, drone dock max 800 W are different boundaries.','Shared plant energy and autonomy margins change.','Separate traction/payload/standby/thermal/dock loads and independent supply; no max-to-average transfer.')
assumption('A16',1,'Mission durations cover the whole service cycle','FieldOperations.clean_hours/inspect_hours; ServiceSystem travel/verification hours','2 h clean, 1 h inspect; .5 h travel, .25 h verification','Timing',['S01','S02','S04'],'No route length, commissioning, view quality, setup or test procedure calibration.','Apparent intervention-free performance omits human work.','Measured full-cycle durations with remote and site effort separated.')
assumption('A17',1,'Human/remote support will be available on request','ServiceSystem support_model, crew shifts, response, travel, remote hours','Optional logistics/1; example 2 h response, 1 h travel; finite shifts/stocks','Support',['S03','S04'],'No European supplier SLA, shared fleet contention or adverse-weather response data.','Robot failures can create prolonged stranded assets.','Contract/crew scope and distributions; count return journeys, retrieval, maintenance and unserved work.')
assumption('A18',1,'Spares, brushes and water are compatible and replenishable','ServiceSystem portable water/stock/supplier fields; FieldOperations kits','12 cleaning kits, 2 service kits; default 1,000 L portable tank; review 4,000 L','Support/consumables',['S02','S07','S24'],'Generic kits; no exact part/reference shelf life or supplier stock evidence.','Tasks become impossible when compatibility or water fails.','Part IDs, storage conditions, supply delay, water quality/waste and replenishment limits.')
assumption('A19',1,'Injected fault timing represents maintenance demand','Scenario.fault_start_hour/capacity_fraction; FaultPolicy','One scheduled fault, persistent unless repaired or explicitly transient','Exposure',['S21','S27'],'No event frequency, competing failure modes, degradation or environmental hazard fit.','A 48 h injected event cannot justify annual robot savings.','Treat as challenge; obtain service logs or present break-even incidents/year without claiming incidence.')
assumption('A20',1,'Capacity loss reduces all electrolysis capability proportionally','FaultPolicy.capacity_cause; simulation execution capacity','Scalar available kW; unchanged conversion efficiency','Fault consequence',['S20','S21','S22'],'Pump fault, stack ageing, contamination and sensor fault have different effects.','Same derating can understate complete shutdown or efficiency loss.','Create cause→physics→observations→allowed remedies contract.')
assumption('A21',1,'Electrolysis has constant efficiency and simple starts','Plant.specific_energy_kwh_per_kg/min_load/start_kwh','55 kWh/kg; 30% minimum; 40 kWh/start','Production/start value',['S20','S27'],'55 is a PEM status guidepost; load, temperature, cold/standby/purge curves uncalibrated.','Recovered electricity may yield a different amount or incur downtime.','Use system-level measured load/start maps; distinguish stack vs balance-of-plant.')
assumption('A22',1,'Missing auxiliaries cannot change service value','methane/physics.py scope; Plant auxiliary values','No pressure dynamics, purge/vent losses, compression, water treatment or detailed cooling circuit','Plant boundary',['S21','S22'],'Utilities unspecified. An hourly balanced sandbox is not a complete process energy audit.','Important failures or start costs may be absent entirely.','Declare pressure/purity/utility interfaces; add only consequential auxiliary loads and failure modes.')
assumption('A23',1,'The reactor thermal response is representative','Plant thermal_capacity/heat_loss/heater/cooling/band/minimum_run','0.3 kWh/K; .08 kW/K; 60/40 kW; 250–400°C; 4 h run','Delayed response',['S28'],'Reaction exotherm supported; C, UA, band and commitments are illustrative.','Warm-up, heat retention and capacity-repair value can change direction.','Obtain design/step-response envelope; continue analytic sensitivity as conditional evidence.','864 Decimal exponential cases reconcile within 1e-9°C; no empirical validation.')
assumption('A24',1,'CO2 supply and initial stocks permit useful extra production','Plant co2_delivery_kg/every_hours, initial_co2_kg, initial_h2_kg','300 kg/day; 500 kg initial CO2; H2 empty','Bottleneck/terminal effect',[],'Supply contract and delivered gas condition unspecified.','Repairs/cleaning may restore capacity with no methane gain because feedstock binds.','Publish cumulative inputs/ending inventories and constrained shadow value.','Independent supply bound 109.09 kg CH4/day; initial stock supports 181.82 kg.')
assumption('A25',1,'Sabatier mass and heat arithmetic are appropriate','methane/physics.py ratios; reactor.py REACTION_KWH_PER_KG','MW H2/CO2/CH4/H2O=2/44/16/18; 165 MJ/kmol','Numerical mechanism',['S28'],'Ideal conversion; no kinetic/selectivity/gas-quality certification.','Exact arithmetic cannot validate full reactor design.','Retain ideal chemistry label; separate produced methane from accepted product.','Independent mass equality and 2.864583 kWh/kg checked.')
assumption('A26',1,'Short matched windows identify economic service value','Scenario.hours; initial inventories; service open orders','48 h core, 240 h extension; no terminal sales','Interpretation',[],'No annual site utilization/fault process.','Postponed work or consumed initial stock can manufacture apparent savings.','Retain all terminal states/unresolved obligations and extend every matched arm; no annualization.')
assumption('A27',1,'Service prices are representative European costs','HydrogenCosts field asset/human/maintenance defaults; service_economics.illustrative','Cleaner €15k, rover €80k, dock €5k; 8-year life; human €80/h; other activity assumptions','Economics',['S03'],'No supplier quote or local labor/insurance/transport contract.','Ownership/contract preference can reverse.','Use fixed-trace break-even thresholds; report cash expenditure, allocation and decision cost separately.')
assumption('A28',1,'Costs account for wear without duplicate ownership charges','methane/service_economics.py; services/pricing.py','Replaceable capital separated; max(calendar,usage,parts) allocation; expenditure separate','Accounting',[],'Arithmetic convention, not actual invoices; contract inclusions need review.','Double counting or omitted inclusions biases ranking.','Preserve accounting reconciliation and explicit price/version boundaries.','Independent per-run audit and targeted economic tests.')
assumption('A29',2,'Robotic actuator completion proves restored operation','services/verification.py and investigation/recovery variants','Versioned contact/process evidence and optional scheduled tests','Recovery acceptance',['S22','S27'],'Actual test load/duration/acceptance depend on cause and instrumentation.','False restoration or insufficient power delays confirmation.','Keep physical restoration, service receipt and observation confirmation timestamps distinct.')
assumption('A30',2,'Schematic routes and hourly dispatch establish field response','ServiceSystem graph; Plant.dt_hours','Hourly plant plus fractional service events; illustrated paths','Resolution',[],'No geometric navigation, emergency controls or pressure-system dynamics.','Animation can imply capabilities beyond the calculation.','Keep illustrations as task explanation; emergency/safety and navigation behavior outside validated scope.')
assumption('A31',2,'Other hardware families are ready to add as interchangeable robots','F04–F14 capability entries','Uneven commercial maturity; most absent as full mechanisms','Architecture',['S06','S07','S13','S17','S19'],'Each needs its own task/effect/sensor/support contract.','A common class label can conceal unavailable mechanics.','Expand only after family-specific feasibility gate, not generic success rate.')
# Two positive reviews have narrower permission than the evidence-gap defaults.
for a in A:
 if a['id'] in ('A25','A28'):
  a['review']['outcome']='Numerically supported within the declared abstraction';a['review']['permitted_use']='Mechanism/accounting checks under stated inputs; no empirical plant or cost validation.'
catalogue=json.loads((R.parent/'field-robotics/catalogue.json').read_text())['archetypes']
for original,review in zip(catalogue,F,strict=True):
 assert original['name']==review['name'], (original['name'],review['name'])
 review['review_id']=review['id'];review['id']=original['id']
 review['catalogue_schema']='dispatch-lab/research-field-robotics/1'
for name,rows,schema in [('sources',S,'realism-sources/1'),('capabilities',F,'realism-capabilities/1'),('assumptions',A,'realism-assumptions/1')]:
 (R/(name+'.json')).write_text(json.dumps(dict(schema_version=schema,review_date=D,source_hash=LOADED_SOURCE['content_hash'],items=rows),indent=2,ensure_ascii=False)+'\n')
(R/'review-context.json').write_text(json.dumps(dict(date=D,scope='Existing illustrative fixture; London, Seville and Copenhagen; no site/OEM calibration',source=LOADED_SOURCE,defaults=asdict(Config()),production_changes=False,broad_programme='remains paused'),indent=2)+'\n')
print('Wrote',len(S),'sources,',len(F),'families,',len(A),'assumptions')
