const {test,expect}=require('@playwright/test');
async function project(page){await page.goto('/');await page.locator('.m-plant').waitFor();await page.locator('[data-do=menu]').click();await page.locator('[data-do=project]').click();await page.locator('.pj-sites button').filter({hasText:'Seville'}).click();await page.locator('[data-pj=create]').click();await expect(page.locator('.pj-build')).toBeVisible();await page.locator('.pj-header [data-pj=tools]').click();await page.locator('[data-pj=equipment-basis]').click();}
test('equipment reference, commissioning, observed comparison, report and original interval navigation',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await project(page);
 await page.locator('[data-eq=propose]').click();await expect(page.locator('.eq-proposal')).toContainText('448');await expect(page.locator('.eq-proposal')).toContainText('112 / 2.16');await page.locator('[data-eq=apply]').click();await expect(page.locator('.eq-status')).toContainText('Reference applied');await expect(page.locator('.eq-body')).toContainText('reference assumptions match');await page.screenshot({path:'build/equipment-basis.png'});
 await page.locator('[data-eq=review]').click();await expect(page.locator('.eq-body')).toContainText('not reviewed');await page.locator('[name=reviewer]').fill('Browser rehearsal');await page.locator('[name=artifact_name]').fill('Fixture review');await page.locator('[name=artifact_text]').fill('No field acceptance data has been supplied.');await page.locator('[name=rationale]').fill('Leave commissioning incomplete.');await page.locator('[data-eq=save-review]').click();await expect(page.locator('.eq-status')).toContainText('Review edition saved');await page.locator('[data-eq-artifact]').first().click();await expect(page.locator('.eq-artifact')).toContainText('No field acceptance');
 await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();await page.locator('[data-pj=dismiss]').click();await page.locator('.pj-build-bottom [data-pj=operate]').click();await page.locator('[data-pj-weather]').selectOption('synthetic');await page.locator('[data-pj-hours]').selectOption('24');await page.locator('[data-pj-controller]').selectOption('Greedy');await page.locator('[data-pj=run]').click();await expect(page.locator('[data-pj-play]')).toBeVisible({timeout:60000});
 await page.getByRole('button',{name:'Equipment basis',exact:true}).click();await expect(page.locator('.eq-workspace')).toContainText('This run · original');await page.locator('[data-eq=observe]').click();await page.locator('[data-eq=import-form]').click();await page.locator('[name=name]').fill('Synthetic meter rehearsal');await page.locator('[name=asset]').fill('ELY-01 / test only');await page.locator('[name=supplied_by]').fill('Test fixture');await page.locator('[name=source_reference]').fill('Browser synthetic acceptance');await page.locator('[name=origin]').selectOption('synthetic test');await page.locator('[name=method]').fill('Synthetic test values, no field measurement.');await page.locator('[name=uncertainty_absolute]').fill('2');await page.locator('[name=redistribution]').selectOption('permitted');await page.locator('[name=csv_text]').fill('timestamp,value,quality\n2025-07-10T00:00:00Z,2,valid\n2025-07-10T01:00:00Z,,missing\n');await page.locator('[data-eq=import]').click();await expect(page.locator('.eq-status')).toContainText('Observations saved');await page.locator('[data-eq=compare]').click();await expect(page.locator('.eq-result')).toContainText('1/2 hours paired');await expect(page.locator('.eq-result')).toContainText('Synthetic exercise');await expect(page.locator('.eq-result')).toContainText('observation missing');
 await page.locator('[data-eq-result]').first().click();await expect(page.locator('.eq-result')).toContainText('1/2 hours paired');await page.locator('[data-eq-findings]').fill('Missing measurement remains excluded. This is a UI exercise.');await page.locator('[data-eq=publish]').click();await expect(page.locator('.eq-export a')).toContainText('Open saved report');const report=await page.request.get(await page.locator('.eq-export a').getAttribute('href'));expect(await report.text()).toContain('Synthetic exercise');await page.locator('[data-eq=export]').click();await expect(page.locator('.eq-export a[download]')).toBeVisible({timeout:30000});await page.screenshot({path:'build/equipment-comparison.png'});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'build/equipment-mobile.png'});await page.locator('[data-eq-trace]').first().click();await expect(page.locator('.eq-workspace')).toBeHidden();await expect(page.locator('.pj-workspace')).toBeHidden();await expect(page.locator('[data-do=project-revise]')).toBeVisible({timeout:20000});expect(errors).toEqual([]);
});
test('changing evidence context or closing discards a delayed proposal',async({page})=>{
 await project(page);await page.route('**/dispatch/sites',async route=>{const b=route.request().postDataJSON();if(b.operation==='equipment-proposal'){await new Promise(r=>setTimeout(r,600));await route.fulfill({json:{key:b.key,reference:{name:'Stale sentinel',scope:'Must not appear'},changes:[]}});}else await route.continue();});
 await page.locator('[data-eq=propose]').click();await page.locator('[data-eq=review]').click();await page.waitForTimeout(800);await expect(page.locator('.eq-body')).not.toContainText('Stale sentinel');await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();
});

test('optional plant interfaces validate, run, trace and return without changing the illustration',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await project(page);await page.locator('[data-eq=interfaces]').click();await expect(page.locator('.eq-body')).toContainText('Not enabled');await page.locator('[name=enabled]').check();await page.locator('[name=initial_water_l]').fill('999');await page.locator('[data-eq=save-integration]').click();await expect(page.locator('.eq-status')).toContainText('exceeds tank capacity');await page.locator('[name=initial_water_l]').fill('40');await page.locator('[name=water_delivery_l]').fill('100');await page.locator('[name=water_every_hours]').fill('6');await page.locator('[data-eq=save-integration]').click();await expect(page.locator('.eq-status')).toContainText('Plant interfaces saved');await expect(page.locator('.eq-body')).toContainText('Enabled for this design');await page.screenshot({path:'build/plant-interfaces.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'build/plant-interfaces-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();await page.locator('[data-pj=dismiss]').click();await page.locator('.pj-build-bottom [data-pj=operate]').click();await page.locator('[data-pj-weather]').selectOption('synthetic');await page.locator('[data-pj-hours]').selectOption('24');await page.locator('[data-pj-controller]').selectOption('Greedy');await page.locator('[data-pj=run]').click();await expect(page.locator('[data-pj-play]')).toBeVisible({timeout:60000});await page.getByRole('button',{name:'Equipment basis',exact:true}).click();await page.locator('[data-eq=interfaces]').click();await expect(page.locator('.eq-body')).toContainText('Original assumption');await page.locator('[data-eq=integration-trace]').click();await expect(page.locator('.eq-integration-trace')).toContainText('Recorded execution');await expect(page.locator('.eq-integration-trace')).toContainText('40 + 0 − 0 = 40 L');await page.screenshot({path:'build/plant-interface-trace.png'});await page.locator('[data-eq-integration-hour]').fill('6');await page.locator('[data-eq=integration-trace]').click();await expect(page.locator('.eq-integration-trace')).toContainText('100 L offered');await page.locator('[data-eq=integration-replay]').click();await expect(page.locator('.eq-workspace')).toBeHidden();await expect(page.locator('.pj-workspace')).toBeHidden();await expect(page.locator('.m-plant')).toBeVisible();expect(errors).toEqual([]);
});

test('qualification freezes criteria, traces discrepancies and preserves a readable report',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await project(page);await page.locator('[data-eq=propose]').click();await page.locator('[data-eq=apply]').click();await expect(page.locator('.eq-status')).toContainText('Reference applied');await page.keyboard.press('Escape');await page.locator('[data-pj=dismiss]').click();await page.locator('.pj-build-bottom [data-pj=operate]').click();await page.locator('[data-pj-weather]').selectOption('synthetic');await page.locator('[data-pj-hours]').selectOption('24');await page.locator('[data-pj-controller]').selectOption('Greedy');await page.locator('[data-pj=run]').click();await expect(page.locator('[data-pj-play]')).toBeVisible({timeout:60000});await page.getByRole('button',{name:'Equipment basis',exact:true}).click();await page.locator('[data-eq=observe]').click();await page.locator('[data-eq=import-form]').click();
 for(const [k,v] of Object.entries({name:'Qualification rehearsal',asset:'ELY test',supplied_by:'Browser test',source_reference:'Synthetic fixture',method:'No site evidence',uncertainty_absolute:'2',csv_text:'timestamp,value,quality\n2025-07-10T00:00:00Z,2,valid\n2025-07-10T01:00:00Z,3,valid\n2025-07-10T02:00:00Z,4,valid\n2025-07-10T03:00:00Z,0,valid\n'}))await page.locator(`[name=${k}]`).fill(v);
 await page.locator('[name=origin]').selectOption('synthetic test');await page.locator('[name=redistribution]').selectOption('permitted');await page.locator('[data-eq=import]').click();await expect(page.locator('.eq-status')).toContainText('Observations saved');await page.locator('[data-eq=qualification]').click();await page.locator('[data-eq=evidence-plan]').click();await expect(page.locator('.eq-evidence-plan')).toContainText('Public evidence is the primary modelling basis');await page.locator('[data-eq=qualification-form]').click();
 for(const [k,v] of Object.entries({title:'Synthetic qualification check',reviewer:'Test author',split_hour:'4',end_hour:'4',max_rmse:'3',max_absolute_bias:'2',minimum_pairs:'2',rationale:'Matched artificial night-time fixture; numerical check only.'}))await page.locator(`[data-eq-protocol] [name=${k}]`).fill(v);
 await page.locator('[data-eq-protocol] [name=comparable]').selectOption('true');await page.locator('[data-eq=qualification-freeze]').click();await expect(page.locator('.eq-status')).toContainText('non-overlapping');await page.locator('[data-eq-protocol] [name=split_hour]').fill('2');await page.locator('[data-eq=qualification-freeze]').click();await expect(page.locator('.eq-status')).toContainText('Protocol frozen');await page.locator('[data-eq-evaluate]').first().click();await expect(page.locator('.eq-assessment')).toContainText('within declared numerical criteria');await expect(page.locator('.eq-assessment')).toContainText('Synthetic exercise');await expect(page.locator('.eq-assessment')).toContainText('Hour 2: -4');await page.locator('[data-eq-assessment-findings]').fill('The software criteria pass; this provides no field qualification.');await page.locator('[data-eq=qualification-publish]').click();await expect(page.locator('.eq-export a')).toContainText('Open assessment report');const response=await page.request.get(await page.locator('.eq-export a').getAttribute('href'));expect(await response.text()).toContain('Scoped equipment assessment');await page.locator('[data-eq=export]').click();await expect(page.locator('.eq-export a[download]')).toBeVisible({timeout:30000});await page.locator('.eq-assessment').scrollIntoViewIfNeeded();await page.screenshot({path:'build/equipment-qualification.png'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'build/equipment-qualification-mobile.png'});await page.locator('[data-eq-discrepancy]').first().click();await expect(page.locator('.eq-workspace')).toBeHidden();await expect(page.locator('.m-plant')).toBeVisible();expect(errors).toEqual([]);
});

test('researched interfaces preview assumptions, reject invalid inputs and trace saved execution',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await project(page);await page.locator('[data-eq=interfaces]').click();await expect(page.locator('[data-eq-research]')).toBeHidden();await page.locator('[name=enabled]').check();await page.locator('[name=research_enabled]').check();await expect(page.locator('[data-eq-research]')).toBeVisible();await page.locator('[data-eq=integration-preview]').click();await expect(page.locator('.eq-model-preview')).toContainText('Learning preview');await expect(page.locator('.eq-model-preview')).toContainText('3.089 kWh reaction heat');await expect(page.locator('.eq-model-preview')).toContainText('0.759 kWh feed heating');await page.locator('[data-eq=research-sources]').click();await expect(page.locator('.eq-research-sources')).toContainText('PV inverter reference curve');await expect(page.locator('.eq-research-sources a')).toHaveCount(6);await page.locator('[name=research_feed_recovery_fraction]').fill('1');await page.locator('[data-eq=integration-preview]').click();await expect(page.locator('.eq-model-preview')).toContainText('assumed recovery 0.535');await expect(page.locator('.eq-model-preview')).toContainText('2.865 kWh net');await page.locator('[name=research_feed_recovery_fraction]').fill('0');
 await page.locator('[name=research_reactor_reference_c]').fill('200');await expect(page.locator('.eq-model-preview')).toBeEmpty();await page.locator('[data-eq=integration-preview]').click();await expect(page.locator('.eq-status')).toContainText('226.85');await page.locator('[name=research_reactor_reference_c]').fill('300');await page.locator('[data-eq=integration-preview]').click();await expect(page.locator('.eq-model-preview')).toContainText('Learning preview');expect((await page.locator('[data-eq=integration-preview]').boundingBox()).height).toBeLessThan(60);await page.locator('.eq-model-preview').scrollIntoViewIfNeeded();await page.screenshot({path:'build/researched-models-preview.png'});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.eq-model-preview').scrollIntoViewIfNeeded();await page.screenshot({path:'build/researched-models-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.locator('[data-eq=save-integration]').click();await expect(page.locator('.eq-status')).toContainText('Plant interfaces saved');await expect(page.locator('[name=research_enabled]')).toBeChecked();await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();await page.locator('[data-pj=dismiss]').click();await page.locator('.pj-build-bottom [data-pj=operate]').click();await page.locator('[data-pj-weather]').selectOption('synthetic');await page.locator('[data-pj-hours]').selectOption('24');await page.locator('[data-pj-controller]').selectOption('Greedy');await page.locator('[data-pj=run]').click();await expect(page.locator('[data-pj-play]')).toBeVisible({timeout:60000});await page.getByRole('button',{name:'Equipment basis',exact:true}).click();await page.locator('[data-eq=interfaces]').click();await expect(page.locator('.eq-body')).toContainText('Original research choices');await page.locator('[data-eq-integration-hour]').fill('12');await page.locator('[data-eq=integration-trace]').click();await expect(page.locator('.eq-integration-trace')).toContainText('researched-interfaces/1');await expect(page.locator('.eq-integration-trace')).toContainText('Recorded piecewise source analogue');await expect(page.locator('.eq-integration-trace')).toContainText('available thermal capacity');await page.screenshot({path:'build/researched-models-trace.png'});await page.locator('[data-eq=integration-replay]').click();await expect(page.locator('.m-plant')).toBeVisible();expect(errors).toEqual([]);
});

test('research preview cannot overwrite newer inputs',async({page})=>{
 await project(page);await page.locator('[data-eq=interfaces]').click();await page.locator('[name=research_enabled]').check();await page.route('**/dispatch/sites',async route=>{const b=route.request().postDataJSON();if(b.operation==='equipment-integration-preview')await new Promise(r=>setTimeout(r,600));await route.continue();});await page.locator('[data-eq=integration-preview]').click();await page.locator('[name=research_coolant_c]').fill('35');await page.waitForTimeout(1000);await expect(page.locator('.eq-model-preview')).toBeEmpty();await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();
});
