const {test,expect}=require('@playwright/test');
async function project(page){await page.goto('/');await page.locator('.m-plant').waitFor();await page.locator('[data-do=menu]').click();await page.locator('[data-do=project]').click();await page.locator('.pj-sites button').filter({hasText:'Seville'}).click();await page.locator('[data-pj=create]').click();await expect(page.locator('.pj-build')).toBeVisible();await page.locator('.pj-header [data-pj=tools]').click();await page.locator('[data-pj=equipment-basis]').click();}
test('equipment reference, commissioning, observed comparison, report and original interval navigation',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await project(page);
 await page.locator('[data-eq=propose]').click();await expect(page.locator('.eq-proposal')).toContainText('448');await expect(page.locator('.eq-proposal')).toContainText('112 / 2.16');await page.locator('[data-eq=apply]').click();await expect(page.locator('.eq-status')).toContainText('Reference applied');await expect(page.locator('.eq-body')).toContainText('reference assumptions match');await page.screenshot({path:'build/equipment-basis.png'});
 await page.locator('[data-eq=review]').click();await expect(page.locator('.eq-body')).toContainText('not reviewed');await page.locator('[name=reviewer]').fill('Browser rehearsal');await page.locator('[name=artifact_name]').fill('Fixture review');await page.locator('[name=artifact_text]').fill('No field acceptance data has been supplied.');await page.locator('[name=rationale]').fill('Leave commissioning incomplete.');await page.locator('[data-eq=save-review]').click();await expect(page.locator('.eq-status')).toContainText('Review edition saved');await page.locator('[data-eq-artifact]').first().click();await expect(page.locator('.eq-artifact')).toContainText('No field acceptance');
 await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();await page.locator('[data-pj=dismiss]').click();await page.locator('.pj-build-bottom [data-pj=operate]').click();await page.locator('[data-pj-weather]').selectOption('synthetic');await page.locator('[data-pj-hours]').selectOption('24');await page.locator('[data-pj-controller]').selectOption('Greedy');await page.locator('[data-pj=run]').click();await expect(page.locator('[data-pj-play]')).toBeVisible({timeout:60000});
 await page.getByRole('button',{name:'Equipment basis',exact:true}).click();await expect(page.locator('.eq-workspace')).toContainText('This run · original');await page.locator('[data-eq=observe]').click();await page.locator('[data-eq=import-form]').click();await page.locator('[name=name]').fill('Synthetic meter rehearsal');await page.locator('[name=asset]').fill('ELY-01 / test only');await page.locator('[name=supplied_by]').fill('Test fixture');await page.locator('[name=source_reference]').fill('Browser synthetic acceptance');await page.locator('[name=origin]').selectOption('synthetic test');await page.locator('[name=method]').fill('Synthetic test values, no field measurement.');await page.locator('[name=uncertainty_absolute]').fill('2');await page.locator('[name=redistribution]').selectOption('permitted');await page.locator('[name=csv_text]').fill('timestamp,value,quality\n2025-07-10T00:00:00Z,2,valid\n2025-07-10T01:00:00Z,,missing\n');await page.locator('[data-eq=import]').click();await expect(page.locator('.eq-status')).toContainText('Observations saved');await page.locator('[data-eq=compare]').click();await expect(page.locator('.eq-result')).toContainText('1/2 hours paired');await expect(page.locator('.eq-result')).toContainText('Synthetic exercise');await expect(page.locator('.eq-result')).toContainText('observation missing');
 await page.locator('[data-eq-result]').first().click();await expect(page.locator('.eq-result')).toContainText('1/2 hours paired');await page.locator('[data-eq-findings]').fill('Missing measurement remains excluded. This is a UI exercise.');await page.locator('[data-eq=publish]').click();await expect(page.locator('.eq-export a')).toContainText('Open saved report');const report=await page.request.get(await page.locator('.eq-export a').getAttribute('href'));expect(await report.text()).toContain('Synthetic exercise');await page.locator('[data-eq=export]').click();await expect(page.locator('.eq-export a[download]')).toBeVisible({timeout:30000});await page.screenshot({path:'build/equipment-comparison.png'});
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'build/equipment-mobile.png'});await page.locator('[data-eq-trace]').first().click();await expect(page.locator('.eq-workspace')).toBeHidden();await expect(page.locator('.pj-workspace')).toBeHidden();await expect(page.locator('[data-do=project-revise]')).toBeVisible({timeout:20000});expect(errors).toEqual([]);
});
test('changing evidence context or closing discards a delayed proposal',async({page})=>{
 await project(page);await page.route('**/dispatch/sites',async route=>{const b=route.request().postDataJSON();if(b.operation==='equipment-proposal'){await new Promise(r=>setTimeout(r,600));await route.fulfill({json:{key:b.key,reference:{name:'Stale sentinel',scope:'Must not appear'},changes:[]}});}else await route.continue();});
 await page.locator('[data-eq=propose]').click();await page.locator('[data-eq=review]').click();await page.waitForTimeout(800);await expect(page.locator('.eq-body')).not.toContainText('Stale sentinel');await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();
});
