const {test,expect}=require('@playwright/test');

test('investigation controls reveal prerequisites, retain edits and return to the quiet plant',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await page.locator('.m-plant').waitFor();
  await page.locator('[data-do="menu"]').click();
  await page.locator('[data-do="setup"]').first().click();
  await page.getByText('Field operations / robots, recovery and human service',{exact:true}).click();
  const service=page.getByRole('checkbox',{name:'Coordinate service work with MPC (experimental)',exact:true});
  const enabled=page.getByRole('checkbox',{name:'Plan investigations from returned evidence',exact:true});
  const version=page.getByRole('combobox',{name:'Investigation follow-through',exact:true});
  await expect(enabled).toBeHidden();await service.check();
  await expect(enabled).not.toBeChecked();await expect(version).toBeHidden();
  await enabled.focus();await page.keyboard.press('Space');
  await expect(version).toHaveValue('Remedies with nominated operating tests (version 2)');
  const threshold=page.getByRole('spinbutton',{name:'Further repair: minimum assumed impairment probability',exact:true});
  await expect(threshold).toBeHidden();
  await version.click();
  await page.getByRole('option',{name:'Carry uncertainty through work and tests (version 3)',exact:true}).click();
  await expect(threshold).toBeVisible();await expect(threshold).toHaveValue('0.5');
  await threshold.fill('0.7');
  await version.click();
  await page.getByRole('option',{name:'Remedies with nominated operating tests (version 2)',exact:true}).click();
  await expect(threshold).toBeHidden();
  await version.click();
  await page.getByRole('option',{name:'Carry uncertainty through work and tests (version 3)',exact:true}).click();
  await expect(threshold).toHaveValue('0.7');
  await expect(page.getByText(/The default prior is illustrative/)).toBeVisible();
  const strategy=page.getByRole('combobox',{name:'Investigation strategy',exact:true});
  await strategy.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');
  await expect(strategy).toHaveValue('Inspect first');const chosen=await strategy.inputValue();
  const wait=page.getByRole('spinbutton',{name:'Wait for the finding / hours',exact:true});
  await wait.fill('2.5');
  await page.setViewportSize({width:390,height:844});await wait.scrollIntoViewIfNeeded();
  await expect(wait).toBeVisible();await enabled.uncheck();await expect(wait).toBeHidden();
  await enabled.check();await expect(wait).toHaveValue('2.5');await expect(strategy).toHaveValue(chosen);
  await page.getByRole('button',{name:'RUN EXPERIMENT →',exact:true}).click();
  await expect(page.getByText(/INCOMPLETE \/ NOT RUN:.*whole number/)).toBeVisible();
  await page.getByRole('button',{name:'← Simulation',exact:true}).click();
  await expect(page.locator('.m-plant')).toBeVisible();await expect(enabled).toBeHidden();
  expect(await page.locator('.methane-console button:visible').count()).toBe(5);
  expect(errors).toEqual([]);
});
