const {test,expect}=require('@playwright/test');
async function open(page){await page.goto('/');await page.locator('.m-plant').waitFor();await page.locator('[data-do=menu]').click();await page.locator('[data-do=project]').click();await page.locator('.pj-sites button').filter({hasText:'Seville'}).click();await page.locator('[data-pj=create]').click();await expect(page.locator('.pj-build')).toBeVisible();await page.locator('.pj-header [data-pj=tools]').click();await page.locator('[data-pj=equipment-basis]').click();await page.locator('[data-eq=literature]').click();await expect(page.locator('[data-lt=run]')).toBeVisible();}
test('reference experiments compare boundaries, uncertainty, saved editions and offline reports',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page);
 await page.locator('[data-lt=run]').click();await expect(page.locator('.lt-result')).toContainText('csu-pem-affine/1');await expect(page.locator('.lt-result')).toContainText('0.01199');await expect(page.locator('.lt-plot')).toBeVisible();await page.locator('[data-lt=details]').click();await expect(page.locator('.lt-details')).toContainText('Startup and AEM transfer');await expect(page.locator('.lt-details')).toContainText('0.01506');
 await page.locator('[name=query_kw]').fill('99');await expect(page.locator('.lt-result')).toBeEmpty();await page.locator('[data-lt=run]').click();await expect(page.locator('.eq-status')).toContainText('no extrapolation');await page.locator('[data-lt=reset]').click();await page.locator('[name=flow_offset_bound]').fill('0.01');await page.locator('[data-lt=run]').click();await expect(page.locator('.lt-result')).toContainText('Common flow-offset scenarios: 0.31907–0.33907');
 await page.locator('[data-lt=source]').click();await expect(page.locator('.lt-source')).toContainText('timezone unspecified');await expect(page.locator('.lt-source')).toContainText('smps_power + subsystem_power + chiller_power');await page.locator('[data-lt=source]').click();
 await page.locator('[name=power]').selectOption('stack_power');await page.locator('[name=channel]').selectOption('hydrogen_flow_cs');await page.locator('[name=model]').selectOption('constant-specific');await page.locator('[data-lt=run]').click();await expect(page.locator('.lt-result')).toContainText('csu-pem-constant-specific/1');
 await page.locator('[data-lt-profile]').selectOption('kit-slurry');await page.locator('[data-lt=run]').click();await expect(page.locator('.lt-result')).toContainText('kit-slurry-first-order/1');await expect(page.locator('.lt-result')).toContainText('0.48979');await page.locator('[data-lt=details]').click();await expect(page.locator('.lt-details')).toContainText('Held-out validation · missing');await expect(page.locator('.lt-details')).toContainText('9.299');await page.locator('[data-lt=details]').click();await page.locator('.lt-result').scrollIntoViewIfNeeded();await page.screenshot({path:'build/literature-models/desktop.png'});
 await page.locator('[data-lt-findings]').fill('Reference-device response only; this does not establish ambient heat loss.');await page.locator('[data-lt=publish]').click();await expect(page.locator('.lt-export a')).toContainText('Open reference report');const url=await page.locator('.lt-export a').getAttribute('href');const report=await page.request.get(url);expect(await report.text()).toContain('Reference-device experiment');expect(await report.text()).toContain('Original inputs and fitted parameters');await page.locator('[data-lt=export]').click();await expect(page.locator('.lt-export a[download]')).toBeVisible({timeout:30000});
 await page.locator('[data-lt=saved]').click();await expect(page.locator('[data-lt-result]').first()).toBeVisible();await page.locator('[data-lt-result]').filter({hasText:'csu-pem-affine/1'}).first().click();await expect(page.locator('.lt-result')).toContainText('csu-pem-affine/1');await expect(page.locator('.eq-status')).toContainText('No recomputation');await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('.lt-result').scrollIntoViewIfNeeded();await page.screenshot({path:'build/literature-models/mobile.png'});await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();expect(errors).toEqual([]);
});
test('reference responses cannot cross input, topic or workspace changes',async({page})=>{
 await open(page);await page.route('**/dispatch/sites',async route=>{if(route.request().postDataJSON().operation==='equipment-literature-run')await new Promise(r=>setTimeout(r,700));await route.continue();});await page.locator('[data-lt=run]').click();await page.locator('[name=query_kw]').fill('40');await page.waitForTimeout(1000);await expect(page.locator('.lt-result')).toBeEmpty();await page.locator('[data-lt=run]').click();await page.locator('[data-lt-profile]').selectOption('kit-slurry');await page.waitForTimeout(1000);await expect(page.locator('.lt-result')).toBeEmpty();await expect(page.locator('[name=query_minutes]')).toBeVisible();await page.locator('[data-lt=run]').click();await page.locator('[data-eq=basis]').click();await page.waitForTimeout(1000);await expect(page.locator('.eq-body')).toContainText('What is this design based on');await expect(page.locator('.lt-result')).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.locator('[data-pj=equipment-basis]')).toBeFocused();
});
