const {test,expect}=require('@playwright/test');
async function project(page){await page.goto('/');await page.locator('.m-plant').waitFor();await page.locator('[data-do=menu]').click();await page.locator('[data-do=project]').click();await page.locator('.pj-sites button').first().click();await page.locator('[data-pj=create]').click();await expect(page.locator('.pj-build')).toBeVisible();}
test('operating brief freezes future runs, assesses actual output, traces equipment and exports a readable edition',async({page})=>{
 test.setTimeout(120000);const errors=[];page.on('pageerror',err=>errors.push(err.message));await project(page);
 await page.locator('.pj-build-bottom [data-pj=operate]').click();await page.locator('[data-pj=requirements]').click();await expect(page.locator('.rq-workspace')).toBeVisible();
 await page.locator('[data-rq-field=name]').fill('Night production commitment');await page.locator('[data-rq-field=methane_kg]').fill('20');await page.locator('[data-rq-field=window_hours]').fill('1');await page.locator('[data-rq-field=battery_kwh]').fill('900');await page.locator('[data-rq-field=rationale]').fill('Keep one hourly commitment visible; test a deliberately undersized battery.');
 await page.locator('[data-rq=save]').click();await expect(page.locator('.rq-status')).toContainText('Brief saved');
 await page.screenshot({path:'build/requirements-brief.png'});await page.keyboard.press('Escape');await expect(page.locator('[data-pj=requirements]')).toBeFocused();
 await page.locator('[data-pj-weather]').selectOption('synthetic');await page.locator('[data-pj-hours]').selectOption('24');await page.locator('[data-pj-controller]').selectOption('Greedy');await page.locator('[data-pj=run]').click();await expect(page.locator('[data-pj-play]')).toBeVisible({timeout:60000});
 await page.getByRole('button',{name:'Assess requirements',exact:true}).click();await expect(page.locator('[data-rq-study]:checked')).toHaveCount(1);await page.locator('[data-rq=assess]').click();await expect(page.locator('.rq-groups')).toBeVisible({timeout:40000});
 await expect(page.locator('.rq-case')).toContainText('declared before execution');await expect(page.locator('.rq-case')).toContainText('Configured capacity cannot meet');await expect(page.locator('.rq-groups')).toContainText('1 unmet');await expect(page.locator('.rq-groups')).toContainText('1/1 exposure cells');await page.screenshot({path:'build/requirements-comparison.png'});
 await page.locator('[data-rq=writeup]').click();await page.locator('[data-rq-findings]').fill('The selected design cannot cover this explicit brief.');await page.locator('[data-rq=publish]').click();await expect(page.locator('.rq-extra a')).toContainText('Open saved report');const report=await page.request.get(await page.locator('.rq-extra a').getAttribute('href'));expect(await report.text()).toContain('Night production commitment');
 await page.locator('[data-rq=export]').click();await expect(page.locator('.rq-extra a[download]')).toBeVisible({timeout:30000});
 await page.setViewportSize({width:390,height:844});await expect(page.locator('[data-rq-case]')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'build/requirements-mobile.png'});
 await page.locator('[data-rq-trace]').first().click();await expect(page.locator('.rq-workspace')).toBeHidden();await expect(page.locator('.pj-workspace')).toBeHidden();await expect(page.locator('[data-do=project-revise]')).toBeVisible({timeout:20000});expect(errors).toEqual([]);
});
test('invalid requirements remain editable and old assessments never replace a newer selection',async({page})=>{
 await project(page);await page.locator('.pj-header [data-pj=tools]').click();await page.locator('[data-pj=requirements]').click();await page.locator('[data-rq-field=name]').fill('Invalid test');await page.locator('[data-rq-field=methane_kg]').fill('1');await page.locator('[data-rq-field=shortfall_kg]').fill('2');await page.locator('[data-rq=save]').click();await expect(page.locator('.rq-status')).toContainText('cannot exceed');await expect(page.locator('[data-rq-field=shortfall_kg]')).toHaveValue('2');
 await page.locator('[data-rq-field=shortfall_kg]').fill('0');await page.locator('[data-rq=save]').click();await expect(page.locator('.rq-status')).toContainText('Brief saved');
 await page.route('**/dispatch/sites',async route=>{const b=route.request().postDataJSON();if(b.operation==='requirements-index'){const response=await route.fetch(),value=await response.json();value.assessments=[{id:'a'.repeat(64),title:'Old delayed assessment'}];await route.fulfill({json:value});}else if(b.operation==='requirements-result'){await new Promise(r=>setTimeout(r,500));await route.fulfill({json:{key:b.key,id:b.id,title:'Stale sentinel'}});}else await route.continue();});
 await page.keyboard.press('Escape');await page.locator('[data-pj=requirements]').click();await page.locator('nav [data-rq=compare]').click();const saved=page.locator('[data-rq-result]').first();await saved.click();await page.locator('nav [data-rq=brief]').click();await page.waitForTimeout(700);await expect(page.locator('.rq-workspace h1')).toHaveText('What must this plant provide?');
 await page.keyboard.press('Escape');await expect(page.locator('.pj-workspace')).toBeVisible();
});
