const {test,expect}=require('@playwright/test');
test('Sites preserves the simulation while saving a sourced regional design',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await page.locator('.m-plant').waitFor();
 const original=await page.locator('.m-plant').innerHTML();
 await page.locator('[data-do=menu]').click();await page.locator('[data-do=sites]').click();
 await expect(page.locator('.si-workspace')).toBeVisible();
 await expect(page.locator('.si-site-list')).toContainText('London regional anchor');
 await expect(page.locator('.si-marker')).toHaveCount(3);
 expect((await page.locator('.si-map canvas').boundingBox()).height).toBeGreaterThan(500);
 await page.locator('.si-site-list button').filter({hasText:'London regional anchor'}).click();
 await expect(page.locator('.si-detail')).toContainText('1,010.3');
 await page.locator('[data-si=design]').click();
 await expect(page.locator('.si-plant-preview svg')).toBeVisible();
 await page.locator('[data-design=name]').fill('Browser reference design');
 await page.locator('[data-si=save-design]').click();
 await expect(page.locator('.si-status')).toContainText('Design saved');
 await expect(page.locator('.si-detail')).toContainText('Browser reference design');
 await page.keyboard.press('Escape');
 await expect(page.locator('.si-workspace')).toBeHidden();
 expect(await page.locator('.m-plant').innerHTML()).toBe(original);
 await expect(page.locator('[data-do=sites]')).toBeFocused();
 await page.locator('[data-do=sites]').click();
 await page.locator('.si-site-list button').filter({hasText:'London regional anchor'}).click();
 await page.setViewportSize({width:390,height:844});
 await expect(page.locator('.si-detail h1')).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'build/siting-workspace-mobile.png'});
 await page.setViewportSize({width:1440,height:1000});
 await page.locator('[data-si=dismiss]').click();
 await page.waitForTimeout(1000);
 await page.screenshot({path:'build/siting-workspace.png'});
 expect(errors).toEqual([]);
});
