const {test,expect}=require('@playwright/test');
async function open(page){await page.goto('/');await page.locator('.m-plant .battery-component').click();await page.getByRole('button',{name:'Explore component',exact:true}).click();await expect(page.locator('.x-workspace')).toBeVisible();await expect(page.locator('.x-status')).not.toHaveText('Opening catalogue…');if(await page.locator('.x-layout').isHidden()){await page.locator('[data-x=context]').selectOption('Current catalogue');}await expect(page.locator('.x-main h1')).toHaveText('Battery');}
test('explorer preserves the component, controller, hour and focus through nested Model navigation',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page);await expect(page.locator('.x-art svg')).toBeVisible();
 await page.locator('[data-x-view=Operation]').click();await expect(page.locator('.x-content')).toContainText('no interval has executed');
 await page.locator('[data-x-view="Model & evidence"]').click();await page.locator('.x-content [data-model-topic=battery]').first().click();await expect(page.locator('.d-workspace')).toBeVisible();await page.keyboard.press('Escape');
 await expect(page.locator('.d-workspace')).toBeHidden();await expect(page.locator('.x-workspace')).toBeVisible();await expect(page.locator('.x-content [data-model-topic=battery]').first()).toBeFocused();
 expect(await page.locator('.m-plant-wrap').evaluate(n=>n.inert)).toBeTruthy();await page.keyboard.press('Escape');await expect(page.locator('.x-workspace')).toBeHidden();await expect(page.getByRole('button',{name:'Explore component',exact:true})).toBeFocused();expect(await page.locator('.m-plant-wrap').evaluate(n=>n.inert)).toBeFalsy();expect(errors).toEqual([]);
});
test('dependencies lead to shared resources, overview and scoped hardware families',async({page})=>{
 await open(page);await page.locator('[data-x-view=Dependencies]').click();await page.locator('.x-content [data-x-node="system:bus"]').first().click();await expect(page.locator('.x-main h1')).toHaveText('Electrical bus');
 await page.locator('[data-x-view=Dependencies]').click();await page.locator('.x-content [data-x-node="PLANT-01/ELY-01"]').click();await expect(page.locator('.x-main h1')).toHaveText('Electrolyser');
 await page.locator('[data-x-view=Service]').click();await expect(page.locator('.x-content')).toContainText('An inspection does not imply repair');
 await page.locator('[data-x=browse]').click();await page.locator('[data-x=search]').fill('row cleaner');await page.locator('[data-x=search]').fill('row-cleaner');await page.locator('.x-results [data-x-node="family:row-cleaner"]').click();await expect(page.locator('.x-content')).toContainText('permitted_scope');await expect(page.locator('.x-content')).toContainText('unavailable_scope');
 await page.locator('[data-x-view="Model & evidence"]').click();await expect(page.locator('.x-content a[href^="https://www.ecoppia.com"]').first()).toBeVisible();await expect(page.locator('.x-content')).toContainText('grants no repair capability');
});
test('search keeps future concepts optional and works on a narrow screen',async({page})=>{
 await page.setViewportSize({width:390,height:844});await open(page);await page.locator('[data-x=browse]').click();await page.locator('[data-x=search]').fill('predictive maintenance');await expect(page.locator('.x-results')).toContainText('No matching');await page.locator('[data-x=concepts]').check();await page.locator('.x-results button').click();await expect(page.locator('.x-summary')).toContainText('No execution capability');
 expect(await page.locator('.x-workspace').evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBeTruthy();await page.locator('[data-x-view=Operation]').click();await expect(page.locator('.x-content')).toContainText('no live operating state');await page.screenshot({path:'build/taxonomy/mobile.png'});await page.keyboard.press('Escape');await expect(page.locator('.x-workspace')).toBeHidden();
});
test('late catalogue responses do not replace a newer context',async({page})=>{
 await page.route('**/dispatch/taxonomy',async route=>{const req=route.request().postDataJSON();if(req.context==='This run'){await new Promise(r=>setTimeout(r,650));await route.fulfill({status:200,json:{key:req.key,run_id:req.run_id,graph:null,note:'Late old context'}});}else await route.continue();});
 await page.goto('/');await page.locator('.m-plant .battery-component').click();await page.getByRole('button',{name:'Explore component',exact:true}).click();await page.locator('[data-x=context]').selectOption('Current catalogue');await expect(page.locator('.x-main h1')).toHaveText('Battery');await page.waitForTimeout(800);await expect(page.locator('.x-status')).not.toContainText('Late old context');await page.screenshot({path:'build/taxonomy/desktop.png'});
});
test('failed catalogue request has a visible recovery path',async({page})=>{
 await page.route('**/dispatch/taxonomy',route=>route.fulfill({status:503,json:{detail:'Test service unavailable'}}));await page.goto('/');await page.locator('.m-plant .battery-component').click();await page.getByRole('button',{name:'Explore component',exact:true}).click();await expect(page.locator('.x-status')).toContainText('Test service unavailable');await expect(page.locator('.x-layout')).toBeHidden();await page.keyboard.press('Escape');await expect(page.locator('.x-workspace')).toBeHidden();
});
test('saved service snapshot connects target, interface, capability, actor and support offline',async({page})=>{
 const file=process.env.DISPATCH_TAXONOMY_OFFLINE;test.skip(!file,'Requires the generated coupled service reproduction fixture.');
 await page.route('http://**/*',route=>route.abort());await page.route('https://**/*',route=>route.abort());await page.goto('file://'+file);await page.getByRole('button',{name:'Step forward',exact:true}).click();await page.locator('.m-plant .stack-component').click();await page.locator('.m-inspector [data-explore=electrolyser]').click();await expect(page.locator('.x-status')).toContainText('Original catalogue captured');await expect(page.locator('[data-x=context]')).toBeDisabled();
 await page.locator('[data-x-view=Service]').click();await page.locator('.x-content [data-x-node="interfaces:ELY/contact"]').click();await page.locator('[data-x-view=Service]').click();await page.locator('.x-content [data-x-node="capabilities:inspection"]').click();await page.locator('[data-x-view=Service]').click();await page.locator('.x-content [data-x-node="PLANT-01/ROVER-01"]').click();await page.locator('[data-x-view=Operation]').click();await expect(page.locator('.x-content')).toContainText('service information at decision');await page.locator('[data-x-view=Dependencies]').click();await page.locator('.x-content [data-x-node="resources:energy:rover"]').click();await expect(page.locator('.x-main h1')).toHaveText('energy:rover');await page.screenshot({path:'build/taxonomy/offline-resource.png'});await page.keyboard.press('Escape');await expect(page.locator('.m-inspector [data-explore=electrolyser]')).toBeFocused();
});
test('solar and service entry points return to their original workspace',async({page})=>{
 await page.goto('/');await page.locator('.m-plant .solar-component').click();await page.locator('.s-assumptions>summary').filter({hasText:'MODEL AND EVIDENCE'}).click();await page.locator('.s-workspace [data-explore=solar]').click();await expect(page.locator('.x-workspace')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.s-workspace')).toBeVisible();await expect(page.locator('.s-workspace [data-explore=solar]')).toBeFocused();await page.locator('[data-s=back]').click();await page.locator('[data-do=menu]').click();await page.locator('[data-panel=services]').click();await page.locator('[data-explore=services]').click();await expect(page.locator('.x-workspace')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('[data-explore=services]')).toBeFocused();
});
