const {test,expect}=require('@playwright/test');
async function open(page){await page.goto('/');await page.locator('.m-plant').waitFor();await page.getByRole('button',{name:'Simulation menu',exact:true}).click();await page.locator('[data-do=studies]').click();await page.locator('[data-u=open]').click();await expect(page.locator('[data-u=parameter]')).toBeVisible();}
test('uncertainty editor covers complete catalogue, previews worlds and restores context',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await open(page);await expect(page.locator('.st-panel-body')).toContainText('467 registered parameters');await page.locator('[data-u=search]').fill('roundtrip_efficiency');await page.locator('[data-u=parameter]').selectOption('plant.roundtrip_efficiency');await expect(page.locator('[data-u=visibility]')).toHaveValue('hidden');await page.locator('[data-u=values]').fill('0.85, 0.95');await page.locator('[data-u=add]').click();await page.locator('[data-u=worlds]').fill('2');await page.locator('[data-u=seeds]').fill('7');await page.locator('[data-u=preview]').click();await expect(page.locator('[data-u=start]')).toBeEnabled();await expect(page.locator('.u-preview')).toContainText('2 worlds × 1 event seeds');await expect(page.locator('.u-preview')).toContainText('0.9');await page.screenshot({path:'build/uncertainty/editor-desktop.png'});
 await page.locator('[data-u=worlds]').fill('3');await expect(page.locator('[data-u=start]')).toBeDisabled();await page.keyboard.press('Escape');await page.locator('[data-st=back]').click();await expect(page.locator('.st-workspace')).toBeHidden();await expect(page.locator('[data-do=studies]')).toBeFocused();expect(errors).toEqual([]);
});
test('invalid probability requests and late previews cannot enable execution',async({page})=>{
 await open(page);await page.locator('[data-u=search]').fill('roundtrip_efficiency');await page.locator('[data-u=add]').click();await page.locator('[data-u=design]').selectOption('probability');await page.locator('[data-u=preview]').click();await expect(page.locator('.u-preview')).toContainText('no probabilities');await expect(page.locator('[data-u=start]')).toBeDisabled();
 await page.locator('[data-u=design]').selectOption('space-filling');let held=false;await page.route('**/dispatch/studies',async route=>{const b=route.request().postDataJSON();const r=await route.fetch();if(b.operation==='uncertainty-preview'&&!held){held=true;await new Promise(x=>setTimeout(x,400));}await route.fulfill({response:r});});await page.locator('[data-u=preview]').click();await page.locator('[data-u=worlds]').fill('5');await page.waitForTimeout(600);await expect(page.locator('[data-u=start]')).toBeDisabled();
});
test('all observation channels and narrow-screen keyboard workflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});await open(page);await page.locator('[data-u=channel]').selectOption('temperature_c');await page.locator('[data-u=noise]').fill('2');await page.locator('[data-u=bias]').fill('1');await page.locator('[data-u=measure]').focus();await page.keyboard.press('Enter');await expect(page.locator('.u-measurements')).toContainText('temperature_c');await page.screenshot({path:'build/uncertainty/editor-mobile.png'});expect(await page.locator('.st-workspace').evaluate(n=>n.scrollWidth<=n.clientWidth+1)).toBeTruthy();await page.locator('[data-u=unmeasure]').click();await expect(page.locator('.u-measurements')).not.toContainText('temperature_c');
});
test('reviewed world executes in a frozen worker and produces traceable envelopes',async({page})=>{
 test.skip(!process.env.DISPATCH_BROWSER_HOURS,'Dedicated short current-run fixture');test.setTimeout(120000);await open(page);await page.locator('[data-u=search]').fill('roundtrip_efficiency');await page.locator('[data-u=values]').fill('0.88');await page.locator('[data-u=add]').click();await page.locator('[data-u=worlds]').fill('1');await page.locator('[data-u=seeds]').fill('7');await page.locator('[data-u=preview]').click();await expect(page.locator('[data-u=start]')).toBeEnabled();await page.locator('[data-u=start]').click();await expect(page.locator('.st-article h1')).toContainText('assumptions');await expect(page.locator('.st-status')).toHaveText('Study write-up saved',{timeout:90000});await expect(page.locator('.st-article')).toContainText('1/1 world/event cases complete');await expect(page.locator('.u-envelope svg')).toHaveCount(3);await page.locator('[data-u=trajectory]').selectOption('temperature_c');await expect(page.locator('.u-envelope svg').first()).toHaveAttribute('aria-label',/temperature_c/);await page.screenshot({path:'build/uncertainty/report-browser.png'});await page.locator('.st-article button[data-case]').first().click();await expect(page.locator('.st-panel-body')).toContainText('Original uncertainty realization');await expect(page.locator('.st-panel-body')).toContainText('0.88');await expect(page.locator('.st-panel-body')).toContainText('0.9');await page.locator('[data-trace=methane_kg]').first().click();await expect(page.locator('.st-panel-body')).toContainText('uncertainty_world');await page.keyboard.press('Escape');await page.locator('[data-st=export]').click();await expect(page.locator('.st-download a')).toBeVisible({timeout:60000});
});
