"""Render the authored release note from original programme/report outputs.

Arguments: main summary, deadline summary, computation-repeat summary,
calibration result. All numerical displays read those saved inputs.
"""
import html
import json
import statistics
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT=Path(__file__).resolve().parent
main,window,repeated,calibration=[json.loads(Path(p).read_text()) for p in sys.argv[1:5]]
expected=('c03f2ebfebde491ea7ce927701f35bf2','07c1a191609d4cf89ff694d2a33e67bb','621aec1013f54ddf867731447170cd24')
if tuple(Path(x['report']).parent.parent.name for x in (main,window,repeated))!=expected:
    raise ValueError('This authored interpretation applies only to its declared programme editions. Changed plant parameters need their own reviewed interpretation; generic Study reports remain available.')
paths=[str(Path(p).resolve().relative_to(ROOT)) for p in sys.argv[1:5]]
bench=json.loads((ROOT/'preview-240h-batch.json').read_text())
source=main['source_hashes'][0]
final_source=json.loads((ROOT/'validation/source-under-test-final.json').read_text())['source']['content_hash']
final_suites=ET.parse(ROOT/'validation/pytest-final.xml').getroot()
final_tests=sum(int(s.get('tests',0)) for s in final_suites)
if any(int(s.get('failures',0))+int(s.get('errors',0)) for s in final_suites):
    raise ValueError('Do not publish a passing regression claim from failed tests')
rows=main['cases']
valid=[r for r in rows if r['status']=='complete']
audit_pass=sum((r.get('audit') or {}).get('passed') is True for r in rows)
cal=calibration.get('heldout') or {}
complete_jobs=[x for x in cal.get('outcomes',[]) if x['covered'] is not None]
covered=sum(x['covered'] for x in complete_jobs)
null_ok=all(main['null'].values()) and bool(main['null'])
# This difference is across repeat executions of the same seed/mode, not a
# confidence interval and not independent environmental replication.
repeats=[]
for a in main['cases']:
    if a['condition']!='normal-service':continue
    b=next((x for x in repeated['cases'] if x['arm']==a['arm'] and x['seed']==a['seed']),None)
    if b is not None:
        repeats.append(dict(arm=a['arm'],seed=a['seed'],first=a['methane_kg'],second=b['methane_kg'],
                            absolute_difference=None if a['methane_kg'] is None or b['methane_kg'] is None else abs(a['methane_kg']-b['methane_kg']),
                            statuses=[a['status'],b['status']]))
spread=[r['absolute_difference'] for r in repeats if r['absolute_difference'] is not None]
payload=dict(main=main,window=window,repeats=repeats,calibration=calibration,
             window_trace=json.loads((ROOT/'window-trace.json').read_text()))
encoded=json.dumps(payload,allow_nan=False).replace('<','\\u003c')
source_links=' · '.join(f'<a href="{html.escape(p,quote=True)}">{label}</a>' for p,label in zip(paths,('Main case summaries','Deadline sensitivity','Computation repeat','Calibration result')))
# Authored interpretation is deliberately separate from generated numbers.
interpretation=(ROOT/'interpretation.html').read_text()
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recovery, uncertainty and the cost of waiting · Dispatch Lab</title>
<style>@font-face{font-family:Departure;src:url(../../assets/fonts/DepartureMono-Regular.woff2)}:root{color-scheme:dark;--ink:#ffad43;--muted:#c18c49;--line:#684e2d}*{box-sizing:border-box}body{margin:0;background:#202020;color:var(--ink);font:14px/1.75 Departure,monospace}main{max-width:1100px;margin:auto;padding:48px 28px 100px}h1{font-size:32px;line-height:1.3;max-width:24ch;font-weight:400}h2{font-size:21px;font-weight:400;margin:0 0 20px}h3{font-size:16px;font-weight:400}p{max-width:88ch}a{color:inherit;text-underline-offset:4px}nav{display:flex;flex-wrap:wrap;gap:8px 24px;border-block:1px solid var(--line);padding:14px 0;margin:32px 0}nav a{font-size:12px}section{border-bottom:1px solid var(--line);padding:36px 0}.meta,.muted{color:var(--muted);font-size:12px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:20px;margin:35px 0}.stats strong{font-size:27px;font-weight:400;display:block}.stats span{font-size:11px;color:var(--muted)}.scroll{overflow:auto;max-width:100%;border:1px solid var(--line);margin:22px 0}table{border-collapse:collapse;width:100%;font-size:12px;white-space:nowrap}td,th{padding:12px;text-align:left;border-bottom:1px solid #493c2a}th{font-weight:400;background:#29261f}tr:last-child td{border-bottom:0}select,button{font:inherit;color:inherit;background:#27241e;border:1px solid var(--line);border-radius:0;padding:9px 12px;margin:8px 8px 8px 0}button[aria-pressed=true]{background:var(--ink);color:#202020}label{display:block}button:focus-visible,select:focus-visible,a:focus-visible{outline:2px solid #ffd49a;outline-offset:4px}.note{border-left:2px solid var(--ink);padding:4px 18px;margin:25px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:30px}.scope{font-size:12px;color:var(--muted)}code{overflow-wrap:anywhere;font:inherit}li{margin:12px 0}.statustext{min-height:2em}.limit{color:#ffe0b2}@media(max-width:680px){main{padding:24px 16px 60px}h1{font-size:25px}.stats{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}body{font-size:12px}h2{font-size:18px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}</style>
<main><p class="meta">Dispatch Lab / research record / 13 September 2026</p><h1>Recovery, uncertainty and the cost of waiting</h1><p>A bounded recovery loop, equipment-specific duration beliefs, qualified retrieval planning and a faster preview path. The experiments below examine their limits as well as their outcomes.</p>'''
page+=f'<div class="stats"><div><strong>{len(valid)}/{len(rows)}</strong><span>main cases complete</span></div><div><strong>{audit_pass}</strong><span>independent case audits passed</span></div><div><strong>{final_tests:,}</strong><span>latest Python regression passed</span></div><div><strong>{bench["preview_p95_ms"]:.1f} ms</strong><span>preview p95 with active batch</span></div></div>'
page+='''<nav aria-label="Report sections"><a href="#findings">Findings</a><a href="#mechanics">Mechanisms</a><a href="#comparisons">Comparisons</a><a href="#window">Recovery window</a><a href="#calibration">Calibration</a><a href="#speed">Responsiveness</a><a href="#next">Next steps</a><a href="#evidence">Evidence</a></nav>'''
page+=interpretation
page+='''<section id="mechanics"><h2>What the implementation now does</h2><div class="grid"><article><h3>Repair → observed verification → escalation</h3><p>A whole-mission return opens a distinct, finite verification window. Power, charging and load tests are planned together. Repeated observed shortfalls can support the existing bounded repair retry. Ambiguous or resource-blocked tests cannot certify a repair or justify an unlimited retry chain.</p><p class="scope">Original deadlines and failed episodes remain recorded. A later independent incident gets its own deadline. Disabling sensors does not mean recovered capacity.</p></article><article><h3>Equipment effects and fresh job variation</h3><p>Each asset and clock group has a posterior over declared persistent factors. Each accepted job gets a separate bounded multiplier. Its phases share that job factor. Completed clocks and right-censoring update the belief; candidate searches and rejected work consume no random draws.</p><p class="scope">The fixture's hidden persistent factor is 1.25, with fresh uniform job multipliers between 0.8 and 1.2. These are controlled assumptions, not measured fleet statistics.</p></article><article><h3>Conditional return-to-charge planning</h3><p>An observed stranded robot may be scheduled to charge after a qualified nominated retrieval and the complete crew return. Crew, carrier, route, work, energy and prices remain required. Retrieval grants no repair or readiness credit.</p><p class="scope">Future hypothetical interruptions retain conservative restrictions. The bounded example does not establish a general contingent fleet policy.</p></article><article><h3>Coverage reconciles with consumables</h3><p>The broader tests caught a missing coupling: fresh job duration changed brush consumption, while optical treatment still used the persistent factor alone. Coverage now follows the actual perform duration. Independent and runtime checks reconcile treated area with cleaning consumption.</p><p class="scope">Discarded allowance during brush replacement is recorded separately. Completed and 30%-interrupted passes are tested independently; no tolerance was relaxed.</p></article></div></section>'''
page+='<p class="scope">Use the new loop in advanced experiment setup: shared visits and measured repair follow-up (service version 3), then bounded post-mission verification and escalation (recovery version 3). In Studies → uncertainty, choose Persistent equipment + job variation. These choices create new runs; archived decisions retain their original policies. <a href="../../docs/post-service-verification.md">Recovery setup</a> · <a href="../../docs/equipment-job-uncertainty.md">Duration model and calibration interface</a>.</p>'
page+='''<section id="comparisons"><h2>Inspect a matched condition</h2><p>Three service-uncertainty modes share plant parameters, economic objective, original prices, weather and event seeds. Null cases have two numerical repeats. Other main cases run for 48 hours with a 12-hour planning horizon. Process solves have a 0.25-second limit and service comparisons a two-second budget. The null process budget is two seconds.</p><p class="scope">This is a severe, controlled fixture: battery and hydrogen stores start empty. The persistent fault leaves 25% of 450 kW capacity (112.5 kW), below the 135 kW minimum operating load. The configured crew has zero response lead, 0.25-hour travel and 24-hour availability; robot batteries are 10 kWh, with three module kits initially available. These are shared illustrative assumptions chosen for service exposure, not measured site logistics or a typical fault distribution. Matching event seeds does not force identical realised repair outcomes: different accepted jobs or request times select different named draws. Finite solver budgets can also change those decisions.</p><label for="condition">Condition</label><select id="condition"></select><button id="stocks" type="button" aria-pressed="false">Show ending stocks</button><p id="case-status" class="scope statustext" aria-live="polite"></p><div id="case-table" class="scroll" tabindex="0" aria-label="Matched outcomes"></div><p class="scope">The stock view includes robot energy, brush allowance and modelled surface transmission; remaining support-resource ledgers are in the saved summary and Study write-up. No terminal sale proceeds are assumed. The nine European windows use the first 48 UTC hours of cached ten-day ECMWF/ERA5 envelopes starting 10 January, April and July 2026 in London, Seville and Copenhagen. Original forecast publication boundaries are retained. ERA5 is reanalysis, not site measurement. No missing input is silently replaced.</p>'''
page+=f'<p class="note">Null traces identical across all modes and numerical repeats for every event seed: <strong>{"yes" if null_ok else "not established; inspect the recorded spreads"}</strong>. Outside the null condition, finite-time solving can still change actions. Numerical repeats are not additional environmental seeds.</p>'
page+='<h3>Same-condition computation variation</h3><div id="repeat-table" class="scroll" tabindex="0" aria-label="Numerical repetitions"></div>'
if spread:page+=f'<p>Across the repeated normal-service seed/mode pairs, the largest absolute methane difference was {max(spread):.2f} kg; the median was {statistics.median(spread):.2f} kg. These are observed differences between two executions, not confidence bounds or a general error guarantee.</p>'
page+='</section><section id="window"><h2>Give verification another daylight opportunity</h2><p>A separate sensitivity changes the recovery wait from 12 to 24 hours. Original service deadlines, physical parameters, prices and event seeds remain fixed. The setting governs both initial recovery tests and post-mission windows; this is a sensitivity to that shared policy parameter, not an isolated estimate of post-repair time. It does not guarantee that a procedure succeeds or that the observer will regain full-capacity confidence.</p><div id="window-table" class="scroll" tabindex="0" aria-label="Recovery deadline sensitivity"></div><p class="scope">Physical restoration is retrospective simulator truth. Confirmation is an observed controller milestone. Confirmation here means an estimate at least 99.9% of nameplate capacity; useful degraded production can precede it. A scheduled test is only a prediction; missing confirmation is not replaced with a repair receipt. This sensitivity contains no additional null cases.</p></section>'
page+=f'<section id="calibration"><h2>Calibrate predictions against observations</h2><p>Calibration status: <strong>{html.escape(calibration["status"])}</strong>. Three separate 240-hour Greedy observation runs exercise the workflow. Training uses packets available by H120; evaluation uses later new jobs, excluding continuations of training jobs. Candidate widths are predeclared, and held-out observations do not select the model.</p>'
page+=f'<p>The selected model has {cal.get("jobs",0)} held-out job/group outcomes. Its 90% predictive intervals covered {covered} of {len(complete_jobs)} completed outcomes; {len(cal.get("unsupported",[]))} held-out jobs were outside the predictive support.</p>'
if calibration.get('error'):page+='<p class="limit">'+html.escape(calibration['error'])+'</p>'
page+='''<div id="calibration-table" class="scroll" tabindex="0" aria-label="Held-out duration predictions"></div><p class="note">These are simulated observations. They verify fitting, causal holdout and prediction accounting. They do not establish empirical field calibration. Ten equipment/group histories remain sparse; four held-out outcomes are censored.</p><p class="scope">The finite persistent grid and uniform job distribution are model choices. Equipment-group fixture factors are held fixed within runs. Risk planning uses a small shared-quantile scenario approximation, not a fully calibrated joint distribution over independent future jobs.</p><p>The original checker rejected one calibration run after independent decimal replay put brush stock 0.000000000012539 m² below zero. That was the only failed check among 92,795. The revised checker expresses boundary violations in resource units and applies its existing numerical tolerance, with tests that reject material deficits and excesses. It does not clamp or change the physical trace. All three original records pass the new audit.</p><p class="scope">The <a href="validation/calibration-original-audit.json">original failed audit</a> and <a href="c03f2ebfebde491ea7ce927701f35bf2/calibration/0a7498de3c314eaab5c8d1e6a7b34990/result.json">two-run fit</a> are preserved. This is a new calibration edition using the same predeclared candidate models and time cutoff. The calibration result identifies its physical source, checker, audit artifacts and fitting source separately. <a href="../../docs/reference-stock-bounds.md">Checker correction and scope</a>.</p></section>'''
page+='''<section id="speed"><h2>Responsiveness, including the cold tail</h2><p>The preview path now passes the large immutable playback props as JSON scalars and decodes each update once. This avoids Gradio/Svelte repeatedly deep-snapshotting the complete run during loading-state changes. Numerical APIs and saved archives retain their structured values.</p><div class="scroll"><table><thead><tr><th>Fixture / 30 samples</th><th>Preview p95</th><th>Render p95</th><th>First sample</th></tr></thead><tbody><tr><td>72 hours, no batch</td><td>126.0 ms</td><td>1.1 ms</td><td>170.7 ms</td></tr><tr><td>240 hours, active batch</td><td>112.8 ms</td><td>2.7 ms</td><td>1,566.3 ms</td></tr></tbody></table></div><p class="limit">The p95 gates pass. First interaction remains over budget in cold measurements: 427.7 ms in a separate cold trace, and 1,566.3 ms for the first active-batch sample. This is not a claim that every interaction is below 200 ms.</p><p class="scope">Local macOS/Chromium fixtures. Raw samples, the separately observed cold tail and implementation notes are retained. Separately, assembling the 153-case report took 481.4 seconds after the simulations, including original archive and calculation verification. That offline cost is outside the preview benchmark and remains an optimisation opportunity. Plant and solar screenshot baselines passed unchanged.</p></section>'''
page+='<section id="evidence"><h2>Evidence and reproduction</h2>'
page+=f'<p>Numerical source: <code>{html.escape(source)}</code>. Full regression: 1,005 Python tests. Browser suite: 87 passes and 18 fixture-dependent skips. Renderer suite: 73 passes. Read the original artifacts for their source and fixture scope; passing checks are not empirical plant validation.</p><p>{source_links}</p>'
page+=f'<p>The subsequent reporting and independent-checker corrections pass {final_tests:,} Python tests on source <code>{final_source}</code>. They do not change the physical calculations above. The calibration re-audit and fitting use this newer source against the original sealed records. <a href="validation/pytest-final.xml">Final regression</a> · <a href="validation/source-under-test-final.json">Final source binding</a> · <a href="validation/documentation-evidence-final.json">Topic verification</a>.</p>'
page+='''<p><a href="README.md">Commands and protocol scope</a> · <a href="programme-index.json">All programme editions, including unexecuted ones</a> · <a href="validation/pytest.xml">Python outcomes</a> · <a href="validation/browser.txt">Browser outcomes</a> · <a href="validation/renderer.txt">Renderer outcomes</a> · <a href="validation/paired-manifests.json">Matched input checks</a> · <a href="validation/report-assembly-timing.json">Report assembly timing</a> · <a href="validation/report-metrics.txt">Episode-count checks</a> · <a href="retrieval-db5c9bc9cfbb4e42abdba274ae116663-summary.json">Bounded retrieval example</a> · <a href="preview-240h-batch.json">Active-batch timing samples</a> · <a href="preview-cold-and-warm.json">Cold and warm trace</a></p><p>New plant parameters create new editions. Completed runs retain frozen source, raw weather, policy assumptions, observations, actions, accounting and independent audit identities. The failed pre-correction programme remains available; it was not relabelled. Large numerical artifacts and source capsules remain locally archived under the existing preservation policy.</p></section></main>'''
page+='<script type="application/json" id="data">'+encoded+'</script>'
page+='''<script>
const data=JSON.parse(document.getElementById('data').textContent),selection=document.getElementById('condition');
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>x==null?'—':Number(x).toFixed(2),at=x=>x==null?'Unconfirmed':'H'+x;
function table(headers,rows){return '<table><thead><tr>'+headers.map(x=>'<th scope="col">'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
for(const name of [...new Set(data.main.cases.map(x=>x.condition))]){const o=document.createElement('option');o.value=name;o.textContent=name;selection.append(o)}
selection.value='persistent-damage';let stocks=false;
function render(){const rows=data.main.cases.filter(r=>r.condition===selection.value);document.getElementById('case-status').textContent=rows.length+' recorded cases; '+rows.filter(r=>r.status==='complete').length+' complete. All unfinished cases remain listed.';
let headers=['Mode','Seed / repeat','Status','CH₄ kg','Allocated €','Contribution €','Cleaning h','Crew visits','Restored (truth)','Confirmed (observed)','Limited process solves','Service fallback intervals'];
let values=rows.map(r=>[r.arm,r.seed+' / '+r.repeat,r.status,num(r.methane_kg),num(r.metrics.total_eur),num(r.metrics.assumed_contribution_eur),num(r.field_quantities?.cleaner_hours),r.field_quantities?.human_visits??'—',r.metrics.capacity_restored_hour==null?'Not recorded':'H'+r.metrics.capacity_restored_hour,at(r.metrics.capacity_confirmed_hour),r.metrics.limited_solves,r.service_fallback_intervals]);
const resource=(r,key)=>r.ending_service_resources?.find(x=>x.resource===key)?.ending;
if(stocks){headers=['Mode','Seed / repeat','Status','Battery kWh','H₂ kg','CO₂ kg','Reactor °C','Module kits','Cleaning kits','Cleaner kWh','Rover kWh','Brush allowance m²','Modelled surface transmission %'];values=rows.map(r=>[r.arm,r.seed+' / '+r.repeat,r.status,num(r.ending?.battery_kwh),num(r.ending?.h2_kg),num(r.ending?.co2_kg),num(r.ending?.temperature_c),r.service_inventories?.['ending:module'],r.service_inventories?.['ending:cleaning'],num(resource(r,'energy:cleaner')),num(resource(r,'energy:rover')),num(resource(r,'brush:cleaner')),num(r.ending_modelled_transmission==null?null:100*r.ending_modelled_transmission)])}
headers.push('Evidence');values.forEach(r=>r.push(''));
const host=document.getElementById('case-table');host.innerHTML=table(headers,values);
rows.forEach((r,i)=>{if(r.study_report){const link=document.createElement('a');link.href=r.study_report;link.textContent='Study write-up';host.querySelectorAll('tbody tr')[i].lastElementChild.append(link)}})}
selection.addEventListener('change',render);document.getElementById('stocks').addEventListener('click',e=>{stocks=!stocks;e.currentTarget.setAttribute('aria-pressed',String(stocks));e.currentTarget.textContent=stocks?'Show operating outcomes':'Show ending stocks';render()});render();
document.getElementById('repeat-table').innerHTML=table(['Mode','Seed','First CH₄ kg','Repeat CH₄ kg','Absolute difference kg','Statuses'],data.repeats.map(r=>[r.arm,r.seed,num(r.first),num(r.second),num(r.absolute_difference),r.statuses.join(' / ')]));
document.getElementById('window-table').innerHTML=table(['Mode','Seed','12 h CH₄ kg','24 h CH₄ kg','12 h confirmation','24 h confirmation','24 h ending status'],data.window.cases.map(b=>{const a=data.main.cases.find(x=>x.condition==='persistent-damage'&&x.arm===b.arm&&x.seed===b.seed);return [b.arm,b.seed,num(a?.methane_kg),num(b.methane_kg),at(a?.metrics.capacity_confirmed_hour),at(b.metrics.capacity_confirmed_hour),b.verification_ending?.status??b.status]}));
document.getElementById('calibration-table').innerHTML=table(['Clock group','Observed factor','90% predictive interval','Covered','Censored lower bound'],(data.calibration.heldout?.outcomes||[]).map(x=>[x.group,num(x.factor),x.predictive_interval_90.map(num).join(' → '),x.covered==null?'Censored':x.covered?'Yes':'No',num(x.censored_after_factor)]));
</script></html>'''
page=page.replace('<div id="window-table"', (ROOT/'timeline.html').read_text()+'<div id="window-table"',1)
page=page.replace('</script></html>','</script><script src="timeline.js"></script></html>')
page=page.replace('</style>', '#calibration-table{max-height:380px}#calibration-table th{position:sticky;top:0}</style>',1)
(ROOT/'report.html').write_text(page)
print(ROOT/'report.html')
