"""Author-maintained research records; these are not executable plant configurations."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
entries = [
    (
        "ecoppia",
        "Robotic solar panel cleaning services",
        "Ecoppia",
        "Undated; current page",
        "https://www.ecoppia.com/",
        "Manufacturer deployment claims",
        "Public product/company page",
        "Reports more than 5 GW of deployments; no independent fleet availability or cost audit.",
    ),
    (
        "t4",
        "T4 autonomous robotic cleaning solution",
        "Ecoppia",
        "Undated datasheet",
        "https://www.ecoppia.com/warehouse/temp/ecoppia/T4_Datasheet.pdf",
        "Manufacturer technical specification",
        "PDF text",
        "Tracker-specific geometry, coverage and stow requirements; not transferable to fixed-tilt rows.",
    ),
    (
        "solarcleano",
        "SolarCleano F1",
        "SolarCleano",
        "Undated; current page",
        "https://www.solarcleano.com/products/remote-solarcleano-f1",
        "Manufacturer technical specification",
        "Public product page",
        "Portable wet/dry cleaner requiring an operator; distinguishes remote control from unattended operation.",
    ),
    (
        "anymal",
        "ANYmal X — Ex-proof inspection robot",
        "ANYbotics",
        "Undated; current page refers to 2026 specifications",
        "https://www.anybotics.com/robotics/anymal-x/",
        "Manufacturer technical specification",
        "Public product page",
        "Inspection payloads and advertised Zone 1 IIB rating; not evidence of hydrogen-area suitability for a particular configuration.",
    ),
    (
        "exr",
        "ExR-2.5 products, software and services",
        "ExRobotics",
        "Undated; current page",
        "https://www.exrobotics.com/our-products",
        "Manufacturer technical and service claims",
        "Public product page",
        "Modular inspection, autonomous charging, optional payloads, mission durations and service models; advertised unattended intervals are design claims.",
    ),
    (
        "spot",
        "Automated inspections made simple",
        "Boston Dynamics",
        "Undated; current page",
        "https://bostondynamics.com/blog/automated-inspections-made-simple/",
        "Manufacturer workflow description",
        "Public article",
        "Teach-in, repeatable missions, payloads and integration with maintenance systems.",
    ),
    (
        "autoinspect",
        "AutoInspect: Towards Long-Term Autonomous Industrial Inspection",
        "M. Staniaszek et al.",
        "22 April 2024, arXiv v2",
        "https://arxiv.org/html/2404.12785v2",
        "Research deployment report",
        "Full author manuscript",
        "49-day and 35-day deployments; mission-level architecture and recorded interventions. Not zero-touch operation for those entire periods.",
    ),
    (
        "gecko",
        "Reinforcement Learning for RUG",
        "L. Roberto / Gecko Robotics",
        "2 June 2025",
        "https://www.geckorobotics.com/resources/blog/reinforcement-learning-for-rug",
        "Manufacturer technical article",
        "Public article",
        "Contact ultrasonic inspection and thickness inference; does not establish unattended deployment or automatic repair.",
    ),
    (
        "renu",
        "Renu Robotics: autonomous vegetation management",
        "Renu Robotics",
        "Undated; current page",
        "https://renurobotics.com/about-us/",
        "Manufacturer deployment and operating claims",
        "Public company page",
        "Electric mower, recharge pod and remote Mission Control; not independent savings evidence.",
    ),
    (
        "sampling",
        "Calibration and switching modules",
        "Swagelok",
        "Undated; current page",
        "https://products.swagelok.com/en/all-products/analytical-instrumentation/analytical-subsystems-press/calibrating-switching-modules/c/502?clp=true",
        "Manufacturer technical specification",
        "Public product page",
        "Sample conditioning and selection of process/calibration streams; the module is not itself a complete analyzer.",
    ),
    (
        "cdc90",
        "Cleaning and calibration system Liquiline Control CDC90",
        "Endress+Hauser",
        "Undated; current product page",
        "https://www.endress.com/en/field-instruments-overview/liquid-analysis-product-overview/pH-sensor-automatic-cleaning-calibration-cdc90",
        "Manufacturer technical specification",
        "Public product page",
        "Automatic pH/ORP cleaning and calibration; not a hydrogen-flow-meter calibration method.",
    ),
    (
        "emerson",
        "Corrosion and erosion monitoring",
        "Emerson",
        "Undated; current page",
        "https://www.emerson.com/en/measurement-instrumentation/catalog/corrosion-and-erosion-monitoring",
        "Manufacturer technical description",
        "Public product catalogue",
        "Permanently installed ultrasonic, acoustic and intrusive monitoring options; no plant-specific calibration.",
    ),
    (
        "rotork",
        "IQ3 Pro intelligent electric actuators",
        "Rotork",
        "Undated; current page",
        "https://www.rotork.com/en/products/electric-intelligent-actuators/iq3-pro",
        "Manufacturer technical specification",
        "Public product page",
        "Remote actuation and diagnostic torque/position data; retained indication on power loss is distinct from actuation power.",
    ),
    (
        "shutdown",
        "Power generation: actuator solutions",
        "Rotork",
        "Undated application document",
        "https://www.rotork.com/uploads/news/2950/rotork-v3pdf.pdf",
        "Manufacturer application note",
        "PDF text",
        "Dedicated shutdown battery or mechanical spring designs for specified failsafe applications.",
    ),
    (
        "dock",
        "DJI Dock 3 specifications",
        "DJI",
        "Undated; current product specification",
        "https://enterprise.dji.com/dock-3/specs",
        "Manufacturer technical specification",
        "Public specification text",
        "Dock power, aircraft battery, conditional charge time, landing wind and backup-power exclusions. Maximum ratings are not average consumption.",
    ),
    (
        "taurob",
        "Taurob Operator",
        "Taurob",
        "Undated; current page",
        "https://www.taurob.com/operator/",
        "Manufacturer prototype description",
        "Public product page explicitly labelled PROTOTYPE",
        "Valve manipulation and tool handling; broad capability language does not establish routine unattended maintenance availability.",
    ),
    (
        "robotfactors",
        "A Robot Factors Approach to Designing Modular Hardware",
        "N. Melenbrink, C. Teeple and J. Werfel",
        "2022, IROS author manuscript",
        "https://www.eecs.harvard.edu/~jkwerfel/iros22melenbrink.pdf",
        "Robotics research with physical demonstrations",
        "Full author PDF",
        "Robot-friendly power and water-filter modules; laboratory space-habitat examples, not certified industrial gas service.",
    ),
    (
        "maximo",
        "Maximo Completes 100 MW of Robotic Solar Installation",
        "Maximo / AES",
        "25 March 2026",
        "https://www.nasdaq.com/press-release/maximo-completes-100-mw-robotic-solar-installation-2026-03-25",
        "Company press release distributed by PRNewswire, hosted by Nasdaq",
        "Full press release",
        "Company-reported 100 MW installation at Bellefield; construction crews remain part of the system.",
    ),
    (
        "terabase",
        "Next-generation Terafab completes field testing, ready for deployment",
        "Terabase Energy",
        "19 March 2026",
        "https://www.terabase.energy/resources/terabase-energys-next-generation-terafab-completes-field-testing-ready-for-deployment",
        "Company announcement",
        "Public announcement",
        "First generation on five projects; V2 field testing complete and ready for shipment as of announcement, not evidence of every planned deployment.",
    ),
    (
        "maverick",
        "5B Maverick",
        "5B",
        "Undated; current product page",
        "https://5b.co/en/5b-maverick",
        "Manufacturer design and deployment claims",
        "Public product page",
        "Prefabricated, pre-wired folding PV blocks deployed with a crew and telehandler; not an autonomous robot.",
    ),
    (
        "pvps",
        "Understanding, Measuring, and Mitigating Soiling Losses in PV Power Systems",
        "IEA PVPS Tasks 13 and 16",
        "September 2025",
        "https://iea-pvps.org/wp-content/uploads/2025/09/Fact-Sheet-Task-1316-Soiling.pdf",
        "Research-programme technical synthesis",
        "PDF text",
        "Site-specific soiling, clipping, curtailment and storage interactions; global figures are not European-site defaults.",
    ),
    (
        "abrasion",
        "Abrasion of PV Antireflective Coatings by Robot Cleaning",
        "B. W. Figgis et al.",
        "21 June 2024; IEEE Journal of Photovoltaics 14(5), 824–829",
        "https://doi.org/10.1109/JPHOTOV.2024.3414192",
        "Peer-reviewed physical field experiment",
        "Indexed publisher abstract and introduction; full paper not reviewed",
        "18-month Doha test shows module-dependent abrasion effects. No universal wear coefficient follows.",
    ),
    (
        "pomdp",
        "Deep reinforcement learning driven inspection and maintenance planning under incomplete information and constraints",
        "C. P. Andriotis and K. G. Papakonstantinou",
        "2 July 2020, author preprint",
        "https://arxiv.org/abs/2007.01380",
        "Research method",
        "Author abstract",
        "Constrained POMDP and DRL formulation for inspection/maintenance; no validation for this plant.",
    ),
    (
        "dbn",
        "Optimal Inspection and Maintenance Planning for Deteriorating Structural Components through Dynamic Bayesian Networks and Markov Decision Processes",
        "P. G. Morato et al.",
        "28 November 2021, arXiv v2",
        "https://arxiv.org/abs/2009.04547",
        "Research method and numerical experiments",
        "Author abstract",
        "Belief-state inspection and maintenance for structural deterioration; transfer to plant scheduling is a proposal.",
    ),
    (
        "cleanrl",
        "Reinforcement learning-based dynamic cleaning scheduling framework for solar energy system",
        "H. An",
        "2025 journal article; author manuscript posted 8 March 2026",
        "https://arxiv.org/abs/2603.07518",
        "Published simulation study, according to author record",
        "Author abstract and publication metadata",
        "PPO/SAC cleaning scheduling in an Abu Dhabi case; not European field validation or whole-plant optimization.",
    ),
    (
        "rmf",
        "Open-RMF demonstrations: task dispatching",
        "Open-RMF contributors",
        "Living repository; accessed 10 September 2026",
        "https://github.com/open-rmf/rmf_demos/blob/main/README.md",
        "Official open-source implementation documentation",
        "Repository README",
        "Fleet task allocation and integrated charging; an architectural reference, not a mandated dependency.",
    ),
    (
        "gemini",
        "Gemini Robotics On-Device 2 model card",
        "Google DeepMind",
        "30 July 2026",
        "https://deepmind.google/models/model-cards/gemini-robotics-on-device-2/",
        "Developer model card",
        "Public model card",
        "Trusted-tester distribution, manipulation benchmarks and explicit generalization/mobile-platform limitations; not industrial field qualification.",
    ),
    (
        "flir",
        "Understanding Cooled vs Uncooled Optical Gas Imaging",
        "FLIR",
        "Undated; current article",
        "https://www.flir.com/en-gb/discover/instruments/gas-detection/understanding-cooled-vs-uncooled-optical-gas-imaging/",
        "Instrument manufacturer technical explanation",
        "Public article",
        "Spectrally selective OGI; hydrogen cannot be directly imaged by the described conventional OGI method. The article incorrectly groups these gases as noble; that wording is not adopted.",
    ),
    (
        "hydrogen",
        "Working Safely with Hydrogen",
        "MSA Safety, hosted by H2tools",
        "Document available March 2025; publication date not independently established",
        "https://h2tools.org/sites/default/files/2025-03/0700-006-EU_MSA-White-Paper_Working-Safely-with%20Hydrogen_EN.pdf",
        "Manufacturer technical white paper",
        "Indexed PDF text",
        "Hydrogen gas-group IIC distinction; not a site classification or certificate assessment.",
    ),
    (
        "easa",
        "Specific Category — Civil Drones",
        "European Union Aviation Safety Agency",
        "Living guidance; accessed 10 September 2026",
        "https://www.easa.europa.eu/en/domains/drones-air-mobility/operating-drone/specific-category-civil-drones",
        "Aviation authority guidance",
        "Public guidance",
        "BVLOS and applicable authorization/declaration routes in EASA states; not a permission for a particular mission.",
    ),
    (
        "caa",
        "GM1 Article 3: Categories of UAS Operations",
        "UK Civil Aviation Authority",
        "Living regulatory library; accessed 10 September 2026",
        "https://regulatorylibrary.caa.co.uk/2019-947/Content/AMC-GM/GM1%20Article%203%20Categories%20of.htm",
        "Aviation authority guidance",
        "Public regulatory text",
        "UK BVLOS lies outside Open category; separate UK scope from EASA rules.",
    ),
]
sources = [
    dict(
        zip(("id", "title", "authors", "date", "url", "type", "access", "scope"), e, strict=True),
        accessed="2026-09-10",
    )
    for e in entries
]
(ROOT / "sources.json").write_text(json.dumps(sources, indent=2, ensure_ascii=False) + "\n")
items = [
    (
        "row-cleaner",
        "Dedicated solar-row cleaner",
        "Commercial, geometry-specific",
        "Ecoppia E4/H4/T4",
        "Dry brushing with docking; some systems use their own solar supply.",
        "Soiling removal per section, finite coverage, brush condition, docking and weather limits.",
        "Track/bridge layout; no automatic cross-row compatibility; consumables and servicing remain.",
        ["ecoppia", "t4"],
        "First implementation",
    ),
    (
        "portable-cleaner",
        "Portable wet/dry cleaner",
        "Commercial, operator-assisted",
        "SolarCleano F1",
        "Battery-powered cleaner transported and operated by a person.",
        "Water, setup/movement labour, energy, coverage and cleaning effectiveness.",
        "Remote control does not eliminate the operator or deployment visit.",
        ["solarcleano"],
        "Comparison baseline",
    ),
    (
        "ground-inspector",
        "Mobile ground inspector",
        "Commercial, commissioned routes",
        "ANYmal X; ExR-2.5; Spot",
        "Visual, thermal, acoustic and optional gas sensing on taught inspection rounds.",
        "Travel graph, payload, observation quality, delay, charge, failed missions and assistance.",
        "Mobility, gas-group rating and payload compatibility differ; a reading is not a repair.",
        ["anymal", "exr", "spot"],
        "First implementation",
    ),
    (
        "aerial-inspector",
        "Docked aerial inspector",
        "Commercial, operation-dependent",
        "DJI Dock 3 / Matrice 4TD",
        "Repeatable visual/thermal survey with automatic dock charging.",
        "Survey coverage, wind/rain restrictions, flight reserve, dock power and delayed observations.",
        "Weather, airspace/authorization and dock dependence; no generic gas identification.",
        ["dock", "easa", "caa"],
        "Second implementation",
    ),
    (
        "contact-inspector",
        "Contact inspection crawler",
        "Commercial specialist inspection",
        "Gecko Robotics RUG",
        "Ultrasonic measurement of surface/material thickness.",
        "Inspection method, reachable surfaces and measurement uncertainty.",
        "Deployment and contact preparation may require people; requires a corresponding degradation model.",
        ["gecko"],
        "Later, if integrity mechanics added",
    ),
    (
        "grounds",
        "Vegetation-management robot",
        "Commercial deployments reported",
        "Renu Robotics Renubot",
        "Mapped autonomous mowing with recharge pod and remote monitoring.",
        "Seasonal growth, access obstruction, service hours, energy and human support.",
        "Terrain, obstacles and robot maintenance; economics differ with site and climate.",
        ["renu"],
        "Later site-operations example",
    ),
    (
        "sampler",
        "Sampling and analyzer station",
        "Commercial engineered subsystem",
        "Swagelok calibration/switching modules",
        "Condition and route process or reference samples to an analyzer.",
        "Purge/transport delay, sample use, contamination, analyzer status and reference inventory.",
        "Requires an analyzer, utilities and compatible process interfaces; not gas-quality certification.",
        ["sampling"],
        "Initial architecture; later mechanism",
    ),
    (
        "calibration",
        "Automatic sensor service station",
        "Commercial for specified sensors",
        "Endress+Hauser CDC90",
        "Retract, clean, validate and calibrate compatible pH/ORP sensors.",
        "Calibration age, reference/cleaner stocks, temporary unavailability and verified return.",
        "Not a generic cure for a hydrogen flow meter; electrode and reagent replacement remain.",
        ["cdc90"],
        "First fixed-hardware comparison",
    ),
    (
        "fixed-sensor",
        "Rugged fixed sensor package",
        "Commercial, technology-specific",
        "Emerson corrosion/erosion sensing",
        "Permanent ultrasonic, acoustic or intrusive measurements.",
        "Independent channels, battery life, drift, dropout and common-mode error.",
        "Sensor coverage and calibration are bounded; no automatic remaining-life ground truth.",
        ["emerson"],
        "First inspection baseline",
    ),
    (
        "remote-actuator",
        "Remote actuator / redundant service path",
        "Commercial with engineered integration",
        "Rotork IQ3 Pro and shutdown options",
        "Commanded actuation with position/torque feedback; optional stored-energy shutdown.",
        "Actuation power, stuck states, position uncertainty and service-path prerequisites.",
        "Indication backup is not actuator motive power; valve action must have a modeled physical effect.",
        ["rotork", "shutdown"],
        "First bounded-recovery example",
    ),
    (
        "manipulator",
        "Mobile maintenance manipulator",
        "Prototype / constrained demonstrations",
        "Taurob Operator",
        "Valve manipulation, tooling and material handling.",
        "Tool/reach/torque compatibility, multi-stage tasks, failure, verification and remote assistance.",
        "Manufacturer page explicitly says prototype; no universal consumable-replacement capability.",
        ["taurob"],
        "Explicit future-capability fixture",
    ),
    (
        "service-module",
        "Robot-compatible replaceable module",
        "Research demonstration / design option",
        "Melenbrink–Teeple–Werfel modular hardware",
        "Single-axis guided insertion, combined latching and compliant mechanical interfaces.",
        "Service-port compatibility, spare stock, isolation, swap and post-service check.",
        "Space-habitat lab hardware is evidence for a design principle, not pressure-system qualification.",
        ["robotfactors"],
        "Explicit future-capability fixture",
    ),
    (
        "construction",
        "Solar construction robot",
        "Commercial deployments reported; evolving versions",
        "AES/Maximo; Terabase Terafab",
        "Mechanized panel handling, assembly and installation alongside construction crews.",
        "Build-phase labour, rented equipment, mobilization, capacity commissioning and defects.",
        "Not a daily O&M robot; module installation is only part of project completion.",
        ["maximo", "terabase"],
        "Separate commissioning scenario",
    ),
    (
        "deployable-array",
        "Pre-integrated deployable solar array",
        "Commercial, crew-assisted",
        "5B Maverick",
        "Transportable pre-wired solar blocks unfolded with a small crew and machinery.",
        "Transport, installation time/cost, footprint and compatible cleaning/access geometry.",
        "A design alternative rather than an autonomous robot; crew and telehandler still required.",
        ["maverick"],
        "Separate design comparison",
    ),
]
archetypes = [
    dict(
        zip(
            (
                "id",
                "name",
                "maturity",
                "examples",
                "mechanism",
                "simulation",
                "limits",
                "sources",
                "priority",
            ),
            i,
            strict=True,
        )
    )
    for i in items
]
(ROOT / "catalogue.json").write_text(
    json.dumps(
        {
            "schema_version": "dispatch-lab/research-field-robotics/1",
            "as_of": "2026-09-10",
            "status": "Research proposals, not implemented asset definitions",
            "archetypes": archetypes,
        },
        indent=2,
        ensure_ascii=False,
    )
    + "\n"
)
print(f"{len(sources)} sources; {len(archetypes)} hardware archetypes")
