const {chromium}=require('@playwright/test');
const fs=require('fs');
const path=require('path');
const assert=require('assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},offline:true});
 const page=await context.newPage();
 const requests=[]; const errors=[];
 page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
 page.on('pageerror',e=>errors.push(e.message));
 const dir=__dirname+'/';
 await page.goto('file://'+dir+'report.html');
 await page.screenshot({path:dir+'preview-desktop.png'});
 const result={title:await page.title(),headingCount:await page.locator('h2').count(),catalogueRows:await page.locator('#hardware tbody tr').count(),desktopOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)};
 await page.locator('#hardware-search').fill('prototype');
 result.filteredRows=await page.locator('#hardware tbody tr:visible').count();
 await page.getByRole('button',{name:'Show all'}).click();
 result.resetRows=await page.locator('#hardware tbody tr:visible').count();
 await page.locator('figure.architecture').scrollIntoViewIfNeeded();
 await page.screenshot({path:dir+'preview-architecture.png'});
 result.missingAnchors=await page.evaluate(()=>[...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.getElementById(a.getAttribute('href').slice(1))).map(a=>a.getAttribute('href')));
 const links=await page.locator('a[href]').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('href')));
 result.missingLocalFiles=links.filter(h=>!h.startsWith('#')&&!/^[a-z]+:/i.test(h)).filter(h=>!fs.existsSync(path.resolve(dir,h.split('#')[0])));
 await page.setViewportSize({width:390,height:844});
 await page.emulateMedia({reducedMotion:'reduce'});
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:dir+'preview-mobile.png'});
 result.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 result.horizontalTables=await page.locator('.table-scroll').count();
 result.externalRequests=requests; result.pageErrors=errors;
 assert.equal(result.catalogueRows,14); assert.equal(result.resetRows,14);
 assert(result.filteredRows>0&&result.filteredRows<14);
 assert(!result.desktopOverflow&&!result.mobileOverflow);
 assert.deepEqual(result.missingAnchors,[]);assert.deepEqual(result.missingLocalFiles,[]);
 assert.deepEqual(requests,[]);assert.deepEqual(errors,[]);
 fs.writeFileSync(dir+'browser-verification.json',JSON.stringify(result,null,2)+'\n');
 console.log(JSON.stringify(result));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
