"""Proposed connector catalogue. Documentation review is not adapter qualification."""
import json
from pathlib import Path

# family, source IDs, coverage, inputs, access, boundary, priority
ROWS = [
 ('Solar resource', ['pvgis-api','pvgis-manual'], 'Europe / SARAH3 2005–2023, approximately 5 km; hourly and aggregate products', 'Radiation, horizon, reference PV; design tilt and orientation', 'Public versioned GET API; raw JSON cache. Three PVcalc requests tested. Server-side integration.', 'Provider PV is a cross-check, not plant DC plus another loss stage. Exact hourly timestamp adapter still requires qualification.', 'A'),
 ('Historical weather', ['era5','era5-land'], 'Global / ERA5 since 1940, ERA5-Land since 1950; hourly gridded reanalysis', 'Temperature, humidity/dewpoint, radiation, wind, precipitation and snow where supported', 'Copernicus CDS authenticated downloads; accept the selected dataset terms. Cache original files and metadata.', 'Grid estimates are not on-site measurements; resolution, accumulations and provider revisions matter.', 'B'),
 ('Operational weather', ['weather-runs','weather-history','weather-terms'], 'European coordinates; ECMWF original forecast runs from March 2024', 'Original forecasts, issue/availability times, explicit ERA5 replay reference', 'Reuse Open-Meteo adapter; commercial advanced APIs require appropriate plan. Free prototype access is non-commercial.', 'Shorter archive than climate history. No automatic stitched forecast or synthetic substitution.', 'A/B'),
 ('Solar cross-check', ['cams'], 'Historical record since 2004; European satellite coverage', 'Global, direct, diffuse and direct-normal radiation', 'Copernicus Atmosphere Data Store product access; qualify interval and licence metadata.', 'Shares atmospheric/satellite information with other products; disagreement is not independent validation.', 'B'),
 ('Land cover', ['clc'], 'European CLCplus Backbone 2023; 10 m raster', 'Cover classes, confidence/quality layers where supplied, usable-area masks', 'CLMS/WEkEO downloads and services; preserve CLMS attribution and edition.', 'Does not establish ownership, lease availability or permission to build.', 'A'),
 ('Terrain', ['dem'], 'Copernicus GLO-30; 30 m global surface model', 'Elevation, slope distribution and broad horizon', 'Copernicus Data Space / regional extracts; record product licence and attribution.', 'Vegetation and structures affect elevations; parcel levelling and near-object shadows need better evidence.', 'A'),
 ('Protected areas', ['natura','natura-service','england'], 'EU Natura 2000 plus separate national jurisdiction layers', 'Intersections, nearby designations, configurable avoidance distances', 'EEA spatial services/downloads; national open-data products under their own terms.', 'Selected screening policy is not a legal verdict. UK coverage is not supplied by an England-only layer.', 'A'),
 ('Parcel and planning', ['parcels'], 'Country/region-specific cadastral and planning data', 'Geometry, parcel IDs, zoning; uploaded lease and survey evidence', 'INSPIRE-compatible national services where available; rights/access evidence is obtained separately.', 'No uniform European database of available industrial land, asking price and development permission.', 'A/C'),
 ('Flood exposure', ['flood'], 'Europe and Mediterranean river basins >150 km²; return periods 10–500 years', 'Modelled flood-depth intersections and exposure flags', 'JRC/CEMS open downloads; CC BY 4.0. Higher-detail national layers as candidate-specific additions.', 'Not an official flood map; no automatic site failure probability or complete coastal/pluvial coverage.', 'A'),
 ('Water stress', ['wei','aqueduct'], 'European seasonal sub-units 2000–2023; global Aqueduct baseline/future indicators', 'Seasonality and regional water-pressure context', 'EEA downloadable data; WRI public datasets with attribution/registration terms.', 'Not a supply entitlement, delivered volume, treatment specification or usable rainfall model.', 'A'),
 ('Industrial supply and demand', ['industrial'], 'Reported European industrial facilities; coverage depends on reporting regime', 'Locations, sector, reported emissions and potential co-location leads', 'EEA industrial reporting downloads; record reporting year, thresholds and country coverage.', 'Reported CO₂ emissions are not captured, pure, biogenic or available CO₂. An actual offer is a separate input.', 'A/C'),
 ('Electrical connection', ['ukpn'], 'First proposed national adapter: UKPN EHV headroom and plans', 'Network context, indicative headroom, scenario year; uploaded operator quotation', 'Operator data portals and dated documents; licence/automation review per dataset.', 'No guarantee of import/export capacity, firm access, cost, reinforcement or commissioning date.', 'C'),
 ('Electricity market', ['entsoe','entsoe-api','elexon','esios'], 'Bidding zones and national products; native hourly/sub-hourly intervals', 'Historical prices, price publication times, market/context series', 'ENTSO-E/e·sios authentication; Elexon public documented APIs; reuse rights checked per product.', 'Market or imbalance prices are not the delivered site tariff. No implied grid interface in current physics.', 'C'),
 ('Gas export', ['entsog'], 'European transmission maps and operator-specific connection evidence', 'Network leads, offered injection capacity and product acceptance requirements', 'ENTSOG reference links only until use rights are resolved; operator offers imported explicitly.', 'Map is indicative and has restrictive commercial-use wording. Nearby infrastructure is not an injection right.', 'C'),
 ('Capital and operation', ['costs'], 'Technology/scale-specific catalogue editions, including August 2026', 'Equipment benchmark ranges and referenced lifetime/performance assumptions', 'Danish Energy Agency catalogue/data sheets; dated vendor/site quotes override matched assumptions.', 'Large-plant reference values do not calibrate the current small package or local installation costs.', 'C'),
 ('Measured weather and performance', ['dwd','metoffice'], 'DWD identified radiation stations; Met Office recent hourly station observations', 'Quality-controlled measured inputs; user-uploaded pyranometer/PV/plant traces', 'DWD open data; Met Office subscription/access terms; explicit upload rights and provenance.', 'Representativeness and sensor exposure need review. Met Office recent API is not a long archive.', 'B/E'),
 ('Service access and logistics', ['osm-data','osm-tiles','maplibre'], 'Candidate region plus surveyed site access graph', 'Road/route geometry, depot travel, gate restrictions, delivery and service quotes', 'Licence-compatible vector/road provider or local extract; OSM data requires ODbL compliance and attribution. Surveyed access and operator records.', 'A routable public road does not prove heavy-vehicle or robot access. No automatic repair capability or response-time guarantee.', 'C'),
 ('Renewable-fuel eligibility', ['rfnbo'], 'EU framework plus separately versioned national/UK rules', 'Rule references, evidence obligations and conditional price-premium scenario', 'Official rules and project-specific specialist evidence; no automated certification in the first release.', 'Renewable supply or CO₂ consumption does not establish certified fuel, sale acceptance or net removal.', 'C/E'),
 ('Offline basemap', ['natural-earth','osm-tiles','maplibre'], 'World overview plus licensed regional tiles', 'Geographical context and selection', 'Natural Earth public-domain overview; appropriate licensed/self-hosted detailed tiles.', 'Public OSM raster tiles cannot be bulk-prefetched. A rendering library does not grant data rights.', 'A'),
]
if __name__ == '__main__':
    out = [dict(family=f,sources=s,coverage=c,inputs=i,access=a,boundary=b,stage=p)
           for f,s,c,i,a,b,p in ROWS]
    Path(__file__).with_name('data-catalogue.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
