'use strict';
// This explorer renders saved public data. It does not run a plant or query an API.
const saved = JSON.parse(document.getElementById('saved-data').textContent);
const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sourceLink = id => {const s=saved.sources[id];return `<a href="${escapeHTML(s.url)}">${escapeHTML(s.publisher)} · ${escapeHTML(s.title)}</a>`};
const workflow = [
  ['Explore','Pick an area, coordinates or candidate polygon. Inspect one geographical layer at a time.','Saved object: SiteCandidate'],
  ['Assess','Follow land, resource and infrastructure claims to their sources. Missing evidence stays unresolved.','Saved object: SiteAssessment'],
  ['Design','Configure the illustrated plant and its services against the site’s constraints.','Saved object: DeploymentDesign'],
  ['Run','Simulate continuous operation with declared weather, forecasts, uncertainty and controller information.','Saved object: YieldStudy'],
  ['Compare','Examine production, project cash flow, constraints and ranking reversals under the same question.','Saved objects: ProjectCashflow + RecommendationSet'],
  ['Simulate','Enter a difficult period’s recorded playback. Inspect why the plant behaved as it did.','Restored context: original state, controller, hour and evidence'],
];
const flowHost=document.getElementById('workflow');flowHost.classList.add('interactive');
flowHost.innerHTML='<p class="eyebrow">Proposed journey · select a stage</p><div class="controls">'+workflow.map((r,i)=>`<button type="button" aria-pressed="${i===0}" data-stage="${i}">${i+1}. ${r[0]}</button>`).join('')+'</div><div class="workflow-output" aria-live="polite"></div>';
function showStage(index){flowHost.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));const r=workflow[index];flowHost.querySelector('.workflow-output').innerHTML=`<p>${r[1]}</p><p class="small">${r[2]}</p>`}
flowHost.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>showStage(Number(b.dataset.stage))));showStage(0);

const catalogueHost=document.getElementById('data-catalogue');catalogueHost.classList.add('interactive');
catalogueHost.innerHTML='<p class="eyebrow">19 proposed connector families</p><label class="small" for="family-search">Find a dataset or requirement</label><div class="controls"><input id="family-search" type="search" placeholder="e.g. water, land, licence"><button id="clear-search" type="button">Clear</button></div><p id="family-count" class="small" aria-live="polite"></p><div class="catalogue-layout"><div class="family-list" aria-label="Data families"></div><div id="family-detail" aria-live="polite"></div></div>';
let selectedFamily=0;
function familyDetail(index){const r=saved.catalogue[index];selectedFamily=index;catalogueHost.querySelectorAll('[data-family]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.family)===index)));document.getElementById('family-detail').innerHTML=`<h3>${escapeHTML(r.family)}</h3><p class="small">Proposed stage ${escapeHTML(r.stage)} · ${index===0?'PVcalc aggregate probe tested; hourly adapter proposed':'Documentation reviewed; adapter not tested in this design'}</p><dl>${[['Coverage',r.coverage],['What it supplies',r.inputs],['Access',r.access],['What it cannot establish',r.boundary]].map(([k,v])=>`<dt>${k}</dt><dd>${escapeHTML(v)}</dd>`).join('')}</dl><p class="small">${r.sources.map(sourceLink).join('<br>')}</p>`}
function filterFamilies(){const q=document.getElementById('family-search').value.toLowerCase().trim();const indices=saved.catalogue.map((r,i)=>[r,i]).filter(([r])=>JSON.stringify(r).toLowerCase().includes(q)).map(([,i])=>i);const list=catalogueHost.querySelector('.family-list');list.innerHTML=indices.map(i=>`<button type="button" data-family="${i}" aria-pressed="false">${escapeHTML(saved.catalogue[i].family)}</button>`).join('');document.getElementById('family-count').textContent=`${indices.length} of ${saved.catalogue.length} families`;list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>familyDetail(Number(b.dataset.family))));if(indices.length)familyDetail(indices.includes(selectedFamily)?selectedFamily:indices[0]);else document.getElementById('family-detail').innerHTML='<p class="empty">No matching data families. Clear the search to restore the catalogue.</p>'}
document.getElementById('family-search').addEventListener('input',filterFamilies);document.getElementById('clear-search').addEventListener('click',()=>{document.getElementById('family-search').value='';filterFamilies();document.getElementById('family-search').focus()});filterFamilies();

const resourceHost=document.getElementById('resource-example');resourceHost.classList.add('interactive');
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
resourceHost.innerHTML='<p class="eyebrow">Saved real data · PVGIS 5.3 / SARAH3 · 2005–2023</p><div class="controls" id="site-buttons">'+saved.resource.sites.map((s,i)=>`<button type="button" data-site="${i}" aria-pressed="${i===0}">${escapeHTML(s.name)}</button>`).join('')+'</div><div class="resource-stats"><div><output id="annual-yield"></output><p class="small">kWh / kWp / year<br>Provider reference PV output</p></div><div><output id="winter-share"></output><p class="small">December–February share<br>of mean annual PV output</p></div></div><div id="monthly-chart"></div><div class="controls"><label for="month-select">Inspect a month<select id="month-select">'+months.map((m,i)=>`<option value="${i}">${m}</option>`).join('')+'</select></label></div><p id="month-output" aria-live="polite"></p><p id="site-provenance" class="small"></p><p class="small">Fixed 30° south-facing, 1 kWp crystalline silicon, free-standing, 14% input system losses and provider terrain horizon. This is not Dispatch Lab DC generation or a methane forecast. Chart scale is identical across sites.</p>';
let selectedSite=0;
function showResource(){const s=saved.resource.sites[selectedSite],m=Number(document.getElementById('month-select').value),r=s.monthly[m];resourceHost.querySelectorAll('[data-site]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.site)===selectedSite)));document.getElementById('annual-yield').textContent=s.annual.E_y.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2});const winter=s.monthly.filter(x=>[12,1,2].includes(x.month)).reduce((sum,x)=>sum+x.E_m,0);document.getElementById('winter-share').textContent=(100*winter/s.annual.E_y).toFixed(1)+'%';
  const ymax=200,w=680,h=250,left=42,bottom=218,scale=185/ymax;
  let chart=`<svg class="chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${escapeHTML(s.name)} monthly reference PV output; exact values available in the month selector"><text class="unit" x="${left}" y="13">Monthly kWh per 1 kWp</text>`;
  for(const y of [0,50,100,150,200]){const py=bottom-y*scale;chart+=`<line class="grid" x1="${left}" y1="${py}" x2="668" y2="${py}"/><text x="32" y="${py+4}" text-anchor="end">${y}</text>`}
  s.monthly.forEach((row,i)=>{const x=left+10+i*51,bh=row.E_m*scale;chart+=`<rect class="bar${i===m?' selected':''}" x="${x}" y="${bottom-bh}" width="31" height="${bh}"><title>${months[i]}: ${row.E_m.toFixed(2)} kWh/kWp</title></rect><text x="${x+15.5}" y="239" text-anchor="middle">${months[i].slice(0,3)}</text>`});chart+='</svg>';document.getElementById('monthly-chart').innerHTML=chart;
  document.getElementById('month-output').textContent=`${s.name} · ${months[m]}: ${r.E_m.toFixed(2)} kWh/kWp. Provider year-to-year standard deviation for this month: ${r.SD_m.toFixed(2)} kWh/kWp; this is not total prediction uncertainty.`;
  document.getElementById('site-provenance').innerHTML=`City reference point ${s.latitude.toFixed(4)}, ${s.longitude.toFixed(4)} · ${s.inputs.meteo_data.radiation_db} + ${s.inputs.meteo_data.meteo_db}. <a href="retrieval-20260913/${escapeHTML(s.request)}">Saved request</a> · <a href="retrieval-20260913/${escapeHTML(s.request.replace('request.json','response.json'))}">Raw provider response</a>. Winter share is calculated here from the saved monthly means.`;
}
resourceHost.querySelectorAll('[data-site]').forEach(b=>b.addEventListener('click',()=>{selectedSite=Number(b.dataset.site);showResource()}));document.getElementById('month-select').addEventListener('change',showResource);showResource();
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',String(a.hash==='#'+e.target.id))) }},{rootMargin:'0px 0px -70% 0px'});document.querySelectorAll('h2[id]').forEach(h=>observer.observe(h));
