"""Reviewed primary-source register for the siting design, 13 September 2026."""
import json
from pathlib import Path

ROWS = [
 ('pvgis','European Commission JRC','PVGIS overview and public beta notice','https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis_en','PVGIS 6 is offered for testing; do not silently change the pinned production adapter.'),
 ('pvgis-api','European Commission JRC','PVGIS 5 API','https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis/using-pvgis-5/api-non-interactive-service_en','Versioned server-side API, parameters, units, limits and CORS restrictions. Three v5_3 PVcalc requests were tested.'),
 ('pvgis-manual','European Commission JRC','PVGIS 5 user manual','https://joint-research-centre.ec.europa.eu/photovoltaic-geographical-information-system-pvgis/using-pvgis-5/pvgis-5-user-manual_en','SARAH3 2005–2023; provider timestamp and TMY conventions. The detailed hourly explanation also retains older SARAH names; validate the exact selected product.'),
 ('era5','ECMWF','ECMWF Reanalysis v5','https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5','Long historical hourly atmospheric reconstruction; reanalysis is not a site measurement.'),
 ('era5-land','Copernicus Climate Data Store','ERA5-Land hourly data from 1950 to present','https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land?tab=overview','Higher-resolution land reconstruction and documented uncertainty; dataset-specific accumulation conversion.'),
 ('weather-runs','Open-Meteo','Single Runs API','https://open-meteo.com/en/docs/single-runs-api','ECMWF IFS original runs from March 2024; preserve initialisation and assumed availability, not a stitched hindcast.'),
 ('weather-history','Open-Meteo','Historical Weather API','https://open-meteo.com/en/docs/historical-weather-api','Explicit ERA5/ERA5-Land model selection and hourly conventions.'),
 ('weather-terms','Open-Meteo','Pricing and use terms','https://open-meteo.com/en/pricing','Free service is non-commercial; commercial historical/ensemble/single-run access needs an appropriate plan. Data licence and API access are distinct.'),
 ('cams','Copernicus Atmosphere Monitoring Service','Solar radiation services','https://atmosphere.copernicus.eu/solar-radiation-supplementary-products','Historical global/direct/diffuse radiation since 2004; satellite coverage and atmospheric inputs.'),
 ('clc','Copernicus Land Monitoring Service','CLCplus Backbone 2023','https://land.copernicus.eu/en/products/clc-backbone/clcplus-backbone-2023-raster-10-m-europe-2-yearly','10 m European land-cover raster; observed cover does not establish use permission or ownership.'),
 ('dem','Copernicus Data Space Ecosystem','Copernicus Contributing Missions documentation','https://documentation.dataspace.copernicus.eu/Data/Others/CCM.html','GLO-30 is a 30 m digital surface model including vegetation and structures, not a parcel survey.'),
 ('natura','European Environment Agency','Natura 2000 viewer disclaimer','https://natura2000.eea.europa.eu/html/Disclaimer.html','The viewer describes the 2024 network; country submissions and sensitive-feature omissions matter.'),
 ('natura-service','European Environment Agency','Natura 2000 spatial service','https://bio.discomap.eea.europa.eu/arcgis/rest/services/ProtectedSites/Natura2000Sites/MapServer','Queryable spatial service; exact version, jurisdiction and coverage must be frozen.'),
 ('england','Natural England / GOV.UK','Access Natural England maps and data','https://www.gov.uk/guidance/how-to-access-natural-englands-maps-and-data','MAGIC and downloadable national environmental layers; England is not the whole UK.'),
 ('parcels','European Commission INSPIRE','Cadastral parcels specification','https://knowledge-base.inspire.ec.europa.eu/publications/inspire-data-specification-cadastral-parcels-technical-guidelines_en','Common spatial specification; national geometry, rights and access remain separate.'),
 ('flood','European Commission JRC / CEMS','River flood hazard maps for Europe and the Mediterranean','https://data.jrc.ec.europa.eu/dataset/1d128b6c-a4ee-4858-9e34-6210707f3c81','Modelled water depths for return periods 10–500 years; river basins >150 km². Explicitly not an official flood-hazard map; CC BY 4.0.'),
 ('wei','European Environment Agency','Seasonal Water Exploitation Index plus at sub-unit level','https://www.eea.europa.eu/en/datahub/datahubitem-view/5a980253-9e62-4004-830e-ae7a985237b9','2023 edition published January 2026, temporal coverage 2000–2023; seasonal catchment pressure, not an abstraction entitlement.'),
 ('aqueduct','World Resources Institute','Aqueduct 4.0 data','https://www.wri.org/data/aqueduct-global-maps-40-data','August 2023 framework; baseline and future water-risk indicators. WRI describes this as prioritisation requiring local investigation.'),
 ('industrial','European Environment Agency','Industrial Emissions Portal datasets','https://industry.eea.europa.eu/industrial-emissions/dataset','Facility locations and reported annual emissions; not a CO₂ supply offer, gas assay or captured-volume dataset.'),
 ('ukpn','UK Power Networks DSO','Network data and development plans','https://dso.ukpowernetworks.co.uk/dso-data','Indicative EHV network headroom and future scenarios; not a reserved import/export connection.'),
 ('entsoe','ENTSO-E Transparency Platform','How to get an API security token','https://transparencyplatform.zendesk.com/hc/en-us/articles/12845911031188-How-to-get-security-token','Authenticated API access path; do not embed tokens in exports or browser code.'),
 ('entsoe-api','ENTSO-E','Transparency data extraction implementation guide','https://transparency.entsoe.eu/content/static_content/download?path=%2FStatic+content%2Fweb+api%2FIG-for-TP-data-extraction-process.pdf','Market/bidding-zone documents including day-ahead prices; preserve native resolution and publication.'),
 ('elexon','Elexon','Insights API Developer Portal','https://developer.data.elexon.co.uk/','GB operational and settlement data; imbalance/system prices are not a site electricity tariff.'),
 ('esios','Red Eléctrica','e·sios API documentation','https://api.esios.ree.es/','Spanish market/context data; token access and explicit publication dates.'),
 ('entsog','ENTSOG','System capacity maps','https://www.entsog.eu/maps','European transmission context. Map disclaimer restricts use to indicative information and disclaims commercial-use reliance; keep as a reference, not an assumed reusable commercial layer.'),
 ('costs','Danish Energy Agency','Technology Data for Renewable Fuels','https://ens.dk/en/analyses-and-statistics/technology-data-renewable-fuels','Live page links August 2026 catalogue/data sheets; scale, technology, currency year and uncertainty must accompany any imported benchmark.'),
 ('rfnbo','European Commission DG Energy','Renewable hydrogen','https://energy.ec.europa.eu/topics/eus-energy-system/hydrogen/renewable-hydrogen_en','Additionality and temporal/geographic correlation affect renewable-fuel eligibility; not a certification implemented by this design.'),
 ('metoffice','Met Office','Weather DataHub observations overview','https://datahub.metoffice.gov.uk/docs/g/category/observations/overview','Recent hourly station measurements; this API has a 48-hour historical window, not a long-term site calibration archive.'),
 ('dwd','Deutscher Wetterdienst','10-minute solar observations dataset description','https://opendatat.dwd.de/climate_environment/CDC/observations_germany/climate/10_minutes/solar/DESCRIPTION_obsgermany_climate_10min_solar_en.pdf','Station radiation and quality metadata; use identified representative stations, not sunshine duration as irradiance.'),
 ('fraunhofer','Fraunhofer ISE','Regional hydrogen and Power-to-X ecosystems','https://www.ise.fraunhofer.de/en/business-areas/hydrogen-technologies/hydrogen-system-analysis/analysis-and-optimization-of-regional-hydrogen-and-power-to-x-ecosystems.html','HYSCOPE / geo-techno-economic analysis combines location, scale, operation and supply chains.'),
 ('reopt','NREL / National Laboratory of the Rockies','REopt user manual','https://reopt.nlr.gov/tool/reopt-user-manual.pdf','Techno-economic and resilience design pattern; US-oriented defaults are not European methane-plant inputs.'),
 ('atlite','PyPSA / atlite authors','Calculate land-use availabilities','https://atlite.readthedocs.io/en/master/examples/landuse-availability.html','Explicit exclusion masks and renewable-potential calculation; reuse GIS patterns, keep plant kernels.'),
 ('ninja','Pfenninger and Staffell / Renewables.ninja','About Renewables.ninja','https://www.renewables.ninja/about','Hourly renewable modelling and validation work; separate commercial-data terms.'),
 ('pv-uncertainty','NREL','Quantifying Uncertainty in PV Energy Estimates, final report and errata','https://docs.nlr.gov/docs/fy23osti/84993.pdf','Separates resource variability from performance uncertainty and defines exceedance probabilities. Use its corrected method, not unreviewed defaults.'),
 ('aggregation','Kotzur, Markewitz, Robinius and Stolten','Time series aggregation for energy system design: Modeling seasonal storage','https://arxiv.org/abs/1710.07593','2018 Applied Energy study, DOI 10.1016/j.apenergy.2018.01.023; inter-period storage states matter for representative-period design.'),
 ('maplibre','MapLibre','MapLibre GL JS','https://maplibre.org/projects/gl-js/','Browser vector-map rendering; tiles and data have separate licences.'),
 ('osm-tiles','OpenStreetMap Foundation','Tile usage policy','https://operations.osmfoundation.org/policies/tiles/','The public raster tile service prohibits bulk/offline prefetch; select a suitable provider or licensed local data.'),
 ('osm-data','OpenStreetMap Foundation','Copyright and licence','https://www.openstreetmap.org/copyright','Road/vector data is ODbL with attribution and database obligations; data rights are distinct from hosted tiles, geocoding and routing services.'),
 ('natural-earth','Natural Earth','Terms of use','https://www.naturalearthdata.com/about/terms-of-use/','Public-domain low-resolution geography suitable for the offline overview; not cadastral boundaries.'),
]

if __name__ == '__main__':
    out = dict(reviewed_at='2026-09-13', scope='Primary documentation review and selected read-only API probe. Only PVGIS PVcalc was live-tested; other connectors are proposed and require adapter acceptance.',
        sources=[dict(id=i,publisher=p,title=t,url=u,used_for=c) for i,p,t,u,c in ROWS])
    Path(__file__).with_name('sources.json').write_text(json.dumps(out,indent=2,ensure_ascii=False)+'\n')
