"""Authored evidence records; numerical values are loaded from calculated outputs."""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def load(name):
    return json.loads((HERE / "analysis" / f"{name}.json").read_text())


# ID, title, authors/publisher, publication date, exact URL, evidence type, access.
ROWS = [
    (
        "pv-data",
        "IEA PVPS Task 13 module validation dataset: SUPSI",
        "SUPSI PVLab; IEA PVPS Task 13; Sandia PVPMC",
        "2018–2019 measurements; 2020 report",
        "https://pvpmc.sandia.gov/datasets/iea-pvps-task-13-module-validation-dataset/",
        "experimental data",
        "Twelve original CSVs and characterization workbook downloaded; SHA256 recorded.",
    ),
    (
        "pv-report",
        "Climatic Rating of Photovoltaic Modules: Different Technologies for Various Operating Conditions",
        "IEA PVPS Task 13",
        "2020",
        "https://pvpmc.sandia.gov/download/3773/",
        "experimental methods",
        "Full report read, especially Annex 1; cached.",
    ),
    (
        "pem-data",
        "Data from: Grid-connected PEM electrolysis: Experimental characterization and dispatch simulation across a decarbonizing grid",
        "Evan Veatch; Bret Windom; Andrew Zdanowicz / Colorado State University, Dryad",
        "2026-09-03",
        "https://datadryad.org/dataset/doi:10.5061/dryad.8931zcs64",
        "experimental data",
        "Dryad landing read. Direct archive blocked; original files from its linked author repository cached at immutable identifier.",
    ),
    (
        "pem-code",
        "ERCOT Electrolyzer Simulation Engine: experimental data and characterization",
        "Veatch et al. / HydrogenDude",
        "snapshot retrieved 2026-09-12",
        "https://github.com/HydrogenDude/ERCOT_Electrolyzer_Sim_Engine/tree/a534d8a89cf5e662f183d91a9b40b7936387c4a2",
        "author data and code",
        "Original channels and characterization code cached; not all repository models adopted.",
    ),
    (
        "pem-preprint",
        "Grid-connected PEM electrolysis: Experimental characterization and dispatch simulation across a decarbonizing grid",
        "Evan Veatch; Andrew Zdanowicz; Bret Windom / SSRN",
        "2026-07-14 posted",
        "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=7117658",
        "preprint",
        "Landing and abstract read; PDF fetch blocked. Peer-reviewed publication not verified.",
    ),
    (
        "pem-dispatch",
        "Experimental dynamic dispatch of a 60 kW proton exchange membrane electrolyzer in power-to-gas application",
        "J.M. Stansberry; J. Brouwer / International Journal of Hydrogen Energy 45(16), 9305–9316",
        "2020",
        "https://www.sciencedirect.com/science/article/pii/S0360319920304237",
        "peer-reviewed experiment",
        "Abstract read; used only for reported rapid dispatch and part-load support losses.",
    ),
    (
        "pem-age",
        "Performance data extraction from dynamic long-term operation of proton exchange membrane and alkaline water electrolysis cells",
        "Sharon-Virginia Pape; Sarah Zerressen; Martin Florian Seidler et al. / IJHE 127, 51–63",
        "2025",
        "https://publications.rwth-aachen.de/record/1010862/files/1010862.pdf",
        "peer-reviewed experiment",
        "Full paper read. Cell-scale dynamic characterization, not a fitted system lifetime.",
    ),
    (
        "jrc",
        "EU harmonised protocols for testing of low temperature water electrolysers",
        "G. Tsotridis; A. Pilenga / European Commission Joint Research Centre; JRC122565",
        "2021",
        "https://publications.jrc.ec.europa.eu/repository/bitstream/JRC122565/jrc122565_ltwe_harmonisation_online_identifier_4.pdf",
        "official test protocol",
        "Full PDF available; system/cell boundary and test-protocol guidance.",
    ),
    (
        "battery",
        "Ageing and energy performance analysis of a utility-scale lithium-ion battery for power grid applications through a data-driven empirical modelling approach",
        "Alberto Grimaldi; Francesco Demetrio Minuto; Alessandro Perol; Silvia Casagrande; Andrea Lanzini / Journal of Energy Storage 65,107232",
        "2023",
        "https://iris.polito.it/retrieve/handle/11583/2977810/3d8ed5b7-7e2e-4251-a62e-49f2682c8297/1-s2.0-S2352152X23006291-main.pdf",
        "peer-reviewed field experiment",
        "Full PDF read via browser including Table 6. Local download blocked; regression transcribed, no raw SCADA available.",
    ),
    (
        "slurry",
        "Methanation Pilot Plant with a Slurry Bubble Column Reactor: Setup and First Experimental Results",
        "Simon Sauerschell; Siegfried Bajohr; Thomas Kolb / Energy & Fuels 36(13),7166–7176",
        "2022",
        "https://publikationen.bibliothek.kit.edu/1000148877/149046930",
        "peer-reviewed pilot experiment",
        "Full open PDF cached; Figure 8 visually inspected and manually digitized.",
    ),
    (
        "fixed-bed",
        "Catalytic methanation of CO2 in biogas: experimental results from a reactor at full scale",
        "Christian Dannesboe; John Bøgild Hansen; Ib Johannsen / Reaction Chemistry & Engineering 5,183–189",
        "2019-11-28 online; 2020 volume",
        "https://pure.au.dk/ws/files/174380919/Catalytic_methanation_of_CO2_in_biogas_RCE_Published.pdf",
        "peer-reviewed pilot experiment",
        "Full open PDF cached and read, including temperature and feed-cleanup conditions.",
    ),
    (
        "kinetics",
        "Determination of reaction kinetics in three phase CO2 methanation",
        "Mathias Monning; Asad Asadli; Siegfried Bajohr; Moritz Wolf; Thomas Kolb / RSC",
        "2025-12-10 online",
        "https://publikationen.bibliothek.kit.edu/1000188810/171087110",
        "peer-reviewed experiment",
        "Full open paper cached. Equation 13 and Table 1 scoped to conditioned catalyst and DBT system.",
    ),
    (
        "density",
        "Revised Standardized Equation for Hydrogen Gas Densities for Fuel Consumption Applications",
        "Eric W. Lemmon; Marcia L. Huber; Jacob W. Leachman / Journal of Research of NIST 113,341–350",
        "2008",
        "https://nvlpubs.nist.gov/nistpubs/jres/113/6/V113.N06.A05.pdf",
        "reference correlation",
        "Full paper cached; Equation 3 coefficients and all five check points independently reproduced.",
    ),
    (
        "nist-ch4",
        "Methane: gas phase thermochemistry and Shomate coefficients",
        "NIST Chemistry WebBook; Chase, NIST-JANAF",
        "1998 reference compilation; live WebBook",
        "https://webbook.nist.gov/cgi/cbook.cgi?ID=C74828&Mask=1",
        "thermochemical reference",
        "Coefficients and ranges read from primary database.",
    ),
    (
        "nist-co2",
        "Carbon dioxide: gas phase thermochemistry and Shomate coefficients",
        "NIST Chemistry WebBook; Chase, NIST-JANAF",
        "1998 reference compilation; live WebBook",
        "https://webbook.nist.gov/cgi/cbook.cgi?ID=C124389&Mask=1",
        "thermochemical reference",
        "Coefficients and ranges read from primary database.",
    ),
    (
        "nist-h2",
        "Hydrogen: gas phase thermochemistry and Shomate coefficients",
        "NIST Chemistry WebBook; Chase, NIST-JANAF",
        "1998 reference compilation; live WebBook",
        "https://webbook.nist.gov/cgi/cbook.cgi?ID=C1333740&Mask=1",
        "thermochemical reference",
        "Coefficients and ranges read from primary database.",
    ),
    (
        "nist-water",
        "Water: gas phase thermochemistry and Shomate coefficients",
        "NIST Chemistry WebBook; Chase, NIST-JANAF",
        "1998 reference compilation; live WebBook",
        "https://webbook.nist.gov/cgi/cbook.cgi?ID=C7732185&Mask=1",
        "thermochemical reference",
        "Gas-water coefficients start at 500 K; 298 K formation enthalpy treated separately.",
    ),
    (
        "compression",
        "Energy requirements for hydrogen gas compression and liquefaction as related to vehicle storage needs, Record 9013",
        "US Department of Energy Hydrogen Program",
        "2009 record",
        "https://www.hydrogen.energy.gov/docs/hydrogenprogramlibraries/pdfs/9013_energy_requirements_for_hydrogen_gas_compression.pdf",
        "official measured/reference comparison",
        "Full document read; vehicle-pressure evidence, not a direct 450 kW plant compressor calibration.",
    ),
    (
        "co2-phase",
        "Carbon dioxide gas encyclopedia",
        "Air Liquide",
        "n.d.; current page",
        "https://encyclopedia.airliquide.com/carbon-dioxide",
        "manufacturer physical reference",
        "Phase/state reference; no storage-system quotation or delivery reliability data.",
    ),
    (
        "flow",
        "EL-FLOW Select mass flow meters and controllers: technical specifications",
        "Bronkhorst",
        "n.d.; accessed edition",
        "https://www.bronkhorst.com/getmedia/98668a82-8d1c-4b7f-af8e-995be25641b3/EL-FLOW-Select_en.pdf",
        "manufacturer specification",
        "Reference-condition accuracy, zero and temperature terms read; not a Gaussian-noise calibration.",
    ),
    (
        "pressure",
        "IS-3 intrinsically safe pressure transmitter: operating instructions",
        "WIKA",
        "11/2021, revision 5",
        "https://kz.wika.com/upload/OI_IS_3_en_de_62152.pdf",
        "manufacturer specification",
        "Accuracy, span, drift and temperature limits read; specific option and gas suitability still required.",
    ),
    (
        "methyinfra",
        "D1 Technical report on methods used for calibration of a Coriolis flow meter",
        "MetHyInfra consortium / EMPIR 20IND11",
        "project report; document date not verified",
        "https://www.methyinfra.ptb.de/fileadmin/documents/empir-2021/methyinfra/documents/A1.3.4_-_D1_-_Technical_report_on_the_methods_used_for_calibration_of_a_CFM.pdf",
        "metrology experiment",
        "Full report read; calibration at 0.26–1.84 kg/min. Table 5 has inconsistent distribution labels; not silently repaired here.",
    ),
    (
        "soiling",
        "Photovoltaic soiling loss in Europe: Geographical distribution and cleaning recommendations",
        "Álvaro Fernández Solas; Nicholas Riedel-Lyngskær; Natalie Hanrieder et al. / Renewable Energy 239,122086",
        "2024-12-04 online; 2025 volume",
        "https://elib.dlr.de/210457/1/Published_Paper_Photovoltaic%20soiling%20loss%20in%20Europe_Geographical%20distribution%20and%20cleaning%20recommendations.pdf",
        "peer-reviewed measurements and regional model",
        "Full paper cached and read; nine ground sites. Raw site data on request, no refit claimed.",
    ),
    (
        "abrasion",
        "Abrasion of PV Antireflective Coatings by Robot Cleaning",
        "B. Figgis et al. / IEEE Journal of Photovoltaics",
        "2024",
        "https://doi.org/10.1109/JPHOTOV.2024.3414192",
        "peer-reviewed field experiment",
        "Abstract read: 18-month exposure, multiple module/coating types. No numerical abrasion rate fitted.",
    ),
    (
        "t4",
        "Ecoppia T4 datasheet",
        "Ecoppia",
        "document identifier 020321; date format not assumed",
        "https://www.ecoppia.com/warehouse/temp/ecoppia/T4_Datasheet.pdf",
        "manufacturer specification",
        "Full four-page datasheet read; tracker geometry and dedicated charging are explicit.",
    ),
    (
        "gekko",
        "GEKKO Solar Roboter: technical specifications",
        "Serbot",
        "n.d.; current page",
        "https://www.serbot.ch/de/produktlinie-fuer-photovoltaik-reinigung/gekko-solar-roboter",
        "manufacturer specification",
        "Official indexed full specifications read; English direct fetch blocked. Contradictory maximum-speed entries retained as unresolved.",
    ),
    (
        "spot",
        "Spot specifications",
        "Boston Dynamics",
        "n.d.; current support page",
        "https://support.bostondynamics.com/articles/Knowledge/Spot-Specifications-49916",
        "manufacturer specification",
        "Current 564 Wh specification; older SDK 605 Wh profile not mixed with it.",
    ),
    (
        "anymal",
        "ANYmal X inspection robot",
        "ANYbotics",
        "n.d.; current page",
        "https://www.anybotics.com/robotics/anymal-x/",
        "manufacturer specification",
        "Current Zone 1 IIB claim; no blanket hydrogen gas-group approval inferred.",
    ),
    (
        "dock3",
        "DJI Dock 3: product support and specifications",
        "DJI",
        "n.d.; current page",
        "https://www.dji.com/support/product/dock-3",
        "manufacturer specification",
        "Aircraft and dock limits read separately; maxima and laboratory charge/flight conditions retained.",
    ),
    (
        "autoinspect",
        "AutoInspect: Towards Long-Term Autonomous Industrial Inspection",
        "Michal Staniaszek; Tobit Flatscher; Joseph Rowell; Hanlin Niu; Wenxing Liu; Yang You; Robert Skilton; Maurice Fallon; Nick Hawes",
        "2024-04-22, arXiv v2",
        "https://arxiv.org/html/2404.12785v2",
        "research field deployment",
        "Full paper read; action counts and intervention definitions retained without a fitted independent-failure assumption.",
    ),
    (
        "gecko",
        "Reinforcement Learning for RUG",
        "Luke Roberto / Gecko Robotics",
        "2025-06-02",
        "https://www.geckorobotics.com/resources/blog/reinforcement-learning-for-rug",
        "manufacturer technical account",
        "Measurement mechanism read; no universal detection probability or asset-repair capability.",
    ),
    (
        "ceora",
        "CEORA 544/546 EPOS, RZ43L/RZ43M, CS4: operators manual",
        "Husqvarna",
        "2023-12-22 document",
        "https://www.husqvarna.com/hbd/tdrdownload/v2/pub000092868/doc000237925/OM/9A1r-tFM0-t_2K7MgZbdnOTCa6k",
        "manufacturer specification",
        "546 EPOS/RZ43L entries read; different deck/charge duty combinations not mixed.",
    ),
    (
        "sampling",
        "Understanding time delay: four main areas to inspect",
        "Swagelok; Industrial Sampling Systems by Tony Waters",
        "2013 book; article date not stated",
        "https://boston.swagelok.com/en/resources/industry-expertise/time-delay",
        "manufacturer engineering reference",
        "Full article read; actual-volume flow and well-mixed flush example reproduced.",
    ),
    (
        "cdc90",
        "Liquiline Control CDC90 cleaning and calibration system",
        "Endress+Hauser",
        "n.d.; current page",
        "https://www.endress.com/en/field-instruments-overview/liquid-analysis-product-overview/pH-sensor-automatic-cleaning-calibration-cdc90",
        "manufacturer specification",
        "Full product description read: pH/ORP only, not hydrogen-flow sensor calibration.",
    ),
    (
        "rotork",
        "IQ3 Pro intelligent electric actuators",
        "Rotork",
        "n.d.; current page",
        "https://www.rotork.com/en/products/electric-intelligent-actuators/iq3-pro",
        "manufacturer specification",
        "Existing taxonomy primary reference; bounded valve actuation, not repair evidence.",
    ),
    (
        "taurob",
        "Taurob Operator",
        "Taurob",
        "n.d.; current page",
        "https://www.taurob.com/operator/",
        "manufacturer specification",
        "Current page read: 150 Nm end-effector torque and 75 kg maximum lift claims; reach/configuration qualifications required.",
    ),
    (
        "enapter",
        "EL 4.1 electrolyser handbook",
        "Enapter",
        "n.d.; current handbook",
        "https://handbook.enapter.com/electrolyser/el41/",
        "manufacturer procedure",
        "Existing review procedure source for a named AEM device; does not authorize PEM stack service.",
    ),
    (
        "maximo",
        "Maximo completes 100 MW of robotic solar installation",
        "Maximo / company release carried by Nasdaq",
        "2026-03-25",
        "https://www.nasdaq.com/press-release/maximo-completes-100-mw-robotic-solar-installation-2026-03-25",
        "company deployment claim",
        "Release read; cumulative installation is not unattended end-to-end construction or O&M performance.",
    ),
    (
        "5b",
        "5B Maverick",
        "5B",
        "n.d.; current page",
        "https://5b.co/en/5b-maverick",
        "manufacturer design",
        "Product page read; preassembled deployable design, not recurring in-operation unfolding.",
    ),
    (
        "dea",
        "Technology Data for Renewable Fuels",
        "Danish Energy Agency",
        "August 2026 revision; 2025 cost basis",
        "https://ens.dk/media/7823/download",
        "official technology cost catalogue",
        "Full catalogue cached, chapter 80 tables read. Large-scale reference and cost exclusions retained.",
    ),
    (
        "dea-brief",
        "Brief on technology data for hydrogen production via electrolysis",
        "Danish Energy Agency",
        "August 2026 revision",
        "https://ens.dk/media/3352/download",
        "official cost-boundary note",
        "Current PDF cached; same URL formerly indexed as 2024, current internal date used.",
    ),
    (
        "wind2h2",
        "The Wind-to-Hydrogen Project: Operational Experience, Performance Testing, and Systems Integration",
        "K.W. Harrison; G.D. Martin; T.G. Ramsden; W.E. Kramer; F.J. Novachek / NREL TP-550-44082",
        "2009-03",
        "https://docs.nlr.gov/docs/fy09osti/44082.pdf",
        "operational test report",
        "Full report cached, especially failure/repair experience; historical cases do not establish modern fleet hazards.",
    ),
    (
        "hycred",
        "Hydrogen Component Reliability Database (HyCReD)",
        "Genevieve Saur; Kevin Hartmann; Katrina Groth; William Buttner; Ahmad Al-Douri; Joseph Robinson / NREL",
        "2024",
        "https://research-hub.nlr.gov/en/publications/hydrogen-component-reliability-database-hycred",
        "official reliability programme",
        "Project material identifies collection/exposure requirements; no public matched fleet rates extracted.",
    ),
    (
        "forecast",
        "Single Runs API",
        "Open-Meteo",
        "n.d.; current documentation",
        "https://open-meteo.com/en/docs/single-runs-api",
        "source documentation",
        "Current radiation interval, initialization and archive availability conventions read.",
    ),
    (
        "gum",
        "Metrological compatibility of measurement results",
        "JCGM International Vocabulary of Metrology",
        "VIM 3",
        "https://jcgm.bipm.org/vim/en/2.47.html",
        "metrology reference",
        "Uncertainty of a difference includes covariance; no generic 2% noise endorsement.",
    ),
    (
        "festo",
        "Safety engineering: service-life parameters",
        "Festo",
        "n.d.; technical catalogue",
        "https://www.festo.com/PDF_Flip/safety/en/files/assets/basic-html/page19.html",
        "manufacturer reliability definitions",
        "B10/B10d are cycle-based reliability measures, not universal plant MTBF.",
    ),
]
SOURCES = {
    r[0]: dict(
        zip(
            ["title", "authors_publisher", "publication_date", "url", "evidence_kind", "access"],
            r[1:],
            strict=True,
        ),
        accessed_date="2026-09-12",
    )
    for r in ROWS
}
(HERE / "sources.json").write_text(json.dumps(SOURCES, indent=2, ensure_ascii=False) + "\n")
pv, pem, gas, reactor, derived = (load(n) for n in ["pv", "pem", "gas", "reactor", "derived"])
profiles = [
    dict(
        id="supsi-mono-temperature-v1",
        component="solar",
        status="fitted_reference",
        values=pv["parameters"],
        units={"U0": "W/(m² K)", "U1": "W s/(m³ K)", "effective_NOCT": "°C"},
        domain="SUPSI module back temperature, selected daylight Gpoa≥200 W/m²; same site 2018–2019, local measured wind; not an external-site calibration.",
        sources=["pv-data", "pv-report"],
        artifact="analysis/pv.json",
        promotion="Add named wind-aware reference option; preserve generic fixture and wind measurement height. Do not use as new universal NOCT.",
    ),
    dict(
        id="csu-pem-ac-flow-v1",
        component="electrolyser",
        status="fitted_reference",
        values=next(
            r
            for r in pem["scores"]
            if r["model"] == "parameters"
            and r["power_boundary"] == "system_power"
            and r["hydrogen_channel"] == "hydrogen_flow"
        ),
        units={"affine_kg_per_kwh": "kg/kWh", "affine_kg_per_h": "kg/h"},
        domain="Observed one-day 60 kW-class PEM system, about 36–75 kW whole-system AC demand. Net-looking measured flow channel retained by original name. Do not extrapolate to zero or 450 kW.",
        sources=["pem-data", "pem-code", "pem-preprint"],
        artifact="analysis/pem.json",
        promotion="Build stack, conversion, support-load and usable-output interfaces before transfer. Reference-device fit is suitable for adapter tests.",
    ),
    dict(
        id="italy-nmc-ac-v1",
        component="battery",
        status="published_fit_reproduced",
        values=load("battery"),
        units={"power": "AC kW", "rte": "fraction"},
        domain="500 kW/822 kWh NMC AC-coupled installation, SOC10–90%; first three years P≥0.15 pu, year4≥0.10 pu. Authors cycle-level fit, no independent refit.",
        sources=["battery"],
        artifact="analysis/battery.json",
        promotion="Reference AC profile only. Separate auxiliary boundary; round-trip data does not identify directional efficiency.",
    ),
    dict(
        id="kit-slurry-step-v1",
        component="thermal",
        status="digitized_descriptive_fit",
        values=reactor,
        units={"effective_time_constant_minutes": "min"},
        domain="Figure8 feed-rate step with controlled 310°C coolant, 20 bar slurry pilot. Does not identify ambient UA or independent thermal capacity.",
        sources=["slurry"],
        artifact="analysis/reactor.json",
        promotion="Use as a reduced-response benchmark after separating coolant and ambient heat paths. No ambient-loss coefficient replacement.",
    ),
    dict(
        id="nist-h2-density-v1",
        component="gas-storage",
        status="reference_equation_verified",
        values={"check_points": gas["reference_checks"]},
        units={"pressure": "MPa absolute", "temperature": "K", "density": "mol/L"},
        domain="Correlation 150–1000 K, ≤200 MPa; accuracy is subdomain-specific. Density only, not full thermodynamic EOS.",
        sources=["density"],
        artifact="analysis/gas.json",
        promotion="Can underpin explicit pressure-volume-inventory reference states. Pressure design and minimum delivery pressure remain choices.",
    ),
    dict(
        id="nist-ideal-chemistry-v1",
        component="chemistry",
        status="reference_calculation",
        values=derived["chemistry"],
        units={"reaction_heat": "kWh/kg CH4", "material_ratios": "kg/kg"},
        domain="Complete ideal gas reaction, water vapour; common Shomate range500–1000 K, reference heat at298.15 K separate. No conversion or kinetics guarantee.",
        sources=["nist-ch4", "nist-co2", "nist-h2", "nist-water"],
        artifact="analysis/derived.json",
        promotion="Update chemistry as a versioned optional model with independent balance checks; account for feed enthalpy before changing reaction heat.",
    ),
    dict(
        id="serbot-gekko-support-v1",
        component="support",
        status="vendor_specification_and_derivation",
        values=derived["portable_cleaning"],
        units={"area": "m²", "electricity": "kWh", "water": "L"},
        domain="Named joystick-operated wet cleaner. Vendor rate, not whole-site delivered productivity. Air supply, operator, water and lift required.",
        sources=["gekko"],
        artifact="analysis/derived.json",
        promotion="Named contract with separate air, electricity and water inputs; unsupported autonomy remains unavailable.",
    ),
    dict(
        id="ecoppia-t4-v1",
        component="cleaning",
        status="vendor_specification_and_derivation",
        values=derived["row_cleaning"],
        units={"area": "m²", "rate": "m²/h"},
        domain="Tracker-compatible stow≤2°, dedicated bridges and dock PV. Per-device nightly capacity separate from transit speed.",
        sources=["t4"],
        artifact="analysis/derived.json",
        promotion="Alternative array design, not a direct replacement for the fixed-tilt fixture robot.",
    ),
    dict(
        id="autoinspect-deployments-v1",
        component="inspection",
        status="published_deployment_counts",
        values=derived["inspection"],
        units={"mtbi": "calendar hours"},
        domain="Two Spot/Frontier deployments at UKAEA in2023/2024; clustered software/configuration interventions, inspection actions not repair attempts.",
        sources=["autoinspect"],
        artifact="analysis/derived.json",
        promotion="Reference scenario separates invalid observations, autonomy recovery and human intervention; no universal Bernoulli hazard.",
    ),
]
(HERE / "reference-profiles.json").write_text(
    json.dumps(
        dict(
            schema_version="dispatch-lab/literature-profiles/1",
            scope="Research reference records; not loaded into production or historical archives.",
            profiles=profiles,
        ),
        indent=2,
        ensure_ascii=False,
    )
    + "\n"
)
GROUPS = {
    "layout": (
        "design_choice",
        ["density", "t4", "gekko"],
        "Capacities and geometry are designs; select an internally compatible reference package before sizing conclusions.",
    ),
    "thermal": (
        "structural_change_required",
        ["slurry", "fixed-bed", "kinetics"],
        "New digitized response benchmark; ambient losses, coolant exchange, startup and aged catalyst must be separated.",
    ),
    "chemistry": (
        "reference_calculation_available",
        ["nist-ch4", "nist-co2", "nist-h2", "nist-water"],
        "Molecular weights and gas enthalpies quantified. Feed enthalpy is consequential; ideal conversion remains explicit.",
    ),
    "electrolyser": (
        "reference_fit_available",
        ["pem-data", "pem-code", "pem-dispatch", "pem-age", "jrc"],
        "Raw-data fit complete. Plant transfer requires AC/DC, cooling, purification and standby boundaries.",
    ),
    "battery": (
        "published_curve_available",
        ["battery"],
        "Near-scale published cycle curve reproduced; raw SCADA and current fixture chemistry not matched.",
    ),
    "gas-storage": (
        "reference_calculation_available",
        ["density", "compression", "co2-phase"],
        "Density check points verified; usable pressure heel quantified. Compressor, vaporizer and purchase design still open.",
    ),
    "solar": (
        "reference_fit_available",
        ["pv-data", "pv-report"],
        "Held-out temperature model fitted; back temperature not cell junction, no site yield or shading validation.",
    ),
    "weather": (
        "method_defined_data_extension_needed",
        ["forecast", "soiling"],
        "No new weather bias fit. Add rain/wind and calibrate lead-time errors with chronologically withheld seasons; reanalysis is not measured plant output.",
    ),
    "sensing": (
        "bounded_reference_available",
        ["flow", "pressure", "methyinfra", "gum"],
        "Accuracy floors and span/temperature/drift terms now explicit; fault probabilities and residual covariance remain unmeasured.",
    ),
    "faults": (
        "mechanisms_supported_rates_open",
        ["wind2h2", "pem-age", "kinetics", "hycred"],
        "Failures have cause-specific persistence and recovery. No defensible modern fleet incidence rate extracted.",
    ),
    "cleaning": (
        "named_specs_and_regional_evidence",
        ["soiling", "abrasion", "t4", "gekko"],
        "European soiling evidence and equipment rates available; exact site deposition/removal and permanent damage not fitted.",
    ),
    "inspection": (
        "published_deployment_and_mechanics",
        ["autoinspect", "spot", "dock3", "gecko"],
        "Inspection success and intervention are distinct. Observation detection confusion matrices not yet calibrated.",
    ),
    "recovery": (
        "capability_boundaries_supported",
        ["taurob", "cdc90", "enapter", "wind2h2"],
        "Bounded actuation/cleaning/calibration are not generic equipment repair. No autonomous PEM stack swap evidence.",
    ),
    "support": (
        "named_specifications_available",
        ["gekko", "t4", "spot", "dock3", "ceora", "sampling"],
        "Explicit utilities, geometry, charging, operators and sampling lag replace generic support budgets in reference designs.",
    ),
    "maintenance": (
        "definitions_supported_incidence_open",
        ["hycred", "festo", "autoinspect", "wind2h2"],
        "Avoid mixing cycle reliability, active-time failure and calendar intervention; no universal repair success or lead time.",
    ),
    "economics": (
        "updated_external_benchmark",
        ["dea", "dea-brief"],
        "Dated European capacity-specific costs provide benchmark; no 450kW installed quote or field-robot service contract inferred.",
    ),
    "control": (
        "policy_choice",
        [],
        "Risk preferences, minimum run and horizon are policies unless named equipment imposes them. Test utility after calibrated observation/boundary changes.",
    ),
    "coupling": (
        "structural_change_required",
        ["density", "pem-data", "battery", "nist-water", "sampling"],
        "Support electricity, pressure heels, feed enthalpy and evidence arrival all compete with production.",
    ),
    "experiment": (
        "verification_choice",
        [],
        "Keep fixed seeds, publication boundaries and paired weather; parameter calibration split separate from policy evaluation split.",
    ),
}
old = json.loads((HERE.parent.parent / "docs" / "assumption-review.json").read_text())
assert set(GROUPS) == set(old["groups"])
coverage = {
    k: dict(title=old["groups"][k]["title"], status=v[0], sources=v[1], finding=v[2])
    for k, v in GROUPS.items()
}
parameters = [
    dict(path=p["path"], groups=p.get("groups"), original_classification=p.get("category"))
    for p in old["parameters"]
]
(HERE / "coverage.json").write_text(
    json.dumps(
        dict(
            schema_version="dispatch-lab/literature-coverage/1",
            baseline_registry="docs/assumption-review.json",
            scope="Group-level evidence progression. Does not relabel all individual parameters as calibrated.",
            groups=coverage,
            parameter_count=len(parameters),
        ),
        indent=2,
        ensure_ascii=False,
    )
    + "\n"
)
