"""Offline checks of evidence identities, data splits and independent references."""

import hashlib
import json
import math
import re
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit

import numpy as np
import pandas as pd
from analyse import density_z
from derived import calculate, enthalpy

HERE = Path(__file__).resolve().parent
checks = []


def record(name, condition, scope):
    checks.append(dict(name=name, outcome="passed" if bool(condition) else "failed", scope=scope))


def read(name):
    return json.loads((HERE / name).read_text())


def raises(call):
    try:
        call()
    except ValueError:
        return True
    return False


manifest = read("analysis/manifest.json")
record(
    "Analysis implementation identity",
    hashlib.sha256((HERE / "analyse.py").read_bytes()).hexdigest() == manifest["analysis_sha256"],
    "Exact saved implementation, not physical validation.",
)
record(
    "All recorded input identities",
    all(
        hashlib.sha256((HERE / p).read_bytes()).hexdigest() == h
        for p, h in manifest["inputs"].items()
    ),
    f"{len(manifest['inputs'])} input files including original numerical data and extraction protocol.",
)
record(
    "All analysis output identities",
    all(
        hashlib.sha256((HERE / "analysis" / p).read_bytes()).hexdigest() == h
        for p, h in manifest["outputs"].items()
    ),
    f"{len(manifest['outputs'])} calculated files.",
)
record(
    "Downloaded source hashes",
    all(
        hashlib.sha256((HERE / "raw" / p).read_bytes()).hexdigest() == d["sha256"]
        for p, d in read("downloads.json").items()
        if d["status"] == "downloaded"
    ),
    "Original retrieval identities checked; failed downloads remain failed.",
)
pv = pd.read_csv(HERE / "analysis/pv-predictions.csv", parse_dates=["datetime"])
train = pv[pv.split == "training"]
test = pv[pv.split == "holdout"]
record(
    "Solar observations are disjoint",
    not set(train.datetime) & set(test.datetime) and pv.datetime.nunique() == len(pv),
    "No timestamp appears in both fitting and evaluation.",
)
record(
    "Solar declared month partition",
    all(train.datetime.dt.month % 2 == 1) and all(test.datetime.dt.month % 2 == 0),
    "Chronologically blocked month partition, not a random adjacent-sample split.",
)
record(
    "Solar missing/threshold handling",
    len(pv) == 26023
    and np.isfinite(pv[["Gpoa", "AIR_TEMP", "Tbom", "WIND_SPEED"]]).all().all()
    and (pv.Gpoa >= 200).all(),
    "No accuracy/residual-dependent exclusions.",
)
stats = read("analysis/pv.json")
for model in ["NOCT45", "fitted_NOCT", "published_Faiman", "fitted_Faiman"]:
    saved = next(
        r for r in stats["scores"] if r["split"] == "holdout_even_months" and r["model"] == model
    )["rmse"]
    recomputed = math.sqrt(sum((test[model] - test.Tbom) ** 2) / len(test))
    record(
        f"Solar {model} held-out accounting",
        abs(saved - recomputed) < 1e-10,
        "Recomputed from saved observations/predictions, with independent scalar sum.",
    )
plateaus = pd.read_csv(HERE / "analysis/pem-plateaus.csv", parse_dates=["start", "end"])
record(
    "PEM split has eight matched plateaus",
    plateaus.groupby("segment")["split"].apply(lambda s: set(s) == {"training", "holdout"}).all()
    and plateaus.segment.nunique() == 8,
    "Same experiment; does not claim a second device or independent field campaign.",
)
record(
    "PEM training precedes test within each plateau",
    all(
        g[g.split == "training"].end.iloc[0] < g[g.split == "holdout"].start.iloc[0]
        for _, g in plateaus.groupby("segment")
    ),
    "No retained interval shared between fit and test.",
)
record(
    "PEM system electricity reconciles",
    np.allclose(
        plateaus.system_power,
        plateaus.smps_power + plateaus.chiller_power + plateaus.subsystem_power,
        atol=1e-10,
    ),
    "All three recorded support/electrical channels included at declared AC boundary.",
)
for t, p, z in [
    (200, 1, 1.00675450),
    (300, 10, 1.05985282),
    (400, 50, 1.24304763),
    (500, 200, 1.74461629),
    (200, 200, 2.85953449),
]:
    record(
        f"NIST independent Z point {t} K / {p} MPa",
        abs(density_z(p, t) - z) < 1e-8,
        "Published test point, not a fixture generated by this implementation.",
    )
record(
    "Density rejects out-of-domain inputs",
    raises(lambda: density_z(201, 293.15)) and raises(lambda: density_z(1, 149)),
    "No silent extrapolation outside correlation range.",
)
d = calculate()
chem = d["chemistry"]
record(
    "Gas-phase reaction enthalpy reference",
    abs(chem["standard_reaction_kj_per_mol"] + 165.0035) < 1e-9,
    "Independent arithmetic: -74.87310 + 2*(-241.8264) - (-393.5224).",
)
record(
    "Stoichiometric mass closure",
    abs(chem["mass_rounding_residual_kg_per_kg_ch4"]) < 1e-5,
    "Tolerance permits independent tabulated molecular-weight rounding.",
)
record(
    "Water coefficient range enforced",
    raises(lambda: enthalpy("water", 298.15)),
    "No evaluation of a 500 K-minimum Shomate polynomial at standard temperature.",
)
record(
    "Pressure heel and usable mass reconcile",
    all(
        abs(r["heel_kg"] + r["usable_mass_kg"] - 60) < 1e-10 and 0 < r["usable_mass_kg"] < 60
        for r in d["gas_storage"]
    ),
    "Conditional fixed-temperature storage states; not pressure-vessel approval.",
)
record(
    "Sampling flush matches independent exponential",
    abs(math.exp(-d["sampling"]["time_to_95_percent_replacement_min"]) - 0.05) < 1e-14,
    "Perfect mixing and specified actual volumetric flow only.",
)
record(
    "Reactor scope and uncertainty preserved",
    "Not ambient heat loss" in read("analysis/reactor.json")["scope"]
    and "no independent hold-out" in read("analysis/reactor.json")["fit"],
    "Digitized fit cannot become an ambient-UA calibration.",
)
battery = read("analysis/battery.json")["curve"]
record(
    "Battery published-curve domain",
    all(r["power_pu"] >= (0.15 if r["year"] < 4 else 0.1) for r in battery),
    "No first-three-year plotted values below tested minimum power.",
)
sources = read("sources.json")
profiles = read("reference-profiles.json")["profiles"]
coverage = read("coverage.json")
record(
    "Reference profile sources resolve",
    all(
        set(p["sources"]) <= set(sources)
        and (HERE / p["artifact"]).exists()
        and p["domain"]
        and p["promotion"]
        for p in profiles
    ),
    "Every profile has scope, evidence and an artifact; no default activation.",
)
original = json.loads((HERE.parent.parent / "docs/assumption-review.json").read_text())
record(
    "All original mechanism groups covered",
    set(coverage["groups"]) == set(original["groups"]) and coverage["parameter_count"] == 407,
    "Group-level evidence progression, not 407 newly calibrated parameters.",
)
md = (HERE / "report.md").read_text()
html = (HERE / "report.html").read_text()
record(
    "Narrative citation identities resolve",
    set(re.findall(r"\[\[([\w-]+)\]\]", md)) <= set(sources),
    "Narrative citations resolve to exact source records.",
)


class Links(HTMLParser):
    def __init__(self):
        super().__init__()
        self.hrefs = []
        self.ids = []

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if "id" in a:
            self.ids.append(a["id"])
        if tag == "a" and "href" in a:
            self.hrefs.append(a["href"])


links = Links()
links.feed(html)
record(
    "Unique report anchors",
    len(links.ids) == len(set(links.ids)),
    "Stable navigable report sections and source entries.",
)
record(
    "Local report links exist",
    all(
        (u[1:] in links.ids) if u.startswith("#") else (HERE / unquote(urlsplit(u).path)).exists()
        for u in links.hrefs
        if not urlsplit(u).scheme
    ),
    "Local attachments and in-report navigation checked; external link reachability recorded separately.",
)
record(
    "Offline self-contained report graphics",
    len(re.findall('src="data:image/png;base64,', html)) == 5 and 'src="http' not in html,
    "Five embedded plots and embedded font; external references remain links.",
)
result = dict(
    schema_version="dispatch-lab/literature-validation/1",
    scope="Numerical/provenance/document checks, not physical validation of the illustrative plant.",
    passed=sum(c["outcome"] == "passed" for c in checks),
    failed=sum(c["outcome"] == "failed" for c in checks),
    checks=checks,
)
(HERE / "validation.json").write_text(json.dumps(result, indent=2) + "\n")
print(f"{result['passed']} passed; {result['failed']} failed")
if result["failed"]:
    print(json.dumps([c for c in checks if c["outcome"] == "failed"], indent=2))
    raise SystemExit(1)
