"""Render the offline release account from saved, source-bound check receipts."""
import base64
import html
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
a = json.loads((HERE/'acceptance.json').read_text())
q = json.loads((HERE/'qualification.json').read_text()) if (HERE/'qualification.json').exists() else {'status':'Final checks running'}
e = html.escape
font = base64.b64encode((ROOT/'assets/fonts/DepartureMono-Regular.woff2').read_bytes()).decode()
checks = ''.join(f'<tr><td>{e(c["name"])}</td><td>{e(c["outcome"])}</td><td>{e(c["scope"])}</td></tr>' for c in q.get('checks',[]))
bundles = ''.join(f'<li><a href="../../{e(b["path"])}">{e(Path(b["path"]).name[:16])}… ZIP</a> · {b["bytes"]/1024**2:.1f} MiB compressed / {b["uncompressed_bytes"]/1024**2:.1f} MiB input; {len(b["omissions"])} omissions.</li>' for b in a['portable_bundles'])
body = f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dispatch Lab · Release 3</title>
<style>@font-face{{font-family:Departure;src:url(data:font/woff2;base64,{font})}}*{{box-sizing:border-box}}body{{margin:0;background:#222;color:#eabd80;font:15px/1.65 Departure,monospace}}main{{max-width:1100px;margin:auto;padding:48px 28px 100px}}a{{color:#ffad43;text-underline-offset:4px}}header{{padding:32px 0 42px;border-bottom:1px solid #72542e}}.eyebrow{{color:#ffab39}}h1{{font-size:clamp(30px,5vw,54px);line-height:1.25;color:#ffab39;font-weight:normal;max-width:900px}}h2{{font-size:24px;font-weight:normal;color:#ffab39;margin-top:52px}}p{{max-width:88ch}}.lede{{font-size:20px}}.note{{border-left:2px solid #e99830;padding:12px 20px;margin:24px 0}}.flow{{display:flex;flex-wrap:wrap;gap:8px;margin:28px 0}}.flow span{{border:1px solid #72542e;padding:12px}}table{{border-collapse:collapse;width:100%;font-size:13px}}th,td{{text-align:left;vertical-align:top;padding:14px 12px;border-bottom:1px solid #665032}}th{{color:#ffab39}}.scroll{{overflow:auto}}code{{overflow-wrap:anywhere}}li{{margin-bottom:10px}}footer{{margin-top:64px;border-top:1px solid #72542e;padding-top:24px;font-size:12px}}@media(max-width:600px){{main{{padding:24px 18px}}table{{min-width:650px}}.lede{{font-size:17px}}}}</style>
<main><header><div class="eyebrow">Dispatch Lab / Release 3 / 14 September 2026</div><h1>Learn from observations.<br>Compare decisions.</h1><p class="lede">The software workflow is delivered. Users can freeze observation datasets, fit and compare estimators, register bounded planning aids, run policy experiments and preserve their results.</p><p>The completion criterion is usable experiment machinery. Broad policy, site and seasonal campaigns remain user-run templates.</p></header>
<section><h2>Start in the application</h2><p>Open <strong>Sites → Production studies → Learning &amp; policies</strong>. Start with recorded episodes or “Try a constructed dataset”. No training or deployment happens merely by opening the workspace.</p><div class="flow"><span>Freeze episodes</span><span>Fit &amp; evaluate</span><span>Register policy</span><span>Run matched cases</span><span>Trace &amp; write up</span><span>Export &amp; restore</span></div><p><a href="../../docs/learning-and-policies.md">Complete operating guide</a> · <a href="../../docs/release-3.md">Release contract</a> · <a href="../../docs/roadmap.md">Updated roadmap</a></p></section>
<section><h2>What is implemented</h2><div class="scroll"><table><thead><tr><th>Release stage</th><th>Delivered capability</th><th>Boundary</th></tr></thead><tbody>
<tr><td>1 · Data</td><td>Observation-only packets; complete episode train/validation/test splits; overlapping weather exclusion; optional site/design/equipment holdouts; reconstructable source and adapter identities.</td><td>Retrospective truth and scoring labels are separate. Missing channels stay missing.</td></tr>
<tr><td>2 · Estimation</td><td>Fixed, adaptive and fitted ridge comparisons for observed PV, solar/PEM condition, removable soiling and completed phase duration. Training-only preprocessing, validation error bands and held-out reporting.</td><td>Assumed readings do not establish fault cause, irreversible degradation or remaining useful life. Censored durations remain exclusions in ridge; the existing duration likelihood handles that separate question.</td></tr>
<tr><td>3 · Deployment</td><td>Versioned data-only weights and protocols, explicit registry selection, shadow predictions or a first-future-interval PV planning aid; input, model, budget and fallback recorded.</td><td>No executable plugins, neural/RL trainer or real-plant actuation. Optical service reforecasting explicitly declines the scalar PV aid.</td></tr>
<tr><td>4 · Objectives</td><td>Mode-dependent battery, hydrogen, CO₂ and thermal reserve shortfalls, including forecast service energy. Matched reference Greedy and both MPC objectives remain available.</td><td>Preferences cannot override execution limits. Penalties are neither cash expenditure nor inventory sale proceeds. Support stock and unfinished jobs retain existing service rules.</td></tr>
<tr><td>5 · Studies</td><td>Learning workspace; three interactive Model lessons; original decision operands; fixed publications; numerical-edition comparison; participant response capture.</td><td>Actual participant comprehension remains untested. Predictive accuracy and operating value are separate results.</td></tr>
<tr><td>6 · Operations</td><td>Locked installation; bounded/cancellable workers sharing the study lease; input/disk budgets; immutable export inventories; offline reports and restored model/data/source artifacts.</td><td>Local restore is verified. No durable off-machine destination has been supplied. Memory admission caps and measured RSS are not a hard address-space limit.</td></tr>
</tbody></table></div></section>
<section><h2>A deliberately small saved walkthrough</h2><p>The fixture supplies 72 constructed observations across three independent teaching episodes. Four next-channel comparisons complete; the duration comparison correctly remains <strong>incomplete</strong> because no informative completed service clocks exist in this fixture.</p><p>The PV teaching example even makes the fixed baseline exact: fitting ridge produces a worse point prediction. This is useful as a workflow check, not a reason to rank policies. Missing and unsuccessful results are publishable.</p><p>A four-hour synthetic operating case was interrupted after two hours and resumed with its committed prefix unchanged. All four shadow inferences fell outside their training feature domain and explicitly fell back. A new numerical edition had <strong>{e(a['differences']['status'])}</strong>, with no missing intervals. The comparison excludes solver search logs, elapsed timings, presentation and detailed audit operands; it is not a blanket bitwise-equivalence claim.</p><p>Its original model and observations were restored from the portable bundle. A separate reserve-comparison recipe was frozen without executing the optional campaign.</p><p><a href="acceptance.json">Saved IDs, outcomes and differences</a> · <a href="acceptance.py">Reproducible walkthrough</a></p><ul>{bundles}</ul><p>These files remain local and ignored. Their compressed sizes include source capsules and original study dependencies, not just fitted weights.</p></section>
<section><h2>Software qualification</h2><p>{e(q.get('status',''))}</p><div class="scroll"><table><thead><tr><th>Check</th><th>Outcome</th><th>What it establishes</th></tr></thead><tbody>{checks}</tbody></table></div><p><a href="qualification.json">Source-bound qualification receipt</a> · <a href="source-review.md">Narrative and boundary review</a></p><p>Reviewed desktop and narrow-screen views preserve Departure Mono and the amber palette. The original plant and solar screenshot baselines have not been updated. No participant answers were inferred from browser automation.</p></section>
<section><h2>What remains after the software release</h2><ol><li><strong>Actual user walkthroughs.</strong> Use the six-question capture to observe mechanism understanding, assumptions, decision tracing, unconfirmed work, evidence limitations and context return. Record and resolve material misunderstandings.</li><li><strong>Durable preservation.</strong> Choose an off-machine destination; copy the required bundles and raw-input inventory, verify hashes and test a restore there. Local commits are not that backup.</li><li><strong>Evidence-driven algorithm extensions.</strong> Gather the observations needed for a specific decision, then add reviewed estimators or policies. Neural/RL training, broader scheduling aids and joint service-resource optimisation are future extensions, not hidden capabilities of the current ridge models.</li><li><strong>Field realism.</strong> Obtain equipment-specific capability, sensor/reference, thermal, service-duration and logistics evidence before treating simulated comparisons as deployment recommendations. These software tests cannot supply it.</li></ol><div class="note">The Release 3 software is usable. The participant and off-machine preservation gates are still open. Neither has been marked complete to make the release account look cleaner.</div></section>
<footer>Implementation tested: <code>{e(a['source']['revision'])}</code><br>Source content: <code>{e(a['source']['content_hash'])}</code><br>Report and acceptance-script additions explain the walkthrough’s dirty working-tree flag; the executable content hash matches the clean qualification source. Historical reports and their evidence remain unchanged. This HTML embeds its font and makes no network requests.</footer></main></html>'''
(HERE/'report.html').write_text(body)
