"""Offline, read-only publication from saved qualification operands; no new solves."""
import argparse
import base64
import html
import hashlib
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from methane.provenance import LOADED_FILES, LOADED_SOURCE
from methane.qualification_analysis import compact, comparisons, numerical_spreads, sensitivity_differences, recovery_windows
from methane.siting.store import digest

ROOT = Path(__file__).resolve().parent


def write(results_path, destination, *, performance=None):
    original = json.loads((ROOT / 'original-seville.json').read_text())
    results = json.loads(results_path.read_text())
    cases = results['cases']
    compact_cases = [compact(c) for c in cases]
    compare = comparisons(cases)
    repeats = numerical_spreads(cases)
    sensitivities = sensitivity_differences(cases)
    evidence = dict(version='autonomy-qualification-publication/1', programme=results['programme'], numerical_sources=sorted({c['source'] for c in cases}), reporting_source=LOADED_SOURCE['content_hash'], original_study=original[0]['study_id'], cases=compact_cases, comparisons=compare, numerical_spreads=repeats, sensitivities=sensitivities, recovery_windows=[dict(study_id=c["study_id"],case_id=c["case_id"],windows=recovery_windows(c)) for c in cases], full_operands=str(results_path.resolve()), full_operands_sha256=digest(results), performance=performance)
    evidence['publication_inputs_sha256']={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in ['writeup.py','interpretation.html','evidence-plan.json','next-steps.md','execution-notes.json','original-seville.json','check-report.cjs','performance.json'] if (ROOT/name).exists()}
    destination.parent.mkdir(parents=True,exist_ok=True)
    summary = destination.with_suffix('.json')
    if destination.exists() or summary.exists():
        raise ValueError('Publish to a new report edition; do not overwrite an original report')
    summary.write_text(json.dumps(evidence,indent=2,ensure_ascii=False))
    font=base64.b64encode(LOADED_FILES['assets/fonts/DepartureMono-Regular.woff2']).decode()
    esc=html.escape
    fmt=lambda x: '—' if x is None else f'{0 if abs(x) < .05 else x:,.1f}'
    original_table=''.join(f"<tr><td>{esc(c['controller'])}</td><td>{fmt(c['summary']['methane_kg'])}</td><td>{fmt(c['summary']['capacity_restored_hour'])}</td><td>{fmt(c['summary']['capacity_confirmed_hour'])}</td><td>{fmt(c['summary']['ending']['battery_kwh'])}</td><td>{fmt(c['summary']['ending']['h2_kg'])}</td></tr>" for c in original)
    outcomes=Counter(c['outcome'] for c in compact_cases)
    checked=Counter(c['checks']['status'] if c['checks'] else 'missing' for c in compact_cases)
    def series(c,label):
        return dict(label=label, study_id=c['study_id'], case_id=c['case_id'], rows=[dict(hour=r['hour'], time=r['time'], methane_kg=r['applied']['methane_kg'], battery_kwh=r['state']['battery_kwh'], h2_kg=r['state']['h2_kg'], co2_kg=r['state']['co2_kg'], temperature_c=r['state']['temperature_c'], actual_capacity_kw=r['truth_capacity_kw'], estimated_capacity_kw=r['diagnosis']['capacity_kw'], requested_kw=r['requested']['electrolyser_kw'], applied_kw=r['applied']['electrolyser_kw'], status=r['diagnosis']['status'], solver=r['solver']['status'], solver_details=r['solver'], pv_kw=r['pv_kw'], forecast=r['forecast_source'], human_hours=r['human_hours'], curtailment_kwh=r['curtailed_kwh']) for r in c['timeline']])
    data=dict(cases=compact_cases,series=[series(c,'Original / '+c['controller']) for c in original]+[series(c,c['group']+' / '+c['label']['pair']+' / '+c['label']['arm']+' / seed '+str(c['label']['seed'])+' / repeat '+str(c['label']['repetition'])) for c in cases])
    encoded=json.dumps(data,ensure_ascii=False).replace('<','\\u003c')
    findings=(ROOT/'interpretation.html').read_text() if (ROOT/'interpretation.html').exists() else '<p>The declared experiments are awaiting interpretation. This draft is not a completed qualification.</p>'
    gaps=(ROOT/'evidence-plan.json').read_text() if (ROOT/'evidence-plan.json').exists() else '{}'
    publications=json.loads((ROOT/'publications.json').read_text()) if (ROOT/'publications.json').exists() else []
    links=''.join('<li><a href="'+esc(x['relative_path'],quote=True)+'">'+esc(x['title'])+'</a></li>' for x in publications)
    links='<ul>'+links+'</ul>' if links else '<p>Individual Sites publications are not included in this edition.</p>'
    repeat_rows=''.join(f"<tr><td>{esc(r['group']+' / '+r['pair']+' / '+r['arm'])}</td><td>{r['completed']}/{r['declared']}</td><td>{fmt(r['spreads']['methane_kg'])}</td><td>{'Yes' if r['exact_physical_trace_identity'] is True else 'No' if r['exact_physical_trace_identity'] is False else 'Incomplete'}</td></tr>" for r in repeats)
    performance_text='<p>Performance qualification is not included in this edition.</p>'
    if performance:
        perf_rows=''.join('<tr><td>'+esc(m['label'])+'</td><td>'+fmt(m['observations']['first_input_ms'])+'</td><td>'+fmt(m['observations']['preview_p95_ms'])+'</td><td>'+fmt(m['observations']['render_p95_ms'])+'</td></tr>' for m in performance.get('measurements',[]))
        performance_text='<p>'+esc(performance.get('scope',''))+'</p><div class="scroll" tabindex="0" role="region" aria-label="Recorded interaction performance"><table><thead><tr><th>Measured condition</th><th>First edit / ms</th><th>Input p95 / ms</th><th>Render p95 / ms</th></tr></thead><tbody>'+perf_rows+'</tbody></table></div><p>'+esc(performance.get('interpretation',''))+'</p><details><summary>Samples, exploratory baseline and measurement limits</summary><pre>'+esc(json.dumps(performance,indent=2))+'</pre></details>'

    text='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>When can the plant manage itself? · Dispatch Lab</title><style>
@font-face{font-family:Departure;src:url(data:font/woff2;base64,FONT)}*{box-sizing:border-box}html{scroll-behavior:smooth}body{overflow-wrap:anywhere;margin:0;background:#202020;color:#d7c3a4;font:14px/1.85 Departure,monospace}main{max-width:1250px;margin:auto;padding:65px 5vw 100px}h1,h2,h3{font-weight:normal;color:#ffa631;line-height:1.4}h1{font-size:clamp(27px,4vw,48px);max-width:950px}h2{font-size:25px;margin-top:0}h3{font-size:17px}p{max-width:890px}a{color:#ffc56e}nav{display:flex;gap:20px;flex-wrap:wrap;border-block:1px solid #665139;padding:18px 0;margin:35px 0 65px}section{margin:65px 0;scroll-margin-top:20px}.eyebrow{color:#ffa631;font-size:12px;letter-spacing:2px}.note{border-left:2px solid #ffa631;padding:12px 22px;background:#28251f}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.card{border-top:1px solid #665139;padding-top:16px}.large{font-size:35px;color:#ffa631}.muted{color:#ad987a}.scroll{overflow:auto;max-width:100%}table{border-collapse:collapse;width:100%;font-size:12px}th,td{text-align:left;border-bottom:1px solid #514434;padding:11px;vertical-align:top;font-weight:normal}th{color:#ffa631}button,select,input{font:inherit;color:#ffd49a;background:#28251f;border:1px solid #806037;border-radius:0;padding:9px;max-width:100%}select{width:100%}label{display:block;margin:12px 0;color:#eec38a}input[type=range]{width:100%;accent-color:#ffa631;padding:0}button:focus-visible,select:focus-visible,input:focus-visible,a:focus-visible,.scroll:focus-visible{outline:2px solid #ffe0b5;outline-offset:4px}svg{width:100%;min-width:760px;height:auto;background:#232220;display:block;margin:18px 0}svg text{font:12px Departure,monospace;fill:#d7c3a4}.trace{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;max-height:310px;overflow:auto;border-left:1px solid #806037;padding:15px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.8 Departure}li{margin:12px 0}.filters{display:grid;grid-template-columns:1fr 1fr;gap:25px}.badge{border:1px solid #806037;padding:5px 10px;display:inline-block;margin:4px;font-size:12px}details{margin:25px 0}summary{cursor:pointer;color:#ffc56e}@media(max-width:700px){main{padding:30px 20px 60px}.grid,.filters{grid-template-columns:1fr}nav{gap:14px;margin-bottom:40px}h2{font-size:21px}section{margin:45px 0}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}
</style><main><p class="eyebrow">Dispatch Lab / Autonomous operation / 13–14 September 2026</p><h1>When can the plant manage itself?</h1><p>Forecasts, operating evidence and service resources interact. This programme follows those interactions through saved decisions, physical outcomes and costs—and keeps the unresolved cases visible.</p><nav aria-label="Report sections"><a href="#findings">Findings</a><a href="#original">Original counterexample</a><a href="#trace">Follow a run</a><a href="#experiments">Experiments</a><a href="#evidence">Evidence priorities</a><a href="#reproduce">Reproduce</a></nav>
<div class="grid"><div class="card"><span class="large">COUNT</span><br>declared executions</div><div class="card"><span class="large">HOURS</span><br>recorded hourly intervals</div><div class="card"><span class="large">CHECKED</span><br>independent numerical checks</div></div>
<section id="findings"><h2>What the comparisons establish</h2>FINDINGS<p class="note">These are conditional results under an illustrative plant and service system. Event frequencies, remedy effectiveness, thermal parameters and support logistics are not field-calibrated. No overall trust score or autonomous-site success probability is calculated.</p></section>
<section id="original"><h2>Start with the counterexample</h2><p>The original three-day Seville example compared controller packages. Greedy used its local service rule and version-1 recovery scheduler; MPC used coordinated service and version-4 recovery. They shared weather, plant, fault and prices, but this was not an isolated test of the production objective.</p><div class="scroll" tabindex="0" role="region" aria-label="Original outcomes"><table><thead><tr><th>Original controller</th><th>CH₄ / kg</th><th>Physical restoration / H</th><th>Full confirmation / H</th><th>Ending battery / kWh</th><th>Ending H₂ / kg</th></tr></thead><tbody>ORIGINAL</tbody></table></div><p>Blank confirmation means it was not recorded before the comparison ended. Physical restoration is retrospective simulator truth. Stored hydrogen and electricity remain inventories; they are not added to methane or credited with sale proceeds.</p></section>
<section id="trace"><h2>Follow the recorded sequence</h2><p>Select an original or new case, then move the clock. No values here are recalculated or sent back to the controller. Inventory and diagnostic estimates are recorded after the selected interval; timestamps identify its UTC start.</p><label for="trace-case">Recorded case</label><select id="trace-case"></select><div class="scroll" tabindex="0" role="region" aria-label="Recorded trajectories"><svg id="plot" viewBox="0 0 1000 520" role="img" aria-label="Recorded methane, battery, temperature and capacity trajectories"></svg></div><label for="hour">Completed interval <output id="hour-label"></output></label><input id="hour" type="range" min="0" value="0"><pre class="trace" id="trace-values" tabindex="0" aria-label="Selected original operands"></pre></section>
<section id="experiments"><h2>The complete declared programme</h2><p>The 105 cases separate five questions: the original package and numerical budget; a common local-service objective comparison; observer and deadline ablations; support, energy, thermal and forecast sensitivities; and seven-day exposures in London, Seville and Copenhagen in January, April and July 2025. Seasonal cases use ERA5 and previous-day persistence. The July Seville fault cases use original ECMWF issues, except the explicitly labelled prediction multiplier.</p><div class="filters"><label>Question<select id="group"><option value="">All groups</option></select></label><label>Capacity outcome<select id="outcome"><option value="">All outcomes</option></select></label></div><p id="case-count" aria-live="polite"></p><div class="scroll" tabindex="0" role="region" aria-label="All declared experiment cases"><table><thead><tr><th>Case</th><th>Outcome</th><th>Hours</th><th>CH₄ kg</th><th>Contribution €</th><th>Allocated €</th><th>Visits / crew h</th><th>Limited / fallback</th><th>Checks</th></tr></thead><tbody id="cases"></tbody></table></div><p>Contribution uses the original illustrative methane value minus variable inputs and wear. Allocated cost is a separate view. These conditional period costs do not establish annual maintenance cost or project profitability. “No simulated capacity loss” does not mean sensors were healthy or diagnosis was correct; flow-bias cases have separate diagnostic records.</p><h3>Numerical reproducibility</h3><p>The same inputs can yield different feasible time-limited plans. These are repeated computations, not independent weather draws. Incomplete repetitions are never treated as zero spread.</p><div class="scroll" tabindex="0" role="region" aria-label="Numerical repeat spread"><table><thead><tr><th>Repeated arm</th><th>Completed</th><th>CH₄ spread / kg</th><th>Exact physical trace</th></tr></thead><tbody>REPEATS</tbody></table></div><details><summary>Pairing, changed parameters and uncertainty operands</summary><p>The companion JSON records every actual configuration and policy difference, source/weather identity, numerical repeat and conditional sensitivity. Multiple simultaneous changes are disclosed; a difference is not automatically an isolated causal effect.</p><a href="SUMMARY">Open compact recorded comparisons</a></details></section>
<section id="evidence"><h2>What evidence should come next?</h2><p>Use the sensitivity results to choose measurements and quotations, while retaining the structural gaps. A repair probability cannot make an incompatible robot capable of a task.</p><div id="evidence-cards"></div><p class="note">The parameter registry still labels key thermal, repair and crew-response quantities as unmeasured assumptions. Other inputs have literature priors rather than site calibration. The parameter-bound validation range is not a plausible engineering range. Existing source references and parameter identities are preserved in the evidence plan.</p><h3>Interaction performance</h3>PERFORMANCE</section>
<section id="reproduce"><h2>Read, repeat, or change the plant</h2><p><a href="next-steps.md">The next controller and evidence gates</a></p>PUBLICATIONS<ol><li>Read the immutable case in Sites, open its original period, and inspect the decision at the recorded hour.</li><li>Use a new numerical repetition for the same frozen inputs. Keep solver limits and execution environment in the comparison.</li><li>Use <code>prepare --basis CONFIG.json</code> for changed plant parameters. Review the declared scenario overrides, then execute the new programme edition.</li><li>For offline reproduction, retain original source capsules, raw inputs and checkpoints alongside the committed report. Git alone does not contain those large local artifacts.</li></ol><p><a href="README.md">Protocol and commands</a> · <a href="evidence-plan.json">Evidence acquisition plan</a> · <a href="SUMMARY">Compact result edition</a></p><p>The initial study capsules retain their original stale Sites narrative review and unavailable saved Sites teaching example. The later review applies to the current application, not retroactively to those archives. Other original explanations and numerical operands remain recorded. <a href="execution-notes.json">Execution and review notes</a> disclose this and the resumed worker interruption.</p><p>Preparation and reporting do not fetch network data. Missing inputs are not replaced with synthetic weather. The three seasonal anchors are regional coordinates, not surveyed deployable parcels. One already-used historical year does not establish interannual robustness. Additional hardware families, predictive maintenance and learned policies remain outside this programme.</p><p class="muted">Programme: PROGRAMME<br>Original operands: OPERANDS<br>Evidence: EVIDENCE</p></section></main><script type="application/json" id="data">DATA</script><script type="application/json" id="gaps">GAPS</script><script>
const data=JSON.parse(document.getElementById('data').textContent),gaps=JSON.parse(document.getElementById('gaps').textContent),$=id=>document.getElementById(id),num=x=>x==null?'—':(Math.abs(Number(x))<.05?0:Number(x)).toLocaleString(undefined,{maximumFractionDigits:1});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('select').forEach(n=>n.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey)return;const changes={ArrowUp:-1,ArrowDown:1};if(!(event.key in changes)&&event.key!=='Home'&&event.key!=='End')return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?n.options.length-1:Math.max(0,Math.min(n.options.length-1,n.selectedIndex+changes[event.key]));if(next!==n.selectedIndex){n.selectedIndex=next;n.dispatchEvent(new Event('change',{bubbles:true}));}}));
data.series.forEach((s,i)=>$('trace-case').add(new Option(s.label,i)));[...new Set(data.cases.map(c=>c.group))].forEach(x=>$('group').add(new Option(x,x)));[...new Set(data.cases.map(c=>c.outcome))].forEach(x=>$('outcome').add(new Option(x,x)));
function table(){const rows=data.cases.filter(c=>(!$('group').value||c.group===$('group').value)&&(!$('outcome').value||c.outcome===$('outcome').value));$('case-count').textContent=rows.length+' of '+data.cases.length+' declared executions; unsuccessful and incomplete cases remain selectable.';$('cases').innerHTML=rows.map(c=>`<tr><td>${esc(c.label.pair+' / '+c.label.arm)}<br><span class="muted">seed ${c.label.seed} / repeat ${c.label.repetition} / ${c.case_id}</span></td><td>${esc(c.outcome)}</td><td>${c.hours}/${c.expected_hours}</td><td>${num(c.metrics.methane_kg)}</td><td>${num(c.metrics.assumed_contribution_eur)}</td><td>${num(c.metrics.total_eur)}</td><td>${num(c.human_visits)} / ${num(c.human_hours)}</td><td>${num(c.metrics.limited_solves)} / ${num(c.metrics.fallbacks)}</td><td>${esc(c.checks?.status||'missing')}</td></tr>`).join('')}
function trace(){const s=data.series[Number($('trace-case').value)],rows=s.rows;$('hour').max=Math.max(0,rows.length-1);const index=Math.min(Number($('hour').value),rows.length-1),r=rows[index];if(!r){$('plot').innerHTML='';$('hour-label').textContent='unavailable';$('trace-values').textContent='No completed intervals';return}let cumulative=0;const series=rows.map(x=>({...x,cumulative:(cumulative+=x.methane_kg)})),tracks=[['cumulative','Cumulative methane / kg','#ffa631'],['battery_kwh','Battery inventory / kWh','#ffa631'],['temperature_c','Reactor temperature / °C','#ffa631'],['actual_capacity_kw','Capacity / kW: truth amber, estimate white','#a27338']];let svg='';tracks.forEach(([key,title,color],t)=>{const top=30+t*125,max=Math.max(1,...series.map(x=>x[key]),key==='actual_capacity_kw'?Math.max(...series.map(x=>x.estimated_capacity_kw)):0),line=k=>series.map((x,i)=>(i?'L':'M')+(120+i*850/Math.max(1,series.length-1)).toFixed(1)+' '+(top+75-x[k]/max*65).toFixed(1)).join(' ');svg+=`<text x="12" y="${top}">${title}</text><text x="12" y="${top+45}">${num(series[index][key])}</text><path d="M120 ${top+75}H970" stroke="#574633"/><path d="${line(key)}" stroke="${color}" stroke-width="2" fill="none"/>`;if(key==='actual_capacity_kw')svg+=`<path d="${line('estimated_capacity_kw')}" stroke="#e5ddce" stroke-dasharray="6 4" fill="none"/>`});const x=120+index*850/Math.max(1,rows.length-1);svg+=`<path d="M${x} 20V490" stroke="#ffe5bd" opacity=".5"/>`;$('plot').innerHTML=svg;$('hour-label').textContent='H'+(r.hour+1)+' / starting '+r.time;$('trace-values').textContent=JSON.stringify({interval:r.hour,time:r.time,requested_electrolyser_kw:r.requested_kw,applied_electrolyser_kw:r.applied_kw,diagnostic_status:r.status,estimated_capacity_kw:r.estimated_capacity_kw,retrospective_true_capacity_kw:r.actual_capacity_kw,solver:r.solver_details,forecast_source:r.forecast,human_work_hours:r.human_hours,ending_h2_kg:r.h2_kg,ending_co2_kg:r.co2_kg,curtailed_kwh:r.curtailment_kwh},null,2)}
$('trace-case').addEventListener('change',()=>{$('hour').value=0;trace()});$('hour').addEventListener('input',trace);$('group').addEventListener('change',table);$('outcome').addEventListener('change',table);$('evidence-cards').innerHTML=(gaps.items||[]).map(x=>`<article class="card"><h3>${esc(x.title)}</h3><p>${esc(x.reason)}</p><p><strong>Collect:</strong> ${esc(x.collect)}</p><p class="muted">${esc(x.boundary)}</p></article>`).join('');table();trace();
</script></html>'''
    values=dict(PUBLICATIONS=links,FONT=font,COUNT=str(len(cases)),HOURS=f"{sum(c['hours'] for c in cases):,}",CHECKED=f"{sum((c.get('independent_check') or {}).get('checks',0) for c in cases):,}",FINDINGS=findings,ORIGINAL=original_table,REPEATS=repeat_rows,SUMMARY=summary.name,PERFORMANCE=performance_text,PROGRAMME=esc(results['programme']),OPERANDS=esc(str(results_path.resolve())),EVIDENCE=esc(json.dumps(dict(checks=checked,outcomes=outcomes))),DATA=encoded,GAPS=gaps.replace('<','\\u003c'))
    # Replace exact sentinels once to avoid interpreting embedded authored data.
    import re
    text=re.sub('|'.join(sorted(values,key=len,reverse=True)),lambda m:values[m[0]],text)
    destination.write_text(text)
    return summary

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('results',type=Path);parser.add_argument('destination',type=Path);parser.add_argument('--performance',type=Path);args=parser.parse_args()
    write(args.results,args.destination,performance=json.loads(args.performance.read_text()) if args.performance else None)
